In [1]:
# !python3 -m pip install --upgrade telethon

In [1]:
from telethon.sync import TelegramClient
import datetime
import pandas as pd

# Remember to use your own values from my.telegram.org!
api_id = 23316483
api_hash = "41e58d027579ade30d3e505a48fe3679"
client = TelegramClient("stock", api_id, api_hash)

In [15]:
# # chats = ['smartboursegroup', 'close_trades','smartbourse_com','hezartahlil_g','saahmii','amir_ramzali','fundamental_View','MajidSoltany','Goldenn_Bourse']
# chats = ["smartboursegroup"]
# # import datetime
# # client =  TelegramClient('test', api_id, api_hash)
# df = pd.DataFrame()
# async with TelegramClient("stock", api_id, api_hash) as client:
#     for chat in chats:
#         chats = client.iter_messages(
#             chat, offset_date=datetime.date.today(), reverse=True
#         )
#         async for message in chats:
#             print(message)
#             data = {
#                 "group": chat,
#                 "sender": message.sender_id,
#                 "text": message.text,
#                 "date": message.date,
#             }

#             temp_df = pd.DataFrame(data, index=[1])
#             df = df.append(temp_df)

# df["date"] = df["date"].dt.tz_localize(None)

# df.to_excel("telegrammmm.xlsx".format(datetime.date.today()), index=False)

MessageService(id=79654, peer_id=PeerChannel(channel_id=1727038436), date=datetime.datetime(2023, 5, 26, 1, 46, 40, tzinfo=datetime.timezone.utc), action=MessageActionChatJoinedByLink(inviter_id=1087968824), out=False, mentioned=False, media_unread=False, silent=False, post=False, legacy=False, from_id=PeerUser(user_id=143570098), reply_to=None, ttl_period=None)

ValueError: DataFrame constructor not properly called!

In [2]:
import tiktoken
import os
from parsivar import Normalizer
import pandas as pd
import numpy as np
import json
import shortuuid
import regex as re
import time
from functools import reduce
import openai  # for OpenAI API calls
from tenacity import (
    retry,
    stop_after_attempt,
    wait_random_exponential,
)  # for exponential backoff
import telethon

# from openai.embeddings_utils import get_embedding, cosine_similarity;
# import matplotlib

### Openai api notes for embedding

1. Embedding :

-   Each input must not exceed 8192 tokens in length.
-   Model Name => text-embedding-ada-002

In [3]:
# uuid = shortuuid.ShortUUID(alphabet="0123456789abcdefghijklmnopqrstuvwxyz")
enc = tiktoken.get_encoding("cl100k_base")
pd.set_option("display.max_rows", None)
openai.api_key = "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"

In [4]:
# with open('../../dataset/majid/result.json', encoding='utf-8') as file:
#     maj = json.loads(file.reaad())
# maj

In [5]:
# with open('../../dataset/BOURSGRAM/boursgram.json', encoding='utf-8') as file:
#     boursgram_data = json.loads(file.read())
# boursgram_data

In [6]:
# with open('result.json', encoding='utf-8') as file:
#     result = json.loads(file.read())
# len(result)

In [4]:
stocks = pd.read_csv("../stocks/stocks_tsetmcs.csv")
stocks = stocks[["sym_name", "name", "sym", "gp_name"]]
exlude_list = ["ما", "تمدن"]
stocks = stocks[~stocks["sym_name"].isin(exlude_list)]
stocks.head()

,sym_name,name,sym,gp_name
0,18719101,اوراق مشاركت ايران‌ خودرو,IKCQ1,خودرو و ساخت قطعات
1,آباد,توريستي ورفاهي آبادگران ايران,ABAD1,هتل و رستوران
2,آبادا,توليد نيروي برق آبادان,NBAB1,عرضه برق، گاز، بخاروآب گرم
3,آبادح,ح . ‌توريستي‌ورفاهي‌آبادگران‌,ABAX1,هتل و رستوران
4,آپ,آسان پرداخت پرشين,APPE1,رايانه و فعاليت‌هاي وابسته به آن

In [5]:
# txt="""# فولاژ
# در آستانه صف خرید به دلیل رشد 50 درصدی متوقف شد
#     """

# with open('./stocks/stk_id.json', encoding='utf-8') as file:
#     stocks = json.loads(file.read())
# len(stocks)
# stocks


def norm(txt):
    return Normalizer().normalize(txt)


def compute_token_count(txt):
    return len(enc.encode(txt))


# def if_chatlist_id_included(chatlist, ID):
#     #     print("CHATLIS__",chat_list)
#     for chat in chatlist:
#         if ID in chat["id_list"]:
#             return True
#     return False


def is_id_in_chatlist(chatlist, ID):
    #     print("CHATLIS__",chat_list)
    for chat in chatlist:
        if ID == chat["chat_id"]:
            return True
    return False


# def if_stock_included(txt):
#     for index, row in stocks.iterrows():
#         if norm(row["sym_name"]) in norm(txt):
#             #             print("if_stock_included__")
#             #             print(f"_*_{norm(txt)}_*_",row["sym_name"])
#             return True
#     return False


# if stock name is included in the text it will be replaced by stocks ID RETURNS: (if_is_included,text)
def if_stock_included_replace(txt):
    txt = norm(txt)
    #     txt_list=txt.split()

    for index, row in stocks.iterrows():
        norm_sym = norm(row["sym_name"]).replace("\u200c", " ")
        # txt = re.sub(rf"\b{norm_sym}\b", f"<{row['sym']}>", txt)
        txt = re.sub(rf"\b{norm_sym}\b", f"<{norm_sym}>", txt)
    #     print("replace_stock_with_idـ",norm_sym)
    # if re.findall(r"<[0-9A-Za-z]*>", txt):

    if re.findall(r"<[آا-ی\s]*>", txt):
        return True, txt
    return False, txt


def clean_text(txt):
    replacement_patterns = {
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+": "",  # website
        r"[\w\.-]+@[\w\.-]+": "",  # email
        r"@[A-Za-z0-9]*": "",  # @ID
        r"#": "",
        r"\n{2,}": "\n",
    }
    for pattern, replacement in replacement_patterns.items():
        txt = re.sub(pattern, replacement, txt)
    return txt

In [75]:
# with open('./majid/result.json', encoding='utf-8') as file:
#     maj = json.loads(file.read())
# maj

### Preprocessing public_supergroup

-   GROUPS List :
    1. BOURSGRAM بورسگرام

In [6]:
SUBGROUPS = {
    "1727038436": {
        "name": "بورسگرام | Boursegram",
        "40231": {"name": "غذایی"},
        "40209": {"name": "حمل و نقل"},
        "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
        "40211": {"name": "بانکها"},
        "40302": {"name": "خودرو و ساخت قطعات"},
        "48994": {"name": "آپشن (اختیار معامله)"},
        "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
        "40230": {"name": "دارویی"},
        "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
        "40203": {"name": "انبوه سازي_ساختمانی"},
        "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
        "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
        "40253": {"name": "زراعت"},
        "40236": {"name": "قند و شكر"},
        "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
        "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
        "40206": {
            "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
        },
        "40207": {"name": "بیمه"},
        "40227": {"name": "محصولات شيميايي"},
        "40219": {"name": "سیمان"},
        "40210": {"name": "لیزینگ"},
        "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
        "40247": {"name": "لاستيك و پلاستيك"},
        "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
        "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
        "40217": {"name": "هتل و رستوران"},
        "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
        "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
        "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
    }
}

# BOURSGRAM_SUBGROUPS = {
#     "40231": {"name": "غذایی"},
#     "40209": {"name": "حمل و نقل"},
#     "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
#     "40211": {"name": "بانکها"},
#     "40302": {"name": "خودرو و ساخت قطعات"},
#     "48994": {"name": "آپشن (اختیار معامله)"},
#     "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
#     "40230": {"name": "دارویی"},
#     "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
#     "40203": {"name": "انبوه سازي_ساختمانی"},
#     "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
#     "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
#     "40253": {"name": "زراعت"},
#     "40236": {"name": "قند و شكر"},
#     "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
#     "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
#     "40206": {
#         "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
#     },
#     "40207": {"name": "بیمه"},
#     "40227": {"name": "محصولات شيميايي"},
#     "40219": {"name": "سیمان"},
#     "40210": {"name": "لیزینگ"},
#     "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
#     "40247": {"name": "لاستيك و پلاستيك"},
#     "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
#     "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
#     "40217": {"name": "هتل و رستوران"},
#     "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
#     "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
#     "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
# }

In [21]:
"40202" in BOURSGRAM_SUBGROUPS
# BOURSGRAM_SUBGROUPS["40202"]

{'name': 'رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري'}

In [7]:
# COMMUNITIES = ["smartboursegroup"]
COMMUNITIES = {
    "1727038436": {
        "name": "بورسگرام | Boursegram",
        "name_id": "smartboursegroup",
        "type":"public_supergroup",
        "topics": {
            "40231": {"name": "غذایی"},
            "40209": {"name": "حمل و نقل"},
            "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
            "40211": {"name": "بانکها"},
            "40302": {"name": "خودرو و ساخت قطعات"},
            "48994": {"name": "آپشن (اختیار معامله)"},
            "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
            "40230": {"name": "دارویی"},
            "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
            "40203": {"name": "انبوه سازي_ساختمانی"},
            "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
            "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
            "40253": {"name": "زراعت"},
            "40236": {"name": "قند و شكر"},
            "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
            "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
            "40206": {
                "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
            },
            "40207": {"name": "بیمه"},
            "40227": {"name": "محصولات شيميايي"},
            "40219": {"name": "سیمان"},
            "40210": {"name": "لیزینگ"},
            "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
            "40247": {"name": "لاستيك و پلاستيك"},
            "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
            "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
            "40217": {"name": "هتل و رستوران"},
            "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
            "40249": {
                "name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"
            },
            "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
        },
    }
}

In [51]:
for key,val in COMMUNITIES.items():
    print(key,val)

1727038436 {'name': 'بورسگرام | Boursegram', 'name_id': 'smartboursegroup', 'type': 'public_supergroup', 'topics': {'40231': {'name': 'غذایی'}, '40209': {'name': 'حمل و نقل'}, '40783': {'name': 'روند و\u200c پیش بینی بازار_شاخص کل و شاخص هموزن'}, '40211': {'name': 'بانکها'}, '40302': {'name': 'خودرو و ساخت قطعات'}, '48994': {'name': 'آپشن (اختیار معامله)'}, '40212': {'name': 'سرمایه گذاریها_چند رشته اي صنعتي'}, '40230': {'name': 'دارویی'}, '40246': {'name': 'فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن'}, '40203': {'name': 'انبوه سازي_ساختمانی'}, '40232': {'name': 'نیروگاهها (عرضه برق، گاز، بخاروآب گرم)'}, '40248': {'name': 'پالایشی (فراورده هاي نفتي)_استخراج نفت گاز'}, '40253': {'name': 'زراعت'}, '40236': {'name': 'قند و شكر'}, '40778': {'name': 'بورس کالا_دلار، سکه، طلا_عرضه اولیه'}, '40208': {'name': 'برقی-مخابرات_ساخت دستگاه\u200cها و وسايل ارتباطي'}, '40206': {'name': 'فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط'}, '40207': {'name': 'بیمه'}, '40227': {'name': 'محصولات شيميايي'}, '40219': {'name': 'سیمان'}, '40210': {'name': 'لیزینگ'}, '40200': {'name': 'خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي'}, '40247': {'name': 'لاستيك و پلاستيك'}, '40221': {'name': 'خرده فروشی_تجارت عمده فروشی'}, '40218': {'name': 'ساير محصولات كاني غيرفلزي_کاشی و سرامیک'}, '40217': {'name': 'هتل و رستوران'}, '40242': {'name': 'ماشين آلات و تجهيزات_ساخت محصولات فلزي'}, '40249': {'name': 'محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری'}, '40202': {'name': 'رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري'}}}

In [32]:
# chats = ['smartboursegroup', 'close_trades','smartbourse_com','hezartahlil_g','saahmii','amir_ramzali','fundamental_View','MajidSoltany','Goldenn_Bourse']
# COMMUNITIES = ["smartboursegroup"]
all_chat_list = {
    community["name_id"]: {
        "id": None,
        "community_name": None,
        "messages": [],
    }
    for key ,community in COMMUNITIES.items()
}
#  {community: {"id": None, "messages": []}} for community in communities}

# import datetime
# client =  TelegramClient('test', api_id, api_hash)
# df = pd.DataFrame()
# all_chat_list = []
async with TelegramClient("stock", api_id, api_hash) as client:
    for community_name , value in COMMUNITIES.items():
        community_name_id = value["name_id"]
        all_chat_list[community_name_id]["community_name"] = community_name_id
        all_chat_list[community_name_id]["type"] = value["type"]
        
        chats = client.iter_messages(
            community_name_id, offset_date=datetime.date.today(), reverse=True
        )

        async for message in chats:
            if not message.action:
                print(message)
                data = {
                    # "group": community,
                    "chat_id": message.id,  ###
                    "person_id": message.sender_id,  ###
                    "org_text": message.text,  #
                    "date": message.edit_date if message.edit_date else message.date,  #
                    # "action": message.action if message.action else None,  #
                    "reply_to_message_id": message.reply_to.reply_to_msg_id
                    if message.reply_to
                    else None,  ##
                }
                # data["date"] = data.edit_date if data.edit_date else data.date
                # chat_info = {
                # "person_id": mess["from_id"],
                # "chat_id": mess["id"],
                # "date": date,
                # "date_unixtime": date_unixtime,
                # "org_txt": txt,
                # "reply_to_message_id": "",
                # "text": rep_txt,
                # }

                all_chat_list[community_name_id]["id"] = message.peer_id.channel_id
                all_chat_list[community_name_id]["messages"].append(data)

                # temp_df = pd.DataFrame(data, index=[1])
                # df = df.append(temp_df)

# df['date'] = df['date'].dt.tz_localize(None)

# df.to_excel("telegrammmm.xlsx".format(datetime.date.today()), index=False)
all_chat_list

PhoneNumberInvalidError: The phone number is invalid (caused by SendCodeRequest)

In [58]:
# %%time
def preprocess_subgroup2(data: object):
    data_id = str(data["id"])
    
    print("__> preprocess_subgroup", data["community_name"])
    # messages = boursgram_data["messages"]
    chat_list = []
    for mess in data["messages"]:
        txt = clean_text(mess["org_text"])
        print("__> chat_id", mess["chat_id"])

        if compute_token_count(txt) > 500:
            continue
        
        is_stock_included, rep_txt = if_stock_included_replace(txt.strip())
        mess["text"] = rep_txt

        if (
            ("reply_to_message_id" in mess)
            and (
                (  ## checks in public_supergroup that have subgroups,wheter the replied messaged is not replied to the subgroup ID
                    data["type"] == "public_supergroup"
                    and (data_id in SUBGROUPS)
                    and (mess["reply_to_message_id"] not in SUBGROUPS[data_id])
                )
                or (data["type"] != "public_supergroup")
            )
            and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
        ):
            # chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
            #         txt_rep = replace_stock_with_id(txt.strip())
            # chat_info["text"] = txt
            chat_list.append(mess)
            #                 print(cht["id_list"])
            # print("looooool")
        #     is_included,txt = replace_stock_with_id(txt.strip())
        elif is_stock_included:
            # chat_info["text"] = txt
            chat_list.append(mess)

    return {**data, "messages": chat_list}


# print(chat_list_1)
#

In [59]:
prepro_list = preprocess_subgroup2(all_chat_list["smartboursegroup"])
# all_chat_list['smartboursegroup']

__> preprocess_subgroup smartboursegroup
__> chat_id 79909
__> chat_id 79910
__> chat_id 79911
__> chat_id 79913
__> chat_id 79914
__> chat_id 79915
__> chat_id 79916
__> chat_id 79918
__> chat_id 79919
__> chat_id 79924
__> chat_id 79925
__> chat_id 79926
__> chat_id 79927
__> chat_id 79928
__> chat_id 79929
__> chat_id 79932
__> chat_id 79933
__> chat_id 79934
__> chat_id 79935
__> chat_id 79936
__> chat_id 79937
__> chat_id 79938
__> chat_id 79939
__> chat_id 79941
__> chat_id 79942
__> chat_id 79943
__> chat_id 79944
__> chat_id 79945
__> chat_id 79946
__> chat_id 79947
__> chat_id 79948
__> chat_id 79949
__> chat_id 79950
__> chat_id 79951
__> chat_id 79952
__> chat_id 79953
__> chat_id 79954
__> chat_id 79955
__> chat_id 79956
__> chat_id 79957
__> chat_id 79958
__> chat_id 79959
__> chat_id 79960
__> chat_id 79961
__> chat_id 79962
__> chat_id 79963
__> chat_id 79964
__> chat_id 79967
__> chat_id 79968
__> chat_id 79969
__> chat_id 79970
__> chat_id 79971
__> chat_id 79972
__> chat_id 79973
__> chat_id 79974
__> chat_id 79975
__> chat_id 79976
__> chat_id 79977
__> chat_id 79978
__> chat_id 79979
__> chat_id 79980
__> chat_id 79981
__> chat_id 79982
__> chat_id 79983
__> chat_id 79984
__> chat_id 79985
__> chat_id 79986
__> chat_id 79987
__> chat_id 79988
__> chat_id 79989
__> chat_id 79990
__> chat_id 79991
__> chat_id 79992
__> chat_id 79995
__> chat_id 79996
__> chat_id 79997
__> chat_id 79998
__> chat_id 79999
__> chat_id 80000
__> chat_id 80001
__> chat_id 80002
__> chat_id 80003
__> chat_id 80004
__> chat_id 80005
__> chat_id 80006
__> chat_id 80007
__> chat_id 80008
__> chat_id 80009
__> chat_id 80010
__> chat_id 80011
__> chat_id 80012
__> chat_id 80013
__> chat_id 80014
__> chat_id 80015
__> chat_id 80016
__> chat_id 80017
__> chat_id 80018
__> chat_id 80019
__> chat_id 80020
__> chat_id 80021
__> chat_id 80022
__> chat_id 80023
__> chat_id 80024
__> chat_id 80025
__> chat_id 80026
__> chat_id 80027
__> chat_id 80028
__> chat_id 80029
__> chat_id 80030
__> chat_id 80031
__> chat_id 80032
__> chat_id 80033
__> chat_id 80034
__> chat_id 80035
__> chat_id 80036
__> chat_id 80037
__> chat_id 80038
__> chat_id 80039
__> chat_id 80040
__> chat_id 80041
__> chat_id 80042
__> chat_id 80043
__> chat_id 80044
__> chat_id 80045
__> chat_id 80046
__> chat_id 80047
__> chat_id 80048
__> chat_id 80049
__> chat_id 80050
__> chat_id 80051
__> chat_id 80052
__> chat_id 80053
__> chat_id 80054
__> chat_id 80055
__> chat_id 80056
__> chat_id 80057
__> chat_id 80058
__> chat_id 80059
__> chat_id 80060
__> chat_id 80061
__> chat_id 80062
__> chat_id 80063
__> chat_id 80064
__> chat_id 80065
__> chat_id 80066
__> chat_id 80067
__> chat_id 80068
__> chat_id 80069
__> chat_id 80070
__> chat_id 80071
__> chat_id 80072
__> chat_id 80073
__> chat_id 80074
__> chat_id 80075
__> chat_id 80076
__> chat_id 80077
__> chat_id 80078
__> chat_id 80079
__> chat_id 80080
__> chat_id 80081
__> chat_id 80082
__> chat_id 80083
__> chat_id 80084
__> chat_id 80085
__> chat_id 80086
__> chat_id 80087
__> chat_id 80088
__> chat_id 80089
__> chat_id 80090
__> chat_id 80091
__> chat_id 80092
__> chat_id 80093
__> chat_id 80094
__> chat_id 80095
__> chat_id 80096
__> chat_id 80097
__> chat_id 80098
__> chat_id 80099
__> chat_id 80100
__> chat_id 80101
__> chat_id 80102
__> chat_id 80103
__> chat_id 80104
__> chat_id 80105
__> chat_id 80106
__> chat_id 80107
__> chat_id 80108
__> chat_id 80109
__> chat_id 80110
__> chat_id 80111
__> chat_id 80112
__> chat_id 80115
__> chat_id 80116
__> chat_id 80117
__> chat_id 80118
__> chat_id 80119
__> chat_id 80122
__> chat_id 80123
__> chat_id 80126
__> chat_id 80127
__> chat_id 80128
__> chat_id 80129
__> chat_id 80130
__> chat_id 80131
__> chat_id 80132
__> chat_id 80133
__> chat_id 80134
__> chat_id 80135
__> chat_id 80136
__> chat_id 80137
__> chat_id 80138
__> chat_id 80140
__> chat_id 80141
__> chat_id 80142
__> chat_id 80145
__> chat_id 80147
__> chat_id 80148
__> chat_id 80149
__> chat_id 80150
__> chat_id 80151
__> chat_id 80152
__> chat_id 80153
__> chat_id 80154
__> chat_id 80156
__> chat_id 80157
__> chat_id 80158
__> chat_id 80159
__> chat_id 80160
__> chat_id 80161
__> chat_id 80162
__> chat_id 80163
__> chat_id 80164
__> chat_id 80165
__> chat_id 80166
__> chat_id 80167
__> chat_id 80168
__> chat_id 80169
__> chat_id 80170
__> chat_id 80171
__> chat_id 80172
__> chat_id 80173
__> chat_id 80174
__> chat_id 80175
__> chat_id 80176
__> chat_id 80177
__> chat_id 80178
__> chat_id 80179
__> chat_id 80180
__> chat_id 80181
__> chat_id 80182
__> chat_id 80183
__> chat_id 80184
__> chat_id 80185
__> chat_id 80186
__> chat_id 80187
__> chat_id 80188
__> chat_id 80189
__> chat_id 80190
__> chat_id 80191
__> chat_id 80192
__> chat_id 80193
__> chat_id 80194
__> chat_id 80195
__> chat_id 80198
__> chat_id 80199
__> chat_id 80200
__> chat_id 80201
__> chat_id 80202
__> chat_id 80203
__> chat_id 80206
__> chat_id 80207
__> chat_id 80208
__> chat_id 80209
__> chat_id 80210
__> chat_id 80211
__> chat_id 80214
__> chat_id 80216
__> chat_id 80217
__> chat_id 80218
__> chat_id 80219
__> chat_id 80220
__> chat_id 80221
__> chat_id 80222
__> chat_id 80223
__> chat_id 80224
__> chat_id 80225
__> chat_id 80226
__> chat_id 80227
__> chat_id 80228
__> chat_id 80229
__> chat_id 80230
__> chat_id 80231
__> chat_id 80232
__> chat_id 80233
__> chat_id 80234
__> chat_id 80235
__> chat_id 80239
__> chat_id 80240
__> chat_id 80241
__> chat_id 80242
__> chat_id 80243
__> chat_id 80246
__> chat_id 80249
__> chat_id 80250
__> chat_id 80251
__> chat_id 80252
__> chat_id 80253
__> chat_id 80254
__> chat_id 80257
__> chat_id 80258
__> chat_id 80259
__> chat_id 80260
__> chat_id 80261
__> chat_id 80262
__> chat_id 80263
__> chat_id 80264
__> chat_id 80265
__> chat_id 80266
__> chat_id 80267
__> chat_id 80268
__> chat_id 80269
__> chat_id 80270
__> chat_id 80271
__> chat_id 80272
__> chat_id 80273
__> chat_id 80274
__> chat_id 80280
__> chat_id 80281
__> chat_id 80282
__> chat_id 80285
__> chat_id 80286
__> chat_id 80287
__> chat_id 80288
__> chat_id 80291

In [60]:
prepro_list

{'id': 1727038436,
 'community_name': 'smartboursegroup',
 'messages': [{'chat_id': 79913,
   'person_id': 107779226,
   'org_text': 'درود \nلطفا برای ثبهساز تحلیل داریو\nبخریم؟',
   'date': datetime.datetime(2023, 5, 27, 4, 33, 35, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40203,
   'text': 'درود \nلطفا برای <ثبهساز> تحلیل داریو\nبخریم ؟'},
  {'chat_id': 79916,
   'person_id': 5609613532,
   'org_text': 'کاهش زمان و هزینه انجام افزایش سرمایه\u200c با الکترونیکی شدن حق\u200cتقدم\u200cها\n\n🔹مدیر نظارت بر بازار اولیه سازمان بورس در بیست و یکمین نشست گروهی خبرنگاران بازار سرمایه با مدیران سازمان گفت: منابع حاصل از افزایش سرمایه\u200cها پس از تکمیل فرآیند مربوط، قابل استفاده برای شرکت\u200cهاست و طبیعتا تسریع فرآیند، بهینه\u200cتر و مطلوب\u200cتر است.\n\n🔹بنابراین اقداماتی که منجر به کوتاه\u200cتر شدن فرآیند افزایش سرمایه بشود به سهامداران و شرکت\u200cها کمک قابل توجهی می\u200cکند.\n\n🔹پیش\u200cبینی می\u200cشود با الکترونیکی شدن حق تقدم سهام و بهینه شدن فرآیند افزایش سرمایه\u200cها، استقبال به این موضوع بیش\u200c از پیش افزایش یابد.',
   'date': datetime.datetime(2023, 5, 27, 4, 48, 2, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40211,
   'text': 'کاهش زمان و هزینه انجام افزایش سرمایه\u200c با الکترونیکی شدن حق\u200cتقدم\u200cها\nمدیر نظارت بر بازار اولیه سازمان <بورس> در بیست و یکمین نشست گروهی خبرنگاران بازار سرمایه با مدیران سازمان گفت : منابع حاصل از افزایش سرمایه\u200cها پس از تکمیل فرآیند مربوط ، قابل استفاده برای شرکت\u200cهاست و طبیعتا تسریع فرآیند ، بهینه\u200cتر و مطلوب\u200cتر است .\n بنابراین اقداماتی که منجر به کوتاه\u200cتر شدن فرآیند افزایش سرمایه بشود به سهامداران و شرکت\u200cها کمک قابل\u200cتوجهی می\u200cکند .\n پیش\u200cبینی می\u200cشود با الکترونیکی شدن حق تقدم سهام و بهینه شدن فرآیند افزایش سرمایه\u200cها ، استقبال به این موضوع بیش\u200c از پیش افزایش یابد .'},
  {'chat_id': 79932,
   'person_id': 106533999,
   'org_text': 'حقوقی خودرو😂😂😂💩',
   'date': datetime.datetime(2023, 5, 27, 5, 36, 29, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': 'حقوقی <خودرو>'},
  {'chat_id': 79934,
   'person_id': 781812349,
   'org_text': 'وساپا کی باز میشه',
   'date': datetime.datetime(2023, 5, 27, 5, 43, 31, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': None,
   'text': '<وساپا> کی باز میشه'},
  {'chat_id': 79944,
   'person_id': 152101023,
   'org_text': 'اقا کسی تحلیلی از ختور نداره؟',
   'date': datetime.datetime(2023, 5, 27, 5, 47, 50, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': 'اقا کسی تحلیلی از <ختور> نداره ؟'},
  {'chat_id': 79946,
   'person_id': 389665592,
   'org_text': 'خمحرکه رو یکی بگیره',
   'date': datetime.datetime(2023, 5, 27, 5, 52, 53, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خمحرکه> رو یکی بگیره'},
  {'chat_id': 79947,
   'person_id': 781812349,
   'org_text': 'وساپا کی باز میشه کسی میدونه',
   'date': datetime.datetime(2023, 5, 27, 5, 52, 56, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': None,
   'text': '<وساپا> کی باز میشه کسی میدونه'},
  {'chat_id': 79949,
   'person_id': 5242220299,
   'org_text': 'خودرو و قطعات رنج قوی 👌',
   'date': datetime.datetime(2023, 5, 27, 6, 5, 37, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خودرو> و قطعات رنج قوی'},
  {'chat_id': 79951,
   'person_id': 979620973,
   'org_text': 'خگستر وخساپا بخرین اضافه کنیم نظر تون چیه',
   'date': datetime.datetime(2023, 5, 27, 6, 5, 35, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خگستر> وخساپا بخرین اضافه کنیم نظر تون چیه'},
  {'chat_id': 79952,
   'person_id': 389665592,
   'org_text': 'عجب رنجی زد حکشتی',
   'date': datetime.datetime(2023, 5, 27, 5, 56, 45, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40209,
   'text': 'عجب رنجی زد <حکشتی>'},
  {'chat_id': 79954,
   'person_id': 1928050076,
   'org_text': 'دیشب گفتم حکشتی رو از دست ندین👍👍👍👍',
   'date': datetime.datetime(2023, 5, 27, 5, 57, 14, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79855,
   'text': 'دیشب گفتم <حکشتی> رو از دست ندین'},
  {'chat_id': 79959,
   'person_id': 5242220299,
   'org_text': 'حمایت معتبر 650 ، هدف 870 رو در مرحله اول پیش رو داره',
   'date': datetime.datetime(2023, 5, 27, 6, 3, 16, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79944,
   'text': 'حمایت معتبر 650 ، هدف 870 رو در مرحله اول پیش رو داره'},
  {'chat_id': 79960,
   'person_id': 1297859702,
   'org_text': 'کسی تحلیلی در مورد پترول داره؟',
   'date': datetime.datetime(2023, 5, 27, 6, 4, 52, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40227,
   'text': 'کسی تحلیلی در مورد <پترول> داره ؟'},
  {'chat_id': 79967,
   'person_id': 693956065,
   'org_text': 'سلام روزتون بخیر من ختوقا دارم  بیست درصد سودم بنظرتون با خمحرکه جا به جا کنم یا همون ختوقا را نگه دارم ممنون میشم راهنمایی کنید🙏',
   'date': datetime.datetime(2023, 5, 27, 6, 8, 59, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79958,
   'text': 'سلام روزتون بخیر من <ختوقا> دارم بیست درصد سودم بنظرتون با <خمحرکه> جا به جا کنم یا همون <ختوقا> را نگه دارم ممنون میشم راهنمایی کنید'},
  {'chat_id': 79968,
   'person_id': 91003866,
   'org_text': '#خمحور چریکی جدید بازار\nهمیشه بالاتر از خمحرکه بود و میره که بالای خمحرکه وایسه',
   'date': datetime.datetime(2023, 5, 27, 6, 10, 16, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79950,
   'text': '<خمحور> چریکی جدید بازار\nهمیشه بالاتر از خمحرکه\u200cبود و میره که بالای <خمحرکه> وایسه'},
  {'chat_id': 79971,
   'person_id': 5242220299,
   'org_text': 'سلام روز شما هم بخیر\n\nختوقا رو نگهداری کنید',
   'date': datetime.datetime(2023, 5, 27, 6, 10, 31, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79967,
   'text': 'سلام روز شما هم بخیر\n<ختوقا> رو نگهداری کنید'},
  {'chat_id': 79972,
   'person_id': 6043183100,
   'org_text': 'شاخص بورس',
   'date': datetime.datetime(2023, 5, 27, 6, 11, 19, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40783,
   'text': 'شاخص <بورس>'},
  {'chat_id': 79973,
   'person_id': 5242220299,
   'org_text': 'کم کم باید بره بالای محدوده مقاومتی، انتظار دارم بزودی 1000 رو ببینه 👌\n\nخمحرکه هم دوسش دارم البته 😁',
   'date': datetime.datetime(2023, 5, 27, 6, 11, 20, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79968,
   'text': 'کم کم باید بره بالای محدوده مقاومتی ، انتظار دارم بزودی 1000 رو ببینه \n<خمحرکه> هم دوسش دارم البته'},
  {'chat_id': 79974,
   'person_id': 640353386,
   'org_text': 'خمحور که عالیه \nخمحرکه هم عالیه \nنوع حرکت هاشون و اهدافشون متفاوته \nبین بهتر و بهترین هستیم 👌',
   'date': datetime.datetime(2023, 5, 27, 6, 12, 8, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79968,
   'text': '<خمحور> که عالیه \n<خمحرکه> هم عالیه \nنوع حرکت هاشون و اهدافشون متفاوته \nبین بهتر و بهترین هستیم'},
  {'chat_id': 79976,
   'person_id': 693956065,
   'org_text': 'ممنون یک دنیا سپاس لطف کردید🙏',
   'date': datetime.datetime(2023, 5, 27, 6, 47, 17, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79971,
   'text': 'ممنون یک دنیا سپاس لطف کردید'},
  {'chat_id': 79977,
   'person_id': 5242220299,
   'org_text': 'خواهش میکنم سلامت باشید 🙏',
   'date': datetime.datetime(2023, 5, 27, 6, 12, 25, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79976,
   'text': 'خواهش میکنم سلامت باشید'},
  {'chat_id': 79978,
   'person_id': 6043183100,
   'org_text': 'شپنا تایم 4',
   'date': datetime.datetime(2023, 5, 27, 6, 12, 35, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40248,
   'text': '<شپنا> تایم 4'},
  {'chat_id': 79979,
   'person_id': 640353386,
   'org_text': 'خساپا ، خودرو \nو دیگر هیچ !!!',
   'date': datetime.datetime(2023, 5, 27, 6, 13, 39, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خساپا> ، <خودرو> \nو دیگر هیچ !!!'},
  {'chat_id': 79981,
   'person_id': 187468454,
   'org_text': 'ثامان😍',
   'date': datetime.datetime(2023, 5, 27, 6, 14, 9, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40203,
   'text': '<ثامان>'},
  {'chat_id': 79982,
   'person_id': 5632416119,
   'org_text': 'بعله \nشوربختانه \nیه بازار \nیه ملت \nبازیچه ی حرکت های مزخرف اینا شدن 😉',
   'date': datetime.datetime(2023, 5, 27, 6, 17, 19, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79979,
   'text': 'بعله \nشوربختانه \nیه بازار \nیه <ملت> \nبازیچه ی حرکت\u200cهای مزخرف اینا شدن'},
  {'chat_id': 79984,
   'person_id': 640353386,
   'org_text': 'یه گروه خودمون هم همینطور 😉',
   'date': datetime.datetime(2023, 5, 27, 6, 17, 25, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79982,
   'text': 'یه گروه خودمون هم همینطور'},
  {'chat_id': 79985,
   'person_id': 5632416119,
   'org_text': 'مرحبا 😉😉😉',
   'date': datetime.datetime(2023, 5, 27, 6, 17, 43, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79984,
   'text': 'مرحبا'},
  {'chat_id': 79988,
   'person_id': 5242220299,
   'org_text': 'بابا خدایی بی خیال خودرو و خساپا بشید مگه سهم قحطی شده 😅',
   'date': datetime.datetime(2023, 5, 27, 6, 18, 35, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': 'بابا خدایی بی\u200cخیال <خودرو> و <خساپا> بشید مگه سهم قحطی شده'},
  {'chat_id': 79989,
   'person_id': 5632416119,
   'org_text': 'اینهمه قطعاتی ، ناب 😉',
   'date': datetime.datetime(2023, 5, 27, 6, 19, 16, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79988,
   'text': 'اینهمه قطعاتی ، ناب'},
  {'chat_id': 79991,
   'person_id': 5242220299,
   'org_text': 'به جان خودم یکی از یکی ناب تر 😁',
   'date': datetime.datetime(2023, 5, 27, 6, 21, 2, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79989,
   'text': 'به جان خودم یکی از یکی ناب تر'},
  {'chat_id': 79992,
   'person_id': 640353386,
   'org_text': 'خساپا خیلی جالبه \nهی میزنه به کف برمیگرده بالا \nتهش هم میگن اینکارو بکنه اونکارو بکنه و بزنه و برقصه و زیگزاگ بره \nمیرسه به ۶۰۰ تومن !\n\nاصن تو خوبی 😁😉',
   'date': datetime.datetime(2023, 5, 27, 6, 20, 34, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خساپا> خیلی جالبه \nهی میزنه به کف برمیگرده بالا \nتهش هم میگن اینکارو بکنه اونکارو بکنه و بزنه و برقصه و زیگزاگ بره \nمیرسه به 600 تومن !\n اصن تو خوبی'},
  {'chat_id': 79996,
   'person_id': 106533999,
   'org_text': 'این 600 تومنی که هر روز پست شو میذارن احتمالا واسه سه چهار سال دیگه است',
   'date': datetime.datetime(2023, 5, 27, 6, 21, 42, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79992,
   'text': 'این 600 تومنی که هر روز پست شو میذارن احتمالا واسه سه چهار سال دیگه است'},
  {'chat_id': 79997,
   'person_id': 389665592,
   'org_text': 'حالا جالب اینجاست امروز پالایشی ها دارن بازار رو منفی میکنن و احتمالا بخاطر اخبار سیا  سی پیش رو هست',
   'date': datetime.datetime(2023, 5, 27, 6, 23, 6, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79979,
   'text': 'حالا جالب اینجاست امروز پالایشی\u200cها دارن بازار رو منفی میکنن و احتمالا بخاطر اخبار سیا سی پیش رو هست'},
  {'chat_id': 79998,
   'person_id': 5242220299,
   'org_text': '#خساپا',
   'date': datetime.datetime(2023, 5, 27, 7, 5, 31, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خساپا>'},
  {'chat_id': 79999,
   'person_id': 389665592,
   'org_text': 'اوخ     🥴🤕 این بد شد😂',
   'date': datetime.datetime(2023, 5, 27, 6, 22, 37, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79998,
   'text': 'اوخ این بد شد'},
  {'chat_id': 80000,
   'person_id': 106533999,
   'org_text': 'خب با این وضعیت باید بریم برا شاخص 2100 🤦\u200d♂️',
   'date': datetime.datetime(2023, 5, 27, 6, 23, 5, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79998,
   'text': 'خب با این وضعیت باید بریم برا شاخص 2100'},
  {'chat_id': 80001,
   'person_id': 640353386,
   'org_text': '۶۰۰ تومنه که میگن \nنه ها \n۶۰۰ تووومن !',
   'date': datetime.datetime(2023, 5, 27, 6, 31, 52, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79996,
   'text': '600 تومنه که میگن \nنه\u200cها \n600 تووومن !'},
  {'chat_id': 80002,
   'person_id': 5242220299,
   'org_text': 'متاسفانه 😬',
   'date': datetime.datetime(2023, 5, 27, 6, 23, 49, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79999,
   'text': 'متاسفانه'},
  {'chat_id': 80003,
   'person_id': 109862105,
   'org_text': 'به خاطر دعوای مجلس و دولت سر نرخ تسعیر ارز  شرکت\u200cهای صادرات محور هست',
   'date': datetime.datetime(2023, 5, 27, 6, 23, 50, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79997,
   'text': 'به خاطر دعوای مجلس و دولت سر نرخ تسعیر ارز شرکت\u200cهای صادرات محور هست'},
  {'chat_id': 80004,
   'person_id': 52822857,
   'org_text': 'موافقم',
   'date': datetime.datetime(2023, 5, 27, 6, 24, 23, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80000,
   'text': 'موافقم'},
  {'chat_id': 80005,
   'person_id': 5242220299,
   'org_text': '#خساپا رو 310 حمایت خوبی داره',
   'date': datetime.datetime(2023, 5, 27, 6, 24, 27, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80000,
   'text': '<خساپا> رو 310 حمایت خوبی داره'},
  {'chat_id': 80007,
   'person_id': 6043183100,
   'org_text': 'شبندر🤷\u200d♀️',
   'date': datetime.datetime(2023, 5, 27, 6, 25, 25, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40248,
   'text': '<شبندر>'},
  {'chat_id': 80010,
   'person_id': 442258252,
   'org_text': 'استاد خپارس لطفا تحلیل میکنید',
   'date': datetime.datetime(2023, 5, 27, 6, 26, 17, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': 'استاد <خپارس> لطفا تحلیل میکنید'},
  {'chat_id': 80011,
   'person_id': 80992556,
   'org_text': 'خساپا محدوده ۳۲۰ قوی هست و تا محدوده ۳۲۹ دید به خودش میشه گفت همین نقطه برگشتش هست',
   'date': datetime.datetime(2023, 5, 27, 6, 26, 31, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': '<خساپا> محدوده 320 قوی هست و تا محدوده 329 دید به خودش میشه گفت همین نقطه برگشتش هست'},
  {'chat_id': 80012,
   'person_id': 951550300,
   'org_text': 'شصت درصد زیر سقف قیمتیشه همین',
   'date': datetime.datetime(2023, 5, 27, 6, 27, 27, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80010,
   'text': 'شصت درصد زیر سقف قیمتیشه همین'},
  {'chat_id': 80014,
   'person_id': 573028109,
   'org_text': 'بله یکی خمحرکه رو بگیره که داره سقوط میکنه😂😂',
   'date': datetime.datetime(2023, 5, 27, 6, 28, 33, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79946,
   'text': 'بله یکی <خمحرکه> رو بگیره که داره سقوط میکنه'},
  {'chat_id': 80015,
   'person_id': 640353386,
   'org_text': 'نسبت قدرت خریدار به فروشنده ۲ برابر \nگرفتنش 👌',
   'date': datetime.datetime(2023, 5, 27, 6, 29, 21, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80014,
   'text': 'نسبت قدرت خریدار به فروشنده 2 برابر \nگرفتنش'},
  {'chat_id': 80016,
   'person_id': 389665592,
   'org_text': 'سقوط؟😂😂',
   'date': datetime.datetime(2023, 5, 27, 6, 29, 25, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80014,
   'text': 'سقوط ؟'},
  {'chat_id': 80019,
   'person_id': 640353386,
   'org_text': 'گیربکس سقوط نمیکنه \nسرعت میده 👌',
   'date': datetime.datetime(2023, 5, 27, 6, 30, 51, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80016,
   'text': 'گیربکس سقوط نمیکنه \nسرعت میده'},
  {'chat_id': 80024,
   'person_id': 5632416119,
   'org_text': 'ولی خوب \n\n😉',
   'date': datetime.datetime(2023, 5, 27, 6, 32, 20, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80016,
   'text': 'ولی خوب'},
  {'chat_id': 80026,
   'person_id': 742864361,
   'org_text': 'سلام\nکالا و بورس هر کدوم ۱۵ درصد تو ضررم نگه دارم یا بفروشم؟',
   'date': datetime.datetime(2023, 5, 27, 6, 33, 15, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40206,
   'text': 'سلام\n<کالا> و <بورس> هر کدوم 15 درصد تو ضررم نگه دارم یا بفروشم ؟'},
  {'chat_id': 80028,
   'person_id': 115461758,
   'org_text': 'سلام دوستان بازار بورس توی ایران واقعا مثل سیرک میمونه تمام فلزات امروز توی بازار جهانی مثبت هستن. بجز بازار بورس ایران..ولی توی بازار واقعی ایران متاثر از بازار جهانی گرونتر میفروشن چون قیمت جهانیش رفته بالا',
   'date': datetime.datetime(2023, 5, 27, 6, 34, 10, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40246,
   'text': 'سلام دوستان بازار <بورس> توی ایران واقعا مثل سیرک میمونه تمام فلزات امروز توی بازار جهانی مثبت هستن . بجز بازار <بورس> ایران .. ولی توی بازار واقعی ایران متاثر از بازار جهانی گرونتر میفروشن چون قیمت جهانیش رفته بالا'},
  {'chat_id': 80029,
   'person_id': 389665592,
   'org_text': 'خوبی عزیزم؟ قرار نشدا 😅😅😅',
   'date': datetime.datetime(2023, 5, 27, 6, 34, 51, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80024,
   'text': 'خوبی عزیزم ؟ قرار نشدا'},
  {'chat_id': 80031,
   'person_id': 5632416119,
   'org_text': 'خوبم 🥰\n\nقبوله 👌🏻',
   'date': datetime.datetime(2023, 5, 27, 6, 35, 5, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80029,
   'text': 'خوبم \nقبوله'},
  {'chat_id': 80032,
   'person_id': 742864361,
   'org_text': 'قنیشا نگه دارم یا بفروشم؟',
   'date': datetime.datetime(2023, 5, 27, 6, 36, 9, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40236,
   'text': '<قنیشا> نگه دارم یا بفروشم ؟'},
  {'chat_id': 80033,
   'person_id': 742864361,
   'org_text': 'کدما نگه دارم یا بفروشم؟',
   'date': datetime.datetime(2023, 5, 27, 6, 36, 41, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40246,
   'text': '<کدما> نگه دارم یا بفروشم ؟'},
  {'chat_id': 80034,
   'person_id': 742864361,
   'org_text': 'دامین نگه دارم یا بفروشم؟',
   'date': datetime.datetime(2023, 5, 27, 8, 0, 45, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40230,
   'text': '<دامین> نگه دارم یا بفروشم ؟'},
  {'chat_id': 80036,
   'person_id': 115461758,
   'org_text': 'دوست عزیز بازاری که با الگوریتم تنظیم بشه واقعا اظهار نظر دادن سخته',
   'date': datetime.datetime(2023, 5, 27, 6, 38, 30, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80033,
   'text': 'دوست عزیز بازاری که با الگوریتم تنظیم بشه واقعا اظهار نظر دادن سخته'},
  {'chat_id': 80038,
   'person_id': 76644056,
   'org_text': 'سلام بزرگواران نظرتون در مورد وبیمه چیه؟',
   'date': datetime.datetime(2023, 5, 27, 6, 38, 59, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40207,
   'text': 'سلام بزرگواران نظرتون در مورد <وبیمه> چیه ؟'},
  {'chat_id': 80042,
   'person_id': 1489683835,
   'org_text': 'سلام دوستان \nارادت\nدو روزه وضعیت ما فلزاتیا خوب نیست ، مراقب سهماتون باشید صبوری کنید ، این بازار بازار هیجانی نیست، هر هیجانی پشیمونی داره، من خودم فلوله رو دارم ولی به هیچ عنوان فروشنده نیستم',
   'date': datetime.datetime(2023, 5, 27, 6, 46, 53, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40246,
   'text': 'سلام دوستان \nارادت\nدو روزه وضعیت ما فلزاتیا خوب نیست ، مراقب سهماتون باشید صبوری کنید ، این بازار بازار هیجانی نیست ، هر هیجانی پشیمونی داره ، من خودم <فلوله> رو دارم ولی به هیچ عنوان فروشنده نیستم'},
  {'chat_id': 80045,
   'person_id': 640353386,
   'org_text': 'فروش حقوقی ها در خمحرکه یعنی اونا هم نمیدونن لندکروز با ۲۰۶ فرق داره 👌😉',
   'date': datetime.datetime(2023, 5, 27, 6, 48, 33, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 40302,
   'text': 'فروش حقوقی\u200cها در <خمحرکه> یعنی اونا هم نمیدونن لندکروز با 206 فرق داره'},
  {'chat_id': 80049,
   'person_id': 1489683835,
   'org_text': 'واقعا سهم بینظیریه همیشه خوب بوده',
   'date': datetime.datetime(2023, 5, 27, 6, 45, 48, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 79954,
   'text': 'واقعا سهم بینظیریه همیشه خوب بوده'},
  {'chat_id': 80051,
   'person_id': 115461758,
   'org_text': 'موافقم ..منم تقریبا سبدی از فلزات دارم..فسرب.فاسمین.فولاد. و ذوب که تو این بازار هیچ وقت فروشنده نیستم..همین هیجانات کاذب ما توی صف فروش حقوقی ها هر روز پولدارتر میکنه',
   'date': datetime.datetime(2023, 5, 27, 6, 46, 18, tzinfo=datetime.timezone.utc),
   'reply_to_message_id': 80042,
   'text': 'موافقم .. منم تقریبا سبدی از فلزات دارم .. <فسرب> . <فاسمین> . <فولاد> . و <ذوب> که تو این بازار هیچ وقت فروشنده نیستم .. همین هیجانات کاذب ما توی صف فروش حقوقی\u200cها هر روز پولدارتر میکنه'},
  {'chat_id': 80057,
   'person_id': 640353386,

In [14]:
# %%time
def preprocess_subgroup(data: object):
    data_id = str(data["id"])
    print("__> preprocess_subgroup", data["name"])
    # messages = boursgram_data["messages"]
    chat_list = []
    for mess in data["messages"]:
        txt = ""
        if "actor_id" in mess:
            continue

        date = mess["edited"] if ("edited" in mess) else mess["date"]
        date_unixtime = (
            mess["edited_unixtime"]
            if ("edited_unixtime" in mess)
            else mess["date_unixtime"]
        )

        for tx in mess["text_entities"]:
            txt += clean_text(tx["text"]).strip() + "\n"

        if compute_token_count(txt) > 500:
            continue
        is_stock_included, rep_txt = if_stock_included_replace(txt.strip())

        chat_info = {
            "person_id": mess["from_id"],
            "chat_id": mess["id"],
            "date": date,
            "date_unixtime": date_unixtime,
            "org_txt": txt,
            "reply_to_message_id": "",
            "text": rep_txt,
        }

        #     chat_info["text"]= txt

        # if (data["type"]== "public_supergroup" and mess["reply_to_message_id"] not in SUBGROUPS["id"] ) or (data["type"] != "public_supergroup" ):

        # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        if (
            ("reply_to_message_id" in mess)
            and (
                (  ## checks in public_supergroup that have subgroups,wheter the replied messaged is not replied to the subgroup ID
                    data["type"] == "public_supergroup"
                    and (data_id in SUBGROUPS)
                    and (mess["reply_to_message_id"] not in SUBGROUPS[data_id])
                )
                or (data["type"] != "public_supergroup")
            )
            and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
        ):
            chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
            #         txt_rep = replace_stock_with_id(txt.strip())
            # chat_info["text"] = txt
            chat_list.append(chat_info)
            #                 print(cht["id_list"])
            # print("looooool")
        #     is_included,txt = replace_stock_with_id(txt.strip())
        elif is_stock_included:
            # chat_info["text"] = txt
            chat_list.append(chat_info)

    return {**data, "messages": chat_list}


# print(chat_list_1)
#

In [147]:
# chat_list_2
# bours_df=pd.DataFrame(chat_list_2)
# bours_df.head()
# x="  'text': '\u200c\nواقعیت ماجرای شاسی
# بلندها و ارتباطشان با استیضاح وزیر صمت\nمنابع < PKLJ1 > تایید کردند در ابتدای تابستان 1400 یعنی تنها چند هفته بعد از انتخابات ریاس"
# clean_text(x)

### Preprocessing telegram public_channel and simplegroups

In [145]:
# chat_list_2
# pd.DataFrame(maj_list) ,pd.DataFrame(bours_df)
# pd.concat([maj_df ,bours_df]).head()
# pd.DataFrame(maj_list)
# maj_df=pd.DataFrame(maj_list)
# majcol=maj_df[['person_id', 'chat_id', 'date', 'date_unixtime', 'org_txt', 'text','reply_to_message_id']].columns
# print(majcol)
# print(list(bours_df.columns)==list(majcol))
# maj_df=maj_df[['person_id', 'chat_id']]
# print(maj_df)
# bours_df.columns==maj_df.columns
# chat_list_2[1].keys()
# len(chat_list_2)
# len(enc.encode(chat_list_2[0]["text"]))
# chat_list_2[0]
# for index, row in df.iterrows():
#     print(row['c1'], row['c2'])

In [64]:
# datafile_names =
concatenated_data = pd.DataFrame()
chats_path = "./data/chats_17may/"

for community_name , chat_list in all_chat_list.items():
# for json_file in os.listdir(chats_path):
    # file = pd.read_csv("./data/"+json_file)
    # df = pd.DataFrame()
    # with open(chats_path + json_file, encoding="utf-8") as file:
        # file = json.loads(file.read())
        # df = pd.DataFrame(chat_list["messages"])
        df = pd.DataFrame(preprocess_subgroup2(chat_list)["messages"])

        df["channel_name"] = community_name
        # df.set_index("channel_name",inplace=True)
        concatenated_data = pd.concat([concatenated_data, df])

        # if file["type"] == "public_supergroup":
        #     df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])
        # else:
        #     df = pd.DataFrame(preprocess_chanell_group(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])

concatenated_data = concatenated_data.reindex()
concatenated_data.to_csv("./data/concatenated2.csv", index=False)
concatenated_data.head()
# concatenated_data.con
# pd.to

__> preprocess_subgroup smartboursegroup
__> chat_id 79909
__> chat_id 79910
__> chat_id 79911
__> chat_id 79913
__> chat_id 79914
__> chat_id 79915
__> chat_id 79916
__> chat_id 79918
__> chat_id 79919
__> chat_id 79924
__> chat_id 79925
__> chat_id 79926
__> chat_id 79927
__> chat_id 79928
__> chat_id 79929
__> chat_id 79932
__> chat_id 79933
__> chat_id 79934
__> chat_id 79935
__> chat_id 79936
__> chat_id 79937
__> chat_id 79938
__> chat_id 79939
__> chat_id 79941
__> chat_id 79942
__> chat_id 79943
__> chat_id 79944
__> chat_id 79945
__> chat_id 79946
__> chat_id 79947
__> chat_id 79948
__> chat_id 79949
__> chat_id 79950
__> chat_id 79951
__> chat_id 79952
__> chat_id 79953
__> chat_id 79954
__> chat_id 79955
__> chat_id 79956
__> chat_id 79957
__> chat_id 79958
__> chat_id 79959
__> chat_id 79960
__> chat_id 79961
__> chat_id 79962
__> chat_id 79963
__> chat_id 79964
__> chat_id 79967
__> chat_id 79968
__> chat_id 79969
__> chat_id 79970
__> chat_id 79971
__> chat_id 79972
__> chat_id 79973
__> chat_id 79974
__> chat_id 79975
__> chat_id 79976
__> chat_id 79977
__> chat_id 79978
__> chat_id 79979
__> chat_id 79980
__> chat_id 79981
__> chat_id 79982
__> chat_id 79983
__> chat_id 79984
__> chat_id 79985
__> chat_id 79986
__> chat_id 79987
__> chat_id 79988
__> chat_id 79989
__> chat_id 79990
__> chat_id 79991
__> chat_id 79992
__> chat_id 79995
__> chat_id 79996
__> chat_id 79997
__> chat_id 79998
__> chat_id 79999
__> chat_id 80000
__> chat_id 80001
__> chat_id 80002
__> chat_id 80003
__> chat_id 80004
__> chat_id 80005
__> chat_id 80006
__> chat_id 80007
__> chat_id 80008
__> chat_id 80009
__> chat_id 80010
__> chat_id 80011
__> chat_id 80012
__> chat_id 80013
__> chat_id 80014
__> chat_id 80015
__> chat_id 80016
__> chat_id 80017
__> chat_id 80018
__> chat_id 80019
__> chat_id 80020
__> chat_id 80021
__> chat_id 80022
__> chat_id 80023
__> chat_id 80024
__> chat_id 80025
__> chat_id 80026
__> chat_id 80027
__> chat_id 80028
__> chat_id 80029
__> chat_id 80030
__> chat_id 80031
__> chat_id 80032
__> chat_id 80033
__> chat_id 80034
__> chat_id 80035
__> chat_id 80036
__> chat_id 80037
__> chat_id 80038
__> chat_id 80039
__> chat_id 80040
__> chat_id 80041
__> chat_id 80042
__> chat_id 80043
__> chat_id 80044
__> chat_id 80045
__> chat_id 80046
__> chat_id 80047
__> chat_id 80048
__> chat_id 80049
__> chat_id 80050
__> chat_id 80051
__> chat_id 80052
__> chat_id 80053
__> chat_id 80054
__> chat_id 80055
__> chat_id 80056
__> chat_id 80057
__> chat_id 80058
__> chat_id 80059
__> chat_id 80060
__> chat_id 80061
__> chat_id 80062
__> chat_id 80063
__> chat_id 80064
__> chat_id 80065
__> chat_id 80066
__> chat_id 80067
__> chat_id 80068
__> chat_id 80069
__> chat_id 80070
__> chat_id 80071
__> chat_id 80072
__> chat_id 80073
__> chat_id 80074
__> chat_id 80075
__> chat_id 80076
__> chat_id 80077
__> chat_id 80078
__> chat_id 80079
__> chat_id 80080
__> chat_id 80081
__> chat_id 80082
__> chat_id 80083
__> chat_id 80084
__> chat_id 80085
__> chat_id 80086
__> chat_id 80087
__> chat_id 80088
__> chat_id 80089
__> chat_id 80090
__> chat_id 80091
__> chat_id 80092
__> chat_id 80093
__> chat_id 80094
__> chat_id 80095
__> chat_id 80096
__> chat_id 80097
__> chat_id 80098
__> chat_id 80099
__> chat_id 80100
__> chat_id 80101
__> chat_id 80102
__> chat_id 80103
__> chat_id 80104
__> chat_id 80105
__> chat_id 80106
__> chat_id 80107
__> chat_id 80108
__> chat_id 80109
__> chat_id 80110
__> chat_id 80111
__> chat_id 80112
__> chat_id 80115
__> chat_id 80116
__> chat_id 80117
__> chat_id 80118
__> chat_id 80119
__> chat_id 80122
__> chat_id 80123
__> chat_id 80126
__> chat_id 80127
__> chat_id 80128
__> chat_id 80129
__> chat_id 80130
__> chat_id 80131
__> chat_id 80132
__> chat_id 80133
__> chat_id 80134
__> chat_id 80135
__> chat_id 80136
__> chat_id 80137
__> chat_id 80138
__> chat_id 80140
__> chat_id 80141
__> chat_id 80142
__> chat_id 80145
__> chat_id 80147
__> chat_id 80148
__> chat_id 80149
__> chat_id 80150
__> chat_id 80151
__> chat_id 80152
__> chat_id 80153
__> chat_id 80154
__> chat_id 80156
__> chat_id 80157
__> chat_id 80158
__> chat_id 80159
__> chat_id 80160
__> chat_id 80161
__> chat_id 80162
__> chat_id 80163
__> chat_id 80164
__> chat_id 80165
__> chat_id 80166
__> chat_id 80167
__> chat_id 80168
__> chat_id 80169
__> chat_id 80170
__> chat_id 80171
__> chat_id 80172
__> chat_id 80173
__> chat_id 80174
__> chat_id 80175
__> chat_id 80176
__> chat_id 80177
__> chat_id 80178
__> chat_id 80179
__> chat_id 80180
__> chat_id 80181
__> chat_id 80182
__> chat_id 80183
__> chat_id 80184
__> chat_id 80185
__> chat_id 80186
__> chat_id 80187
__> chat_id 80188
__> chat_id 80189
__> chat_id 80190
__> chat_id 80191
__> chat_id 80192
__> chat_id 80193
__> chat_id 80194
__> chat_id 80195
__> chat_id 80198
__> chat_id 80199
__> chat_id 80200
__> chat_id 80201
__> chat_id 80202
__> chat_id 80203
__> chat_id 80206
__> chat_id 80207
__> chat_id 80208
__> chat_id 80209
__> chat_id 80210
__> chat_id 80211
__> chat_id 80214
__> chat_id 80216
__> chat_id 80217
__> chat_id 80218
__> chat_id 80219
__> chat_id 80220
__> chat_id 80221
__> chat_id 80222
__> chat_id 80223
__> chat_id 80224
__> chat_id 80225
__> chat_id 80226
__> chat_id 80227
__> chat_id 80228
__> chat_id 80229
__> chat_id 80230
__> chat_id 80231
__> chat_id 80232
__> chat_id 80233
__> chat_id 80234
__> chat_id 80235
__> chat_id 80239
__> chat_id 80240
__> chat_id 80241
__> chat_id 80242
__> chat_id 80243
__> chat_id 80246
__> chat_id 80249
__> chat_id 80250
__> chat_id 80251
__> chat_id 80252
__> chat_id 80253
__> chat_id 80254
__> chat_id 80257
__> chat_id 80258
__> chat_id 80259
__> chat_id 80260
__> chat_id 80261
__> chat_id 80262
__> chat_id 80263
__> chat_id 80264
__> chat_id 80265
__> chat_id 80266
__> chat_id 80267
__> chat_id 80268
__> chat_id 80269
__> chat_id 80270
__> chat_id 80271
__> chat_id 80272
__> chat_id 80273
__> chat_id 80274
__> chat_id 80280
__> chat_id 80281
__> chat_id 80282
__> chat_id 80285
__> chat_id 80286
__> chat_id 80287
__> chat_id 80288
__> chat_id 80291

,chat_id,person_id,org_text,date,reply_to_message_id,text,channel_name
0,79913,107779226,درود \nلطفا برای ثبهساز تحلیل داریو\nبخریم؟,2023-05-27 04:33:35+00:00,40203.0,درود \nلطفا برای <ثبهساز> تحلیل داریو\nبخریم ؟,smartboursegroup
1,79916,5609613532,کاهش زمان و هزینه انجام افزایش سرمایه‌ با الکت...,2023-05-27 04:48:02+00:00,40211.0,کاهش زمان و هزینه انجام افزایش سرمایه‌ با الکت...,smartboursegroup
2,79932,106533999,حقوقی خودرو😂😂😂💩,2023-05-27 05:36:29+00:00,40302.0,حقوقی <خودرو>,smartboursegroup
3,79934,781812349,وساپا کی باز میشه,2023-05-27 05:43:31+00:00,NaN,<وساپا> کی باز میشه,smartboursegroup
4,79944,152101023,اقا کسی تحلیلی از ختور نداره؟,2023-05-27 05:47:50+00:00,40302.0,اقا کسی تحلیلی از <ختور> نداره ؟,smartboursegroup

In [9]:
# datafile_names =
concatenated_data = pd.DataFrame()
chats_path = "./data/chats_17may/"
for json_file in os.listdir(chats_path):
    # file = pd.read_csv("./data/"+json_file)
    # df = pd.DataFrame()
    with open(chats_path + json_file, encoding="utf-8") as file:
        file = json.loads(file.read())
        df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        df["channel_name"] = file["name"]
        # df.set_index("channel_name",inplace=True)
        concatenated_data = pd.concat([concatenated_data, df])

        # if file["type"] == "public_supergroup":
        #     df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])
        # else:
        #     df = pd.DataFrame(preprocess_chanell_group(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])

concatenated_data = concatenated_data.reindex()
concatenated_data.to_csv("./data/concatenated.csv", index=False)
concatenated_data.head()
# concatenated_data.con
# pd.to

__> preprocess_subgroup گلدن بورس
__> preprocess_subgroup مجید سلطانی
__> preprocess_subgroup گروه بازار
__> preprocess_subgroup بورسگرام | Boursegram

,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text,channel_name
0,channel1451535779,58838,2023-05-14T09:13:32,1684043012,🔰 خودرو محدوده 360 حمایت مهمی داره که با چند م...,,<خودرو> محدوده 360 حمایت مهمی داره که با چند م...,گلدن بورس
1,channel1451535779,58842,2023-05-14T09:16:05,1684043165,🔰\nخنصیر هم محدودهه 2000 تومان روی حمایته برمی...,,<خنصیر> هم محدودهه 2000 تومان روی حمایته برمید...,گلدن بورس
2,channel1451535779,58845,2023-05-14T09:19:36,1684043376,کدما از صف فروش به منفی 1 ✅\n,,<کدما> از صف فروش به منفی 1,گلدن بورس
3,channel1451535779,58846,2023-05-14T09:19:51,1684043391,وتوشه مثبت 2 🔥\n,,<وتوشه> مثبت 2,گلدن بورس
4,channel1451535779,58883,2023-05-14T10:13:26,1684046606,وتوشه رفت مثبت 3 ✅\n,58846,<وتوشه> رفت مثبت 3,گلدن بورس

In [11]:
# len(concatenated_data)
# # concatenated_data.
# # concatenated_data.set_index([range(1,len(concatenated_data)+1),"channel_name"])
# concatenated_data['index']=range(1,len(concatenated_data)+1)
# concatenated_data
# while
# concatenated_data.iloc[1:3]
# pd.read_csv('./data/concatenated.csv')

In [66]:
# len(concatenated_data)
# chats=concatenated_data.set_index("channel_name")

# concatenated_data = pd.read_csv("./data/concatenated2.csv")

# len(enc.encode("".join(list(chats[49:121]["text"]))))
chats = concatenated_data
chats = chats[chats["text"] != ""]


chats["embedding"] = np.nan
embed_index = chats.columns.get_loc("embedding")

/tmp/ipykernel_9584/2703243347.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chats["embedding"] = np.nan

In [199]:
# df['Row Sum'] = chats["te"].apply(row_sum, axis=1)
# len(enc.encode("".join( list(chats[49: 110]["text"]))))

# chats.iloc[0 : 48, text_index]
# embed = embedding_with_backoff(list(chats.iloc[49:210, text_index]))
# embed

In [216]:
# a=["a",1]
# a=pd.DataFrame({"a":range(10),"b":range(10)})
# a.iloc[0:5,1]=list(range(100,105))
# a
# a.loc[0:1]
# eval(str(a))
# embed["data"][1]["index"]

# len(x)x=list(str(emb["embedding"]) for emb in embed["data"])
chats.drop

,level_0,index,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text,channel_name,test
0,0,0,user956857432,361027,2023-04-15T00:38:55,1681506535,درود هموطن با نخریدن خودرو و دوری از معاملات خ...,,درود هموطن با نخریدن <IKCO1> و دوری از معاملات...,گروه هزار تحلیل,"[-0.004583475645631552, 0.000674283888656646, ..."
1,1,1,channel1247075296,361043,2023-04-15T10:04:39,1681540479,بورس کالا پیشنهاد افزایش سرمایه از دو محل سود ...,,<BORS1> <KALA1> پیشنهاد افزایش سرمایه از دو مح...,گروه هزار تحلیل,"[-0.02429431676864624, -0.014644262380897999, ..."
2,2,2,user164684213,361050,2023-04-15T11:56:44,1681547204,خودرو و خساپا به احتمال زیاد صف خرید بشند قابل...,,<IKCO1> و <SIPA1> به احتمال زیاد صف خرید بشند ...,گروه هزار تحلیل,"[-0.002862186636775732, -0.020522119477391243,..."
3,3,3,user164684213,361051,2023-04-15T11:57:46,1681547266,از فراکاب ها بورس هم وضعیت خوبی داره مدتی درجا...,,از فراکاب‌ها <BORS1> هم وضعیت خوبی داره مدتی د...,گروه هزار تحلیل,"[0.007988776080310345, -0.023250915110111237, ..."
4,4,4,user164684213,361052,2023-04-16T07:36:10,1681617970,وخارزم در حال شکستن مقاومت ، هدف بالاست. بررسی\n,,<IKHR1> در حال شکستن مقاومت ، هدف بالاست . بررسی,گروه هزار تحلیل,"[-0.021470045670866966, -0.023386044427752495,..."
5,5,5,user164684213,361053,2023-04-15T12:11:31,1681548091,بورس صف خرید قدرتمند\n,,<BORS1> صف خرید قدرتمند,گروه هزار تحلیل,"[-0.024858329445123672, -0.019742438569664955,..."
6,6,6,user164684213,361054,2023-04-15T12:18:35,1681548515,کندل های وخارزم نشان از صف خرید میدند بررسی مج...,,کندل‌های <IKHR1> نشان از صف خرید میدند بررسی مجدد,گروه هزار تحلیل,"[0.005701655056327581, -0.010902213864028454, ..."
7,7,7,user164684213,361055,2023-04-15T12:30:38,1681549238,وتجارت و وخارزم هم صف خرید فردا حوالی صف خرید ...,,<BTEJ1> و <IKHR1> هم صف خرید فردا حوالی صف خری...,گروه هزار تحلیل,"[-0.018122000619769096, 0.0011959766270592809,..."
8,8,8,user1075476350,361058,2023-04-15T13:59:53,1681554593,سلام من پول قابل توجهی تو بورس ندارم ولی این ر...,,سلام من پول قابل‌توجهی تو <BORS1> ندارم ولی ای...,گروه هزار تحلیل,"[-0.0030234032310545444, -0.021200519055128098..."
9,9,9,channel1247075296,361061,2023-04-15T18:45:04,1681571704,رکورد حقیقی‌ها در سبزترین روز بورس ۱۴۰۲\n▪️امر...,,رکورد حقیقی‌ها در سبزترین روز <BORS1> 1402\nام...,گروه هزار تحلیل,"[-0.012641439214348793, -0.017003342509269714,..."
10,10,10,user164684213,361062,2023-04-15T20:30:44,1681578044,زمزمه عرضه خودرو در بورس کالا بالا گرفت ظاهرا ...,,زمزمه عرضه <IKCO1> در <BORS1> <KALA1> بالا گرف...,گروه هزار تحلیل,"[-0.018546128645539284, -0.03651611879467964, ..."
11,11,11,user956857432,361071,2023-04-16T07:36:35,1681617995,درود هموطن قبل از هر مطلبی یک احوال پرسی از دل...,,درود هموطن قبل از هر مطلبی یک احوال پرسی از دل...,گروه هزار تحلیل,"[-0.017796175554394722, -0.011418316513299942,..."
12,12,12,channel1247075296,361080,2023-04-16T11:21:19,1681631479,برنامه افزایش سرمایه ۴۰۰ درصدی شرکت حمل و نقلی...,,برنامه افزایش سرمایه 400 درصدی شرکت حمل و نقلی...,گروه هزار تحلیل,"[-0.01553722657263279, -0.016692206263542175, ..."
13,13,13,channel1247075296,361083,2023-04-16T16:13:08,1681648988,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 12...,گروه هزار تحلیل,"[-0.023397494107484818, -0.006529929116368294,..."
14,14,14,channel1247075296,361086,2023-04-16T17:09:11,1681652351,نقشه بازار گروه خودرو و قطعات\n\n\n,,نقشه بازار گروه <IKCO1> و قطعات,گروه هزار تحلیل,"[-0.024104328826069832, -0.0037443945184350014..."
15,15,15,channel1247075296,361088,2023-04-16T17:09:16,1681652356,سید رضا فاطمی‌امین، وزیر صنعت، معدن و تجارت\n▪...,,سید رضا فاطمی‌امین ، وزیر صنعت ، معدن و تجارت\...,گروه هزار تحلیل,"[-0.0012687182752415538, -0.03085307590663433,..."
16,16,16,channel1247075296,361092,2023-04-16T15:12:34,1681645354,قیمت روز خودروهای سایپا ، ایران خودرو / 27 فرو...,,قیمت روز خودروهای سایپا ، ایران <IKCO1> / 27 ف...,گروه هزار تحلیل,"[-0.0024601223412901163, 0.008057791739702225,..."
17,17,17,user66948699,361097,2023-04-16T16:45:21,1681650921,سلام لطفا سهم دکوثر را تحلیل می فرمائید.\n,,سلام لطفا سهم <DKSR1> را تحلیل می‌فرمائید .,گروه هزار تحلیل,"[0.012000229209661484, 0.01010510791093111, -0..."
18,18,18,user78697984,361102,2023-04-16T21:20:56,1681667456,هر نماد بورسی را که می خواهیم بخریم باید قیمت ...,,هر نماد بورسی را که می‌خواهیم بخریم باید قیمت ...,گروه هزار تحلیل,"[-0.007994123734533787, -0.004053172655403614,..."
19,19,19,user39888679,361106,2023-04-17T03:56:14,1681691174,ثشاهد\n\n,,<SAHD1>,گروه هزار تحلیل,"[-0.01280839554965496, 0.016244124621152878, -..."
20,20,20,user949621278,361107,2023-04-17T05:44:32,1681697672,ددام\n\n,,<DAML1>,گروه هزار تحلیل,"[-0.028163084760308266, -0.002301992615684867,..."
21,21,21,user115241482,361108,2023-04-17T06:02:57,1681698777,سلام دوستان \n🚚🚍\nکسی وانت نیسان خواست برای جا...,,سلام دوستان \n\nکسی وانت نیسان خواست برای جا ب...,گروه هزار تحلیل,"[0.004818926099687815, 0.004698369186371565, 0..."
22,22,22,channel1247075296,361113,2023-04-17T08:32:46,1681707766,ادعای خاندوزی درباره عرضه خودرو در بورس تکذیب ...,,ادعای خاندوزی درباره عرضه <IKCO1> در <BORS1> ت...,گروه هزار تحلیل,"[-0.02639629878103733, -0.027682911604642868, ..."
23,23,23,user94813446,361116,2023-04-17T08:57:24,1681709244,پس تپکو چی؟؟؟؟\n,,پس <HPKO1> چی ؟؟؟؟,گروه هزار تحلیل,"[-0.005039392039179802, -0.0037795440293848515..."
24,24,24,channel1247075296,361117,2023-04-17T09:11:37,1681710097,تغییر‌_سهام_سهامداران_فعال\n▪️افزایش سرمایه ها...,,تغییر‌ _ سهام _ سهامداران _ فعال\nافزایش سرمای...,گروه هزار تحلیل,"[-0.022688666358590126, -0.005818566773086786,..."
25,25,25,user530267594,361125,2023-04-17T10:14:56,1681713896,قشکر\n؟؟؟\n,,<SHKR1> \n؟؟؟,گروه هزار تحلیل,"[-0.00942434836179018, -0.005405827425420284, ..."
26,26,26,user164684213,361127,2023-04-17T10:36:27,1681715187,برکت واچ\n,,<BRKT1> واچ,گروه هزار تحلیل,"[-0.022332098335027695, -0.0025152498856186867..."
27,27,27,channel1247075296,361130,2023-04-17T12:23:29,1681721609,فرابورس ایران پیشنهادی برای افزایش دامنه نوسان...,,فرابورس ایران پیشنهادی برای افزایش دامنه نوسان...,گروه هزار تحلیل,"[-0.009814648889005184, -0.010899889282882214,..."
28,28,28,channel1247075296,361131,2023-04-17T16:18:05,1681735685,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 74...,گروه هزار تحلیل,"[-0.02375209517776966, -0.0060776215977966785,..."
29,29,29,channel1247075296,361132,2023-04-17T16:18:12,1681735692,زیرمجموعه سایپا پیشنهاد افزایش سرمایه ۳۱۸ درصد...,,زیرمجموعه سایپا پیشنهاد افزایش سرمایه 318 درصد...,گروه هزار تحلیل,"[-0.013429343700408936, -0.006413913797587156,..."
30,30,30,channel1247075296,361143,2023-04-17T16:18:53,1681735733,▪️ رئیس قوه قضاییه: در نیمه دوم ۱۴۰۰ وزیر صمت ...,,رئیس قوه قضاییه : در نیمه دوم 1400 وزیر صمت خو...,گروه هزار تحلیل,"[-0.005179875064641237, -0.021517939865589142,..."
31,31,31,channel1247075296,361152,2023-04-18T08:58:37,1681795717,واریز سودهای رسوبی به بیش از ۷.۲ همت رسید\nشرک...,,واریز سودهای رسوبی به بیش از 7.2 همت رسید\nشرک...,گروه هزار تحلیل,"[0.006867371499538422, -0.017345596104860306, ..."
32,32,32,channel1247075296,361155,2023-04-18T11:18:35,1681804115,شرکت بازار پایه ای پیشنهاد افزایش سرمایه از مح...,,شرکت بازار پایه‌ای پیشنهاد افزایش سرمایه از مح...,گروه هزار تحلیل,"[-0.024819498881697655, -0.010722077451646328,..."
33,33,33,user164684213,361156,2023-04-18T10:19:41,1681800581,برکت قابل بررسی مثبت ۱\n,,<BRKT1> قابل بررسی مثبت 1,گروه هزار تحلیل,"[-0.013731795363128185, -0.011448858305811882,..."
34,34,34,channel1247075296,361157,2023-04-18T11:18:38,1681804118,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 76...,گروه هزار تحلیل,"[-0.023190779611468315, -0.008333120495080948,..."
35,35,35,channel1247075296,361162,2023-04-18T11:19:05,1681804145,طرح استیضاح وزیر اقتصاد در مجلس به دلیل کاهش ا...,,طرح استیضاح وزیر اقتصاد در مجلس به دلیل کاهش ا...,گروه هزار تحلیل,"[-0.02361893653869629, -0.013208662159740925, ..."
36,36,36,user173580999,361166,2023-04-18T11:08:46,1681803526,تکنو\nبرا خرید زیر نظر داشته باشید\n,,<TKNO1>\nبرا خرید زیر نظر داشته باشید,گروه هزار تحلیل,"[-0.005202749278396368, -0.010651979595422745,..."
37,37,37,channel1247075296,361171,2023-04-18T12:49:22,1681809562,سخنگوی دولت تغییر «وزیر صمت» را تکذیب کرد\nبها...,,سخنگوی دولت تغییر « وزیر صمت » را تکذیب کرد\nب...,گروه هزار تحلیل,"[-0.010925063863396645, -0.0028354742098599672..."
38,38,38,channel1247075296,361177,2023-04-18T21:31:37,1681840897,ارزش معاملات خرد بورس تهران\n,,ارزش معاملات خرد <BORS1> تهران,گروه هزار تحلیل,"[-0.028870387002825737, -0.016243016347289085,..."
39,39,39,channel1247075296,361179,2023-04-18T21:31:48,1681840908,کلیات بازار، میزان تغییرات ارزش معاملات و شاخص...,,کلیات بازار ، میزان تغییرات ارزش معاملات و شاخ...,گروه هزار تحلیل,"[-0.020335884764790535, -0.014576698653399944,..."
40,40,40,channel1247075296,361180,2023-04-18T15:13:22,1681818202,تسنیم مدعی شد: کاهش ۴۰ تا ۹۰ میلیونی قیمت خودر...,,تسنیم مدعی شد : کاهش 40 تا 90 میلیونی قیمت <IK...,گروه هزار تحلیل,"[-0.004634585231542587, -0.011370977386832237,..."
41,41,41,channel1247075296,361181,2023-04-18T16:12:46,1681821766,🔴\nنامه فوری وزیر اقتصاد به رئیس‌جمهور\n🔹وزیر ...,,نامه فوری وزیر اقتصاد به رئیس‌جمهور\nوزیر اقتص...,گروه هزار تحلیل,"[-0.006698148790746927, -0.016520066186785698,..."
42,42,42,channel1247075296,361183,2023-04-18T17:34:53,1681826693,جزئیات واردات خودرو کارکرده اعلام شد\nامید قال...,,جزئیات واردات <IKCO1> کارکرده اعلام شد\n<OMID1...,گروه هزار تحلیل,"[-0.01281424518674612, -0.009902848862111568, ..."
43,43,43,channel1247075296,361184,2023-04-18T16:04:23,1681821263,بازار خودرو از سمت عرضه امسال به نقطه اشباع می...,,بازار <IKCO1> از سمت عرضه امسال به نقطه اشباع ...,گروه هزار تحلیل,"[-0.008684953674674034, -0.024459663778543472,..."
44,44,44,user973888342,361191,2023-04-18T23:02:35,1681846355,خدا لعنتشون کنه تاریخ تحویل خودرو(سورن دوگانه)...,,خدا لعنتشون کنه تاریخ تحویل <IKCO1> ( سورن دوگ...,گروه هزار تحلیل,"[-0.009455729275941849, -0.03202660754323006, ..."
45,45,45,user69564333,361198,2023-04-19T07:13:05,1681875785,سیل فروش حواله های خودرو هست که از امروز توی ج...,,سیل فروش حواله‌های <IKCO1> هست که از امروز توی...,گروه هزار تحلیل,"[-0.011131891049444675, -0.011297151446342468,..."
46,46,46,channel1247075296,361206,2023-04-19T18:11:37,1681915297,زمان پرداخت سود سهام عدالت هم مانند شرکت ها به...,,زمان <PRKT1> سود سهام عدالت هم مانند شرکت‌ها ب...,گروه هزار تحلیل,"[-0.009995631873607635, -0.02094900980591774, ..."
47,47,47,user173580999,361210,2023-04-19T10:35:01,1681887901,بورس هم چند روز قبل گفتم بخرین\nدو روزه صف خری...,,<BORS1> هم چند روز قبل گفتم بخرین\nدو روزه صف ...,گروه هزار تحلیل,"[-0.01913473941385746, 0.00040884778718464077,..."
48,48,48,channel1247075296,361211,2023-04-19T10:45:55,1681888555,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 72...,گروه هزار تحلیل,"[-0.02071465738117695, -0.0024163706693798304,..."
49,49,49,channel1247075296,361221,2023-04-19T12:45:02,1681895702,برنامه دولت برای اخذ مالیات از معاملات مکرر مس...,,برنامه دولت برای اخذ مالیات از معاملات مکرر مس...,گروه هزار تحلیل,"[-0.007500726729631424, -0.006628000643104315,..."
50,50,50,channel1247075296,361223,2023-04-19T12:50:29,1681896029,لایحه دوفوریتی واردات خودروهای کارکرده تصویب و...,,لایحه دوفوریتی واردات خودروهای کارکرده تصویب و...,گروه هزار تحلیل,"[-0.012289070524275303, -0.008199586533010006,..."
51,51,51,user453967023,361234,2023-04-20T20:02:11,1682008331,سلام\nساعت بورس از ۲/۱۶ میخاد تغییر کنه؟\n,,سلام\nساعت <BORS1> از 2 / 16 میخاد تغییر کنه ؟,گروه هزار تحلیل,"[-0.01254215370863676, -0.013465826399624348, ..."
52,52,52,user6195229393,361235,2023-04-20T21:13:26,1682012606,سلام. وقت بخیر. نظرتون در مورد چکارن؟ در منفی ...,,سلام . وقت بخیر . نظرتون در مورد <KRTI1> ؟ در ...,گروه هزار تحلیل,"[0.003243245417252183, -0.012074056081473827, ..."
53,53,53,user164684213,361236,2023-04-20T21:21:00,1682013060,بجاش چکاپا بگیر بررسی کن\n,,بجاش <KAPA1> بگیر بررسی کن,گروه هزار تحلیل,"[-0.0007934776367619634, -0.004565797280520201..."
54,54,54,user367978778,361239,2023-04-20T22:04:01,1682015641,تحلیلی از شبندر بزارید\n,,تحلیلی از <PNBA1> بزارید,گروه هزار تحلیل,"[-0.02228635735809803, -0.017445126548409462, ..."
55,55,55,user299743843,361240,2023-04-20T22:05:39,1682015739,شپدیس نظرتون چیه؟\n,,<PRDZ1> نظرتون چیه ؟,گروه هزار تحلیل,"[0.008631128817796707, -0.02028447389602661, 0..."
56,56,56,user164684213,361241,2023-04-20T22:30:36,1682017236,دوشنبه اول وقت سهم نگیر بازار رو نگاه اگه صعود...,,دوشنبه اول وقت سهم نگیر بازار رو نگاه اگه صعود...,گروه هزار تحلیل,"[-0.0006194617017172277, -0.013105801306664944..."
57,57,57,user161839085,361242,2023-04-21T08:22:33,1682052753,کساپا یا گدنا\n,,<SISH1> یا گدنا,گروه هزار تحلیل,"[-0.012202493846416473, -0.007332440000027418,..."
58,58,58,user107620713,361243,2023-04-21T09:55:51,1682058351,فرآور\n\n,,<FRVR1>,گروه هزار تحلیل,"[-0.013149932958185673, -0.012004321441054344,..."
59,59,59,user122377350,361246,2023-04-21T17:42:26,1682086346,شبندر کسی تحلیل داره\n,,<PNBA1> کسی تحلیل داره,گروه هزار تحلیل,"[-0.00998157262802124, -0.02140861749649048, 0..."
60,60,60,channel1247075296,361249,2023-04-21T21:58:36,1682101716,کت تن کیه ؟!\nتوییت افشاگرایانه رییس اتاق بازر...,,کت تن کیه ؟!\n توییت افشاگرایانه رییس اتاق باز...,گروه هزار تحلیل,"[-0.011301090940833092, -0.014305348508059978,..."
61,61,61,user799325239,361254,2023-04-23T09:38:19,1682230099,سلام وقت بخیر\nیه سوال داشتم اگه امکانش بود ج...,,سلام وقت بخیر\nیه سوال داشتم اگه امکانش‌بود جو...,گروه هزار تحلیل,"[-0.005214995238929987, 0.005817617289721966, ..."
62,62,62,user216841847,361256,2023-04-23T12:30:20,1682240420,پس از ریزش های سال 99 بازار بورس ایران و سیل ا...,,پس از ریزش‌های سال 99 بازار <BORS1> ایران و سی...,گروه هزار تحلیل,"[-0.02115100435912609, -0.017931794747710228, ..."
63,63,63,user216841847,361257,2023-04-23T12:31:07,1682240467,نسبت P/S از دو واژه Price به معنای قیمت و Sale...,,نسبت P / S از دو واژه Price به معنای قیمت و Sa...,گروه هزار تحلیل,"[-0.009756434708833694, -0.006443175952881575,..."
64,64,64,user6195229393,361261,2023-04-23T21:30:17,1682272817,سلام. وقت بخیر. میدکو را برای خرید فردا چطور م...,,سلام . وقت بخیر . <MDKO1> را برای خرید فردا چط...,گروه هزار تحلیل,"[0.003633804153650999, 0.01113294716924429, -0..."
65,65,65,user956857432,361263,2023-04-24T00:16:17,1682282777,درود به همه هموطن اتحاد شما در برابر خودرو ساز...,,درود به همه هموطن اتحاد شما در برابر <IKCO1> س...,گروه هزار تحلیل,"[-0.009424790740013123, -0.01618131436407566, ..."
66,66,66,channel1247075296,361278,2023-04-24T11:47:01,1682324221,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 94...,گروه هزار تحلیل,"[-0.02020762301981449, -0.00943837221711874, -..."
67,67,67,channel1247075296,361279,2023-04-24T11:47:06,1682324226,رشد ۴۱ درصدی محصولات سایپا در فروردین با تولید...,,رشد 41 درصدی محصولات سایپا در فروردین با تولید...,گروه هزار تحلیل,"[-0.009068685583770275, -0.010694204829633236,..."
68,68,68,channel1247075296,361280,2023-04-24T11:47:15,1682324235,حجم مبنا ۲۷ نماد فرابورسی از سه شنبه حذف می شو...,,حجم مبنا 27 نماد فرابورسی از سه شنبه حذف می‌شو...,گروه هزار تحلیل,"[-0.01943681389093399, -0.001369088189676404, ..."
69,69,69,user54013653,361284,2023-04-24T12:08:58,1682325538,تا بازار بورس دوطرفه نشود ریسک بالایی خواهد دا...,,تا بازار <BORS1> دوطرفه نشود ریسک بالایی خواهد...,گروه هزار تحلیل,"[-0.0188043974339962, -0.024930475279688835, -..."
70,70,70,user84698370,361285,2023-04-24T12:16:01,1682325961,🔻مخالفت نمایندگان مجلس با استیضاح فاطمی امین\n...,,مخالفت نمایندگان مجلس با استیضاح فاطمی <TSAN1>...,گروه هزار تحلیل,"[0.0005962142022326589, -0.0150330550968647, -..."
71,71,71,user367978778,361288,2023-04-24T12:49:57,1682327997,شبندر رو تحلیل کنید\n,,<PNBA1> رو تحلیل کنید,گروه هزار تحلیل,"[0.004434048663824797, -0.011579276993870735, ..."
72,72,72,user956857432,361289,2023-04-24T13:11:15,1682329275,درود بهتر نبود وزارت و مجلس اول عملکرد مثبت را...,,درود بهتر نبود وزارت و مجلس اول عمل‌کرد مثبت ر...,گروه هزار تحلیل,"[0.008305607363581657, -0.011833084747195244, ..."
73,73,73,user69564333,361295,2023-04-24T20:15:28,1682354728,شاخص_کل_بورس\nبعد از اصلاح شدیدی که شاخص کل بو...,,شاخص _ کل _ <BORS1>\nبعد از اصلاح شدیدی که شاخ...,گروه هزار تحلیل,"[-0.01935340091586113, -0.013764213770627975, ..."
74,74,74,channel1247075296,361299,2023-04-25T08:51:45,1682400105,قیمت شکر تنظیم بازار و قند شکسته بسته بندی: ۲۱...,,قیمت شکر تنظیم بازار و قند شکسته بسته‌بندی : 2...,گروه هزار تحلیل,"[-0.013384942896664143, -0.00734466128051281, ..."
75,75,75,channel1247075296,361306,2023-04-25T10:16:37,1682405197,شرکت بورسی چهار قرارداد برای تولید و فروش بطری...,,شرکت بورسی چهار قرارداد برای تولید و فروش بطری...,گروه هزار تحلیل,"[-0.014569593593478203, -0.018917517736554146,..."
76,76,76,channel1247075296,361311,2023-04-25T10:50:00,1682407200,نقشه بازار گروه خودرو و قطعات\n\n\n,,نقشه بازار گروه <IKCO1> و قطعات,گروه هزار تحلیل,"[-0.024104328826069832, -0.0037443945184350014..."
77,77,0,user1012889741,751441,2023-05-13T00:35:18,1683925518,✨\nاتاق های ۳گانه مارکت انس\n(یک طرفه)\nتوتال ...,,اتاق‌های 3گانه مارکت انس \n( یک‌طرفه )\n توتال...,گروه بازار,"[-0.03224995359778404, 0.005043300334364176, 0..."
78,78,1,user170865604,751447,2023-05-13T10:00:13,1683959413,نیمه دوم بازار یرمیگرده مفت فروشی نگنید سهام ب...,,نیمه دوم بازار یرمیگرده مفت فروشی نگنید سهام ب...,گروه بازار,"[-0.03249457851052284, 0.004674057941883802, -..."
79,79,2,user170865604,751458,2023-05-13T11:55:50,1683966350,کترام صف فروشش جمع شد\n,,<TKSM1> صف فروشش جمع شد,گروه بازار,"[-0.015325411222875118, -0.011085336096584797,..."
80,80,3,user296014733,751462,2023-05-13T13:18:58,1683971338,فقط شیشه ای ها میرن سمت بورس ایران\n,,فقط شیشه‌ای ها میرن سمت <BORS1> ایران,گروه بازار,"[-0.01840779185295105, -0.02053125761449337, -..."
81,81,4,user296014733,751467,2023-05-13T14:38:43,1683976123,خدا شفا بده\n,,خدا <SHFA1> بده,گروه بازار,"[-0.01510512176901102, -0.01280129048973322, -..."
82,82,5,user170865604,751476,2023-05-13T20:47:21,1683998241,فوری؛\n🔺دو مصوبه مهم سازمان بورس برای حمایت از...,,فوری ؛\n دو مصوبه مهم سازمان <BORS1> برای حمای...,گروه بازار,"[-0.027391018345952034, -0.015341119840741158,..."
83,83,6,user170865604,751480,2023-05-14T00:22:50,1684011170,دستور حمایت وزیر اقتصاد از بازار سرمایه از جده...,,دستور حمایت وزیر اقتصاد از بازار سرمایه از جده...,گروه بازار,"[-0.01905154436826706, -0.00909802969545126, -..."
84,84,7,user170865604,751493,2023-05-14T10:40:05,1684048205,فلامی سهم انحصاری در تولید ژیلت و تیغ با سود د...,,<LAMI1> سهم انحصاری در تولید ژیلت و تیغ با سود...,گروه بازار,"[-0.014380701817572117, 0.007197146769613028, ..."
85,85,8,user395390942,751505,2023-05-14T14:49:05,1684063145,🔴 وزارت صمت: اطلاعات همۀ خریداران خودرو از سام...,,وزارت صمت : اطلاعات همه خریداران <IKCO1> از سا...,گروه بازار,"[-0.011748508550226688, -0.0011331302812322974..."
86,86,0,user117414063,71138,2023-05-14T08:59:38,1684042178,منم تازه چند روز وارد شستا شدم منتظرم پایینتر ...,,منم تازه چند روز وارد <TAMN1> شدم منتظرم پایین...,بورسگرام | Boursegram,"[-0.01531848032027483, -0.017790475860238075, ..."
87,87,1,user732850104,71151,2023-05-14T09:23:01,1684043581,یه نوسان‌گیری عالی از سهمهایی که گفته بودم\nخگ...,,یه نوسان‌گیری عالی از سهمهایی که گفته بودم\n<G...,بورسگرام | Boursegram,"[-0.022676806896924973, -0.00568633945658803, ..."
88,88,2,user106533999,71156,2023-05-14T09:20:46,1684043446,خبری شد دوباره دارن خساپا رو صف فروش میکنن؟\n,,خبری شد دوباره دارن <SIPA1> رو صف فروش میکنن ؟,بورسگرام | Boursegram,"[0.004924655891954899, -0.009460699744522572, ..."
89,89,3,user5632416119,71157,2023-05-14T09:21:19,1684043479,چرا من اسمتو نمیفهمم\nولی خیلی با حالی 🤚🏻🤚🏻🤚🏻☺️\n,71151,چرا من اسمتو نمیفهمم\nولی خیلی با حالی,بورسگرام | Boursegram,"[-0.02513243816792965, 0.0002731010608840734, ..."
90,90,5,user732850104,71160,2023-05-14T09:23:05,1684043585,بازیشونه\n,71156,بازیشونه,بورسگرام | Boursegram,"[-0.033924125134944916, -0.011035558767616749,..."

In [10]:
# type(embed["data"][0])
# embed["data"][0]["embedding"]
# # chats[]
# chats.iloc[0, text_index]=embed["data"][0]


@retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(7))
def embedding_with_backoff(input_data: list):
    # input_data.
    return openai.Embedding.create(model="text-embedding-ada-002", input=input_data)

In [8]:
def get_embedding(chats:pd.DataFrame):
    i = 0
    token_count = 0
    prev_index = 0
    chats_limit_bound = []
    chats = chats[chats["text"] != ""]
    chats["embedding"] = np.nan
    embed_index = chats.columns.get_loc("embedding")
    chats.reset_index(inplace=True, drop=True)
    data_len = len(chats)
    text_index = chats.columns.get_loc("text")
    while i < data_len:
        chat = chats.iloc[i]
        print(chat["text"])
        chat_tokens_count = compute_token_count(chat["text"])
        # print(i,chat_tokens_count,token_count,token_count + chat_tokens_count > 4096,i + 1 == len(chanell),)
        if token_count + chat_tokens_count > 8192:
            # slice_embed=chats.iloc[(prev_index) : i , text_index]
            # chats.iloc[(0 if i == 0 else i + 1) : i, embed_index] = embedding_with_backoff(
            #     slice_embed
            # )
            prev_index = 0 if prev_index == 0 else prev_index + 1

            print("s1")
            print(f"i: {i}, prev_index: {prev_index}")
            slice_embed = list(chats.iloc[prev_index:i, text_index])
            embeddings = embedding_with_backoff(slice_embed)
            embed_str_list = [str(embed["embedding"]) for embed in embeddings["data"]]
            chats.iloc[prev_index:i, embed_index] = embed_str_list
            print("s2")
            # chats_limit_bound.append(i - 1)
            prev_index = i - 1
            token_count = 0
        elif i + 1 == data_len:
            prev_index = 0 if prev_index == 0 else prev_index + 1
            print("f1")
            print(f"i: {i}, prev_index: {prev_index}")
            slice_embed = list(chats.iloc[prev_index : i + 1, text_index])
            embeddings = embedding_with_backoff(slice_embed)
            embed_str_list = [str(embed["embedding"]) for embed in embeddings["data"]]
            chats.iloc[prev_index : i + 1, embed_index] = embed_str_list
            print("f2")
            # chats.iloc[prev_index : i + 1, embed_index] = embedding_with_backoff(slice_embed)
            # chats_limit_bound.append(i)
            prev_index = i
            token_count = 0
            i += 1
        else:
            token_count += chat_tokens_count
            i += 1
    return chats
# print(chats_limit_bound)

### Create Model

In [20]:
with open('data/labeld_dataset.json', encoding='utf-8') as file:
    dataset = json.loads(file.read())
    df=pd.DataFrame(dataset)
dataset=get_embedding(df)

/tmp/ipykernel_20633/1904250906.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chats["embedding"] = np.nan

<خودرو> محدوده 360 حمایت مهمی داره که با چند محدوده دیگه همپوشانی ایجاد کرده
 از طرفی نگاه بازار هم به همین گروهه میتونید برداریم
<خنصیر> هم محدودهه 2000 تومان روی حمایته برمیداریم
<کدما> از صف فروش به منفی 1
<وتوشه> مثبت 2
<وتوشه> رفت مثبت 3
<ولکار> مثبت 3
<تمحرکه>
ورود حوالی 800 تومان با حد ضرر 5 درصدی
<ولکار> مثبت 1.5
از منفی 2 تا مثبت 4 <همراه> با قچار
نوش جون اعضایی که با ما وارد شدن
چ میکنه <تمحرکه>
عضویت 3 ماهه در کانال vip به صورت نیم بها
ارائه سیگنال‌های شارپی <بورس> ایران و ارزدیجیتال
سبدگردانی واصلاح سبد بورسی
ارائه پکیج‌های آموزشی نوسانگیری روزانه
این کانال در حال حاضر
یک _ سهم
جهت معرفی دارد که می‌تواند یک بازدهی 100 الی200 درصدی را برایتان به ارمغان بیاورد
البته دیتای کامل این
سهم
به <همراه> اخبار و شنیده‌ها در اختیارتان قرار خواهد گرفت .
 جهت شرایط دریافت این دیتاها به ادمین کانال
مراجعه کنید .
 لینک کانال فقط بدلیل متضررشدن سهامداران طی مدت اخیر
رایگان
شد
<کهمدا>
هم مثل بقیه سهام ما روی حمایت روزانه است .
تریدرهای آماتور فکر می‌کنند که <بورس> وسیله سرگرمیه و 24 ساعته باید در بازار باشند و معامله کنند !
<تپکو>
اخبار بسیار خوبی از این سهم به گوش می‌رسه و اگر این اخبار درست باشه سهم پرواز بلندی خواهد داشت .
<رانفور>
برای مجمع بسته است .
<کروی>
فراموش نکنید بزودی یک افزایش سرمایه از اندوخته داره و سهام جایزه مجانی خواهد داد . افزایش سرمایه هم تایید‌شده‌.
 بنیاد سهم عالی
تکنیکال عالی
مسابقه اینستاگرامی پیج کارگزاری تمدن

<همراه> شو ، جایزه ببر !
 برای شرکت در قرعه کشی 3 جایزه 10 میلیونی کافیست تا روی لینک زیر بزنید و وارد صفحه اینستاگرام کارگزاری تمدن شوید .
 1 پیج ما را فالو کنید
.
 2پاسخ صحیح را در کامنت درج کنید .
 لینک پست مسابقه :
هیچ حبابی در <بورس> دیده نمی‌شود / تمام فعالان بازار در حمایت از سهم‌هایشان اجماع داشته باشند
عظیم ثابت گفت : ارزش دلاری سهم‌ها اکنون قابل مقایسه با سال 1399 نیست ، براساس بررسی‌های صورت گرفته در حال حاضر ارزش روز برخی شرکت‌ها از ارزش ذاتی سهم‌هایشان پایین‌تر است .
 اکنون P / E فوروارد بازار در محدوده قابل قبولی قرار دارد و هیچ حبابی بر خلاف سایر بازارهای موازی در بازار سرمایه دیده نمی‌شود .
 تمام ارکان بازار سرمایه می‌بایست یک اجماع کلی در راستای حمایت از سهم‌هایشان داشته باشند زیرا طی چند روز اخیر قیمت بسیاری از سهم‌ها کاهش یافته و اکنون به سبب ارزندگی سهم‌ها زمان مناسبی برای سرمایه‌گذاری در راستای کسب بازدهی است / شبکه <بورس>
<تکمبا>
از همون جایی که تحلیل می‌گفت مورد حمایت قرار گرفت .
<غچین>
دقیقا از روی حمایت با یک کندل سبز بلند برگشت .
<کهمدا>
هم دقیقا از حمایت برگشت و به صف خرید نشست
<شنفت>
هم مطابق تحلیل قبلی دقیقا از سقف کانال پولبک را تمام کرد و به صف خرید نشست
<کروی>
هم از کف کانال صعودی برگشت بالا
<تپکو>
در این سهم داره یک اتفاق بزرگ می‌افته و اون چیزی نیست جز خروج سهم از کانال بلند مدت نزولی در تایم هفتگی
با توجه به این اتفاق و اخباری که از سهم به گوش میرسه بنده سهم را به افراد جسوری که تمایل به ریسک کردن دارند پیشنهاد دادم امروز .
 جالب این‌بود که صف فروش سهم در دقایق پایانی بازار یهو با حجم خرید سنگین جمع شد .
<ختور>
این سهم در تمام هفته‌ای که بازار ریخت صف فروشش مرتب جمع می‌شد و صرفا بخاطر جو خودرویی‌ها درجا می‌زد . با کمی تابلو خوانی به وضوح مشخص‌بود که با اولین لبخند سبز بازار قفل صف خرید خواهد شد .
بازار چهارشنبه هم احتمالا با نوسانات محدودی <همراه> خواهد‌بود . و باید منتظر هفته بعد باشیم .
<ختور>
رتبه نخست صادرات در گروه خودروسازی سایپا را کسب کرد
سلام وقت بخیر
بعد از گذشت یک و سال و نیم از ایجاد گروه خوشحالم که در این مدت توانستیم با تحلیل تقریبا موفق سهام در سال 1400 به حدود 60درصد سود و در سال 1401 به 100 درصد سود برسیم و برای سال 1402 هم با تکمیل نجربیات و لحاظ کردن تحلیل بنیادی و بررسی شرکتها پیش بینی
سود بیش از 100 درصدی
را داریم .
 <بورس> را همچنان بهترین گزینه سرمایه‌گذاری و حتی شغلی و رسیدن به امنیت مالی و حتی بازنشستگی پرسود در این بازار میدانم و با انتخاب سهام خوب روندی کم ریسک و بدون استرس را دنبال می‌کنم ، اما در کنار آن تحلیل و توصیه‌های
سرمایه‌گذاری در طلا و سکه و نقره و مسکن
هم برای شما بیان خواهد شد .
 با ما باشید در گروه به آدرس :
 ایتا
تلگرام
آغاز واگذاری سهام به فرهنگیان از 31 اردیبهشت
مدیرعامل صندوق ذخیره فرهنگیان :
 واگذاری سهام در روز ولادت حضرت معصومه ( س )، 31 اردیبهشت ماه خواهد‌بود و اطلاع‌رسانی لازم به فرهنگیان درباره جزئیات سهام دریافتی انجام می‌شود .
 تاکنون بیش از دو سوم اعضا کدبورسی دریافت کرده‌اند . برای آن‌ها که کدبورسی ندارند از سوی سازمان <بورس> مهلتی تعیین‌شده‌تا سهام آن‌ها ذخیره و بعد از دریافت کد بورسی تخصیص یابد ./ ایسنا
<رانفور>
بعد از مجمع و تقسیم سود ، در حال گشایش است . این سهم تکنیکال و فاندامنتال عالی در این قیمتها داره
این بازار سرشار از حماقته !
 سهمی که پارسال <ملت> در صف فروش به قیمت 500 تومان التماس فروش داشتند امروز 260 تومان سود ساخته !
 یعنی بازار می‌تونه اینقدر خر باشه ؟
 بله ، حتی بیشتر
در کوتاه مدت بازار هر خریتی می‌کنه
اما در بلند مدت هیچ چیزی منطقی تر از رفتار بازار نیست .
بوی مذاکره به مشام میرسه بانکی <وبملت> <وتجارت> بررسس شود
حال کردید <وتجارت> ووبملت را
اتاق‌های 3گانه مارکت انس
( یک‌طرفه )
 توتال مارکت و توتال پلاس
( بروکری )
5سال سابقه فعالیت درخشان

کمترین
کمیسیون ( 2هزارتومن & 5 سنت ) اسپرد ( 10 & 12سنت )
 امکان
برداشت وجه با فاکتورباز
درتوتال پلاس
دارای
بونوس
های
حمایتی
برای متضررین ( هر3اتاق ) و دارای اتاق دمو <همراه> با جوایز
20تا 30 درصد
شارژ بیشتر
به صورت بونوس در اولین واریز مارکت انس
امکان ثبت نام
بدون احراز هویت
درصورت واریز و برداشت تتری
 دربرگیرنده تمام سلایق مارجین
به دلار و ریال
جهت اطلاعات بیشتر ومطالعه جزئیات ربات ثبت نام را استارت بزنید .
<بورس> در حال نابودیه
اتاق‌های 3گانه مارکت انس
( یک‌طرفه )
 توتال مارکت و توتال پلاس
( بروکری )
5سال سابقه فعالیت درخشان

کمترین
کمیسیون ( 2هزارتومن & 5 سنت ) اسپرد ( 10 & 12سنت )
 امکان
برداشت وجه با فاکتورباز
درتوتال پلاس
دارای
بونوس
های
حمایتی
برای متضررین ( هر3اتاق ) و دارای اتاق دمو <همراه> با جوایز
20تا 30 درصد
شارژ بیشتر
به صورت بونوس در اولین واریز مارکت انس
امکان ثبت نام
بدون احراز هویت
درصورت واریز و برداشت تتری
 دربرگیرنده تمام سلایق مارجین
به دلار و ریال
جهت اطلاعات بیشتر ومطالعه جزئیات ربات ثبت نام را استارت بزنید .
<وبملت>
در روند صعودی حاضر و در داخل کانال صعودی بلندمدت بعد از شکست سقف تعدیل‌شده‌قبلی ، در حال حرکت به سمت اهداف بالاتر است
نکته کلیدی :
 با حفظ محدوده حمایتی 380 ، هدف فعلی را می‌توان در محدوده 610 تومان دانست که با عبور از آن می‌تواند به به اهداف بالاتر در محدوده 1400 تومان حرکت کند در مجموع توان عبور از 610 تومان را دارد
<بورس> آخرش نابودی سرمایه است
<کترام> 1700 رد کنه رفته برای اهداف بالا منبع خبر کانال پرویز خان خالقی دوستان لطفا نظر بدید تکنیکالی من بهش امیدوارم مثل <کلوند> میشه
راستش بنظرم الان باید یه مقدار کلی تر به ماهیت خود <بورس> نگاه کرد نه فقط سهم !!
 قطعا توی موقعیت خوبی هست این سهم ،، تکنیکالی و بنیادی !
 اما باید دید پارامترهای دیگه هم اجازه میده بازار روال عادیشو طی کنه !!!
 ورود پول خاصی نداریم فعلا ،،، ارزش معاملات هم نسبت به دوزهای سبز پایین هنوز !
 هنوز ترس و نگرانی وجود داره !! و از همه مهمتر بحث بازارساز هستش که نظرش همچنان روی اصلاح فرسایشی هستش یا قرار از همینجا برگرده دوباره !!!
 بنظرم قیمت دلار و ارزش معاملات خیلی میتونه راه گشا باشه الان !!
 ارزش معاملات اگه برگرده بالای 20 همت قطعا اوضاع خیلی فرق میکنه که فعلا خبری‌نشده‌!
 امیدوارم همه موفق باشیم .
صف خرید <وبملت> ووتجارت مبارک سهامداران <کترام> <دلقما> <فلامی> بررسی شود اهداف بالایی دارن
مهندس وتحارت ووبملت صف خرید شدن لطفا <دلقما> <فلامی> سیگنال بده حال ما عوض بشه
ثبت نام <خودرو> هم تموم میشه ( ورود پول به بازار طلا و دلار )
سهم رشد نکرده‌ها را فقط برسی کنید مثل ثرووود که خودمون در حمایت معتبر 1400تا 1450خریدامونا تکمیل کردیم فول سهم شدیم بازیگران شناوری سهم را بین 1500تا 2000دارن <جم> می‌کنند بد بزنن زیرش
وسین
وسرمد
<دانا>
<سبهان> عالیه
بررسی کنید
واقعا جامانده
صد در صد با سقف قبلیش فاصله داره
ای پی اس عالیه
شناوری پایین
پی به‌ای بعد از مجمع که هفته آینده هست میاد پایین تر و جذاب تر میشه
<پترول> کف قیمت وضرر
یعنی چی ؟ اخه من هم <پترول> دارم . نگه داشتنش ضرره ؟
سللام خوش آمدید
لطفا مطالب ، اخبار و تحلیلهای هر " سهم " یا " موضوع " را در تاپیک مربوط به خودش ارسال نمایید
مثلا مطالب مرتبط با " <خساپا> " را در تاپیک " <خودرو> و ساخت قطعات " ارسال بفرمایید
 پستهای غیرمرتبط با هماهنگی و پیشنهادات از این تاپیک حذف میشوند

 مطالب مرتبط با روند و کلیت بازار را در تاپیک روند و پیش‌بینی بازار ارسال کنید
<غنوش> 1200 حمایت مستحکمی داره ، شاید عمدا شکسته بشه تا حد ضرر رو فعال کنن ، ولی به نظر به‌طور کامل از دست نمیره
با سلام .
 وضعیت نماد <سخوز> چطوره . و پیش قیمت آینده چند می‌تونه باشه ؟
 با تشکر
<دکوثر> فوق العادست حیف پایینتر فروختمش
اگه تا چهارشنبه دلار بره بالا <پترول> هم میره بالا
دقیقا
حد ضرر . 1150
سلام
پارسال719ت ، امسال حدودا 850تومن سودشه
پ ب‌ای 6 / 4
رشد قیمتی خاصی از اخرین قیمت ( 5 / 400 ) فک نکنم داشته باشه
سیمانی
<سبهان> » قیمت 7تا8هزار تومن
<ساروم> » زیر 4هزار تومن
<سغرب> » حدود 3هزار تومن
<سهرمز> » حدود 1 / 800تومن
سلام <وبانک> میان مدت صلاح میدانید اضافه کنم ؟
موارد فوق قیمت‌های پیش‌بینی برای آینده 4 سهم مذکور می‌باشد ؟
 چون از دیروز صف خرید برای <سخوز> شروع شد .
افزایش سرمایه <حفارس> اومد اما چرا دوباره شل کرد ؟
<خگستر> رشد خوبی خواهد داشت
سلام
من <وبیمهح> داشتم ولی از پرتفوی اصلیم حذف‌شده‌چه کار باید بکنم ؟
یکساله این سهم رو دارم مزخرف ترین سهم تاریخه
اگر صد تومن به ازای هر سهم را ریخته باشید تا دو ماه دیگه به پرتفوتون اضافه میشه
الان <ساروم> طبق <سیستم> ما از اخرین قیمتش دوشنبه ، حدود 40٪ پتانسیل رشد دارع
یعنی <ساروم> از قیمت 4 / 185تومن اگ انتظار رشد تا پی ب‌ای 7 ازش داشته باشیم ، قیمتش تا6000تومن میرسه
نه متاسفانه من صد تومن رو نریختم ولی یک میلیون سهم داشتم که از پرتفوم حذف شده
من زیر 250 فروختم بیچاره شدم
سلام ببخشید کسی از <غالبر> خبری داره ؟
اره من دارمش
<اخابر> جامانده ترین
میشه لطف کنید و نظرتون رو در مورد سهم بفرمایید
<وکار> چطوره ؟ من که 25 درصد تو ضررم
<غالبر> جای رشد داره من این سهم 4 ماهه دارمش وبا اینکه رشد زیاد کرده بازهم جای رشد داره هنوز
تشکر
<چکاپا> روسه ساله دارم 45درصد ضررم نگه‌دارم یا بفروشم
کسی نظری در خصوص <شسینا> داره ؟
2 سال قبل افزایش سرمایه داد ، فکر میکنم ، 2100 درصد ، یعنی 21 برابر شد تعداد سهام ، سهامداران
در حال حاضر قیمت ارزندگی هر سهم 186 تومنه
با توجه به گستردگی سهم‌های مختلف در پرتفوی <شستا> و افزایش قیمت ارزندگی شون ، قطعا ، ارزندگی <شستا> هم افزایش پیدا میکنه
سهم بزرگی است با شناوری بالای سهام ، برای رشد ، نیاز به ورود نقدینگی بالا در یک بازه زمانی بلند مدت هست .
با امور سهام تماس بگیرید و پیگیر باشید
وقتی سهام حق تقدم فروش رفت به حساب معرفی شدتون در سجام واریز میشه
جذاب نیست
<پترول> که نمیشه فروخت الان هفته پیش تا بالاترین سود رسید نفروختم الان کاملا توضررم وسودم ازدست دادم چون خیلی‌ها گفتن نفروش اونموقع
چقدر‌داری ؟
سلام کسی درباره <دزهراوی> تحلیل داره ؟
300000
آقا مانی سلام لطفا نماد <بجهرم> رو تحلیل بفرمایید ممنون
سهم رشد خوبی داشته الانم اصلاح زیادی کرده بلندمدتی سهم بسیار خوبی هست
حمایت مهم 460 و410داره
<رتاپ> مناسب ورود است حتما در سبد داشته باشید
لطفا در مورد <شفن> اگه تحلیلی دارید لطف کنید متشکرم
منم آن موقع‌ها <وکار> گرفتم تو منفی‌ها یه مدت داشتم رشد نکرد سر به سرفزوختم
کسی نظرش در مورد <خریخت> چیه
چن درصد توضرری
الان نگاه می‌کنم می‌گم
11 درصد
زیر500میانگین بزن
انگار حداقل خرید 5میلیونی هست
میانگین زدن یه کم سخته
بازار پایه حداقل خرید 5تومن هست
من تازه اومدم <بورس> بازم حدود 15 درصد سود‌بودم فکر کنم
اما منفی هاش 6 درصدی متبت هاش 1 درصدی هست
همیشه حدسود وضرر برای سهم در نظر بگیرید
البته من روز اول دیدم داره منفی می‌شه تو سود هم‌بودم یه مقدار ش فروختم گفتم سهم خوبیه بمونه
رو هیچ سهمی تعصب نداشته باشید
تجربه نداشتم
مهندس راج به خرید طلا به صورت گرمی در <بورس> اطلاعی دارید که قرار‌بود اجرایی کنن به چه صورت شد ؟
مقاومت مهم 1100و 1200مانع باز پس‌گیری سقف تاریخی شد
حمایت مهم سهم محدوده 680 تومان
 مقاومت سهم 900 تومان
هدف میان مدت 1700
خبر ندارم چجوری هست چون سمتش نرفتم تا حالا
دوستان احتمالا اطلاع دارن و راهنمایی تون میکنن
درود <شپنا> بخرم فردا ؟ یکشنبه بهتره ؟
سلام
بله
سلام روز همگی خوش
<غدشت> و <پاکشو> جامانده ترینها هستند خودتان بررسی کنید
<دکوثر>
پتانسیل رشد 25٪
ممنون
سلام <غدشت> من فکر میکنم یه موج صعودی یک رو شروع کرده و ار اس‌ای اش روند نزولی روشکوند و پولبک زد در حال زدن بوسه وداع است و ماه آینده رشد شارپی منتظرش است تو این مدت رشد نکرده و در حال تشکیل یه مستطیل‌بود و سهام کلی فشرده‌شده‌آماده است
برای رشد انفجاری
توکل به خداااا
درود <خساپا> بخرم فردا ؟ یا شنبه ؟
s1
i: 108, prev_index: 0

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

s2
درود <خساپا> بخرم فردا ؟ یا شنبه ؟
<خساپا>
در روند حاضر در حال پولبک به 340 تومان در سقف کانال کوچک فعلی است
نکته کلیدی :
 بازار تمرکز خاصی روی روند <خساپا> دارد و حرکت آن برای کل بازار حائز اهمیت است لذا محدوده 340 تومان در معاملات فردا از اهمیت بالایی برخوردار است در ادامه و برگشت می‌تواند در گام اول تا 600 تومان سقف تعدیل‌شده‌قبلی پیشروی کند
___
 _ com
شما مهندس راج هستین ؟
مهندس راج دیگه کیه !؟
نمیدونم
نوشتن مهندس راج شما هم جوابشونو دادین گفتم شاید میشناسنتون
ما اعتقاد داریم که امسال بازار سرمایه از خرداد ماه شتاب رشد بیشتری خواهد داشت و امسال <بورس> بازدهی مناسبی خواهد داشت .
 البته با توجه به تورم وحشتناک ایران کماکان از تورم عقب هستیم اما ما نصف و نیمه سرمایه‌گذاری تو <بورس> رو بلدیم و تو بازارهای موازی دلالی بلد نیستیم ، چاره‌ای نداریم که فقط همینجا گلیم خودمون رو از آب بکشیم بیرون ...
 کماکان هم با یکی دوتا سهم از گروه خودرویی بعنوان بخشی از سبدمون هستیم . البته نه در حد ازدواج همون جاست فرند !!!
سلام لطفا تحلیل سهام <پسهند> را بفرمایید
از روند <وساپا> تحلیل دارید ؟
توی همین کانال اسمارت <بورس>
چند بار تحلیل‌شده‌
سرچ کنید
دوستان و عزیزانی که سهام گروه خودرویی را عموما از مرداد 99 نگهداشتن دقت بفرمایید که اگر هر سهمی رو در اون تاریخ خرید داشتین تقریبا تو سقف قیمتی قبل از ریزش 99 بوده !
 حالا که این همه مدت صبور بودین این آخرا هم بازم کمی صبوری کنید که انشالله این سهم‌ها بتونن به سقف قبلی برسن و چه بسا سقفشون رو رد کنن انشالله
نکته مهمش اینه که امسال سهم‌هایی را که از آذر 401 تا کنون رشد زیادی کرده‌اند را با احتیاط بیشتری به سمت خریدشون برید .
 برای سود بهتر در <بورس> نقاط خرید بسیار مهم هستند
<چکاپا> رو میگم
نوشتن مهندس راج به منظورشون راجع به بوده
اگه شنبه بازار خوب‌بود بخر
<وسدید>
افشای _ اطلاعات _ بااهمیت
- ( تغییر در مفاد هر نوع اطلاعیه بااهمیتی که قبلا منتشر‌شده‌است - گروه الف ) منتهی به سال مالی 1402 / 12 / 29 شرکت گروه صنعتی سدید
1402 - 02 - 26 14 : 44 : 48
( 1026368 )
<غزر>
نظر شخصی
اگه امکان داره تحلیل د زهراوی لطفا
سلام اگه امکان داره تحلیل <دزهراوی>
سلام تو قطعه سازی‌ها <خاذین> ، <ختور> ، <خاهن> یا <خریخت> .. کدوم بهتره
<خزر>
<ختور>
دیروز راهشو جدا کرد و مثبت‌بود .... <ختوقا> .. هم عالیه از همه بهتره
<خاهن> از قبل داشتم فردا هم منفی بخوره کل سودم پریده کی و کجا میشه میانگین زد
چرا ایرانخودرو از جیب سهام‌دار به زنانی که فرزند دوم به دنیا می‌آورند باید <خودرو> مفت بده اگر دولت دنبال جوانی جمعیت است از جیب خودش از بودجه عمومی بده چرا از جیب شرکتی که دولت سهم ندارد می‌دهد این حق الناس هست و هیچ سهامداری راضی نیست
مدیریت کمونیستی همینه دیگه
سوال منم جواب بدید لطفا
<ختوقا> وخمهر فقط
وقتی 51درصد سهم داره یعنی هرچی اون بگه
<حفارس>
خکرمان و <حفاری> هم میتونه جذاب باشه
من بی‌تجربه‌ام ولی این بازار کفش معلوم نیست
کی 51 درصد دارد
بلوک ایران <خودرو> 51درصد از دولت هست 49درصد داخل <بورس>
<وسدید> واچ
هیچ وقت سمت سهم‌های که رانت دارن نرید
دوستان نظرتون در مورد
<ثشاهد>
و
کرمان
چیه ؟
کرمان اصلاح خوبی کرده گارد صعودی گرفته مقاومت سخت200را داره رد کنه تا300میره بلندمدتی سهم خوبیه سود خوبی میده
مقاومت اولش 170 تومنه
بتهران
<وسدید>
بررسی کن
خرید پله‌ای رعایت کنید
گفتم مقاومت مهمش
اگه خودتون میدونید دیگه چرا میپرسید
وقتی تو این گروهها ی عمومی حضور داریم ، مدام تحت آزمون الهی قرار میگیریم .
اینم درسته
چارت و نمودارش خیلی زیباست ... از بحاظ تکنیکالی خیلی حرفا داره اما بنیادی شرکتیه که بیشتر معروف به داروهای پیوند اعضاش و دولت رو محصولاتش حساسه و دیر تر از همه داروییها افزایش نرخ گرفت و کم کم باید تو صورتهای مالیش خودشو نشون بده
بزودی
<خودرو>
به عنوان لیدر استارت میزنه
سلام چکارش کنم
با تشکر
الان توجاده هستم تااخرشب تحلیلش میفرستم
ممنون
پی به‌ای ش که اصلا خوب نیست
اساتید اینو جواب بدن لطفا
امروز تعطیل‌بود چطوری رو کدال تاریخ افشا امروز زده ؟!
الان به راحتی تو روز روشن از جیب منو شما دزدی‌شده‌تو <بورس> و همچنین قانون شکنی هم‌شده‌هر چند تو این مملکت قانونی نیس
افشا را ناشر اعلام میکنه
هر زمانی میتونه باشه
اوک نمیدونستم
چون دیروز صف فروش‌بود پس یعنی فردا صف خرید میره یا مشخص نیس ؟
هر زمان که باز بشه
صف خرید سنگین خواهد داشت
تشکر
اینده سهم درخشانه
تو واچ داشته باشید
کوتاه مدت یا بلند مدت ؟
بلند مدت
تقسیم سود و ....
 یه مقدار در مورد این افشا الف تحقیق کنید
متوجه خواهید شد
که در اینده الماس <بورس> خواهد شد
مفاهیم <بورس> : سهام شناور آزاد
سهام شناور آزاد  ( Free Float ) بخشی از سهام یک شرکت است که دارندگان آن ، آماده عرضه و فروش آن سهام هستند و قصد ندارند با حفظ آن قسمت از سهام ، در مدیریت شرکت مشارکت کنند و انتظار می‌رود ، در آینده نزدیک ، قابل معامله باشد .
 برای محاسبه سهام شناور آزاد باید ترکیب سهامداران بررسی‌شده‌و سهامداران راهبردی را مشخص کرد . سهامدار راهبردی ، سهامدارانی هستند که در کوتاه‌مدت ، قصد واگذاری سهام خود را نداشته و معمولا می‌خواهند برای اعمال مدیریت خود ، این سهام را حفظ کنند .
<غزر> الان خوب اصلاح کرده
من ذهنم رفت سراغ راج کاپور
غویتا ، <غسالم> ، <غشان>
باز بشه <وسدید> خرید بزنم یا <فنوال> ؟
<غدام> خوبه . بنظرم یک سال و نیم تا دو سال اعداد بالای رو میبینه .
<خمحرکه> ، <خاهن> ، <خریخت> ، <خکار> ، <خکمک> ، <ختور> عالی هستن . اون یکی‌ها هم خوبن .
<امید> منشا حل تمام مشکلات است
سلامتی باشه
فقط باید با <سیستم> اینکارو بکنی
<ختراک> . <خنصیر> هم آخرای اصلاحش هستش
<ختراک> دو روز صف خریده
راجب <خرینگ> و <خاذین> کسی نظری داره
حمایت اول 385
حمایت دوم 345
تارگت اول 520
تارگت دوم700
<وسدید> احتمالا به بار دیگه بیاد پایین به قیمت 209تومن پولبک بزنه .
تشکر
چ سایتی هس
<خودرو> نظرتون
خواهش میکنم
شخصا ترجیح میدم روی قطعه سازهای گروه سرمایه‌گذاری کنم تا شرکتی که زیان ده هست
<ختوقا> <خمهر> سلاطین
باز هم الگوی پوشای صعودی در ناحیه حمایتی ( <حکشتی> )
<خمحور>
فرصت خرید میده
شکل‌گیری گارد صعودی
معاملات امروز <خساپا> روی کل گروه خودرویی و حتی کل بازار موثر است
<خساپا> دقیقا روی خط حمایت است
خساا و گروه خودرویی خروج پول دارند اخر بازار احتمال مثبت شدنش هست ولی باید دید تکلیف توافق چی میشه
توافق ؟
بله توافق برجام
کی بهت گفتم شاوان بخر ، حالا هی حس ناسیونالیستی گل میکنه ، میری <شپنا> میخری
بالاب چند ده ساله توافق تکلیفش مشخص نیست
مسئله جدیه ؟
 یا مثل همیشه
دیگه تموم شد منتظر موندن واسه توافق هیچکس جدی نمیگیره اصن توافقو
اهان برجام
به برجام هیچ اعتقادی ندارم
شرکت سایپا اثرش بیشتره روی اقتصادمون فعلا
<دامین>
<رتاپ>
فرصت خرید داده حتما کمی در سبد سهام خود داشته باشید
افزایش سرمایه خورد ولی چقدر از قیمتش اومد پایین
135 هزار سهم دارم از <شستا>
وقتی 21 برابر افزایش پیدا میکنه ، 22 برابر قیمتش میاد پائین
صف خرید شد تمام
پاک میکنه نمیزاره حرفمو بزنم .... نمیدونم چقدر دیگه باید پول به پای این سهم بریزم تا از ضرر دربیاد
<ثبهساز> خوبه امروز برای ورود ؟
اره
کامبک میزنه امرو
یعنی چی ؟
<قشرین>
زمان قطعی که نمیشه گفت ، باید دید دیدگاه حضرات وتصمیمات آقایون چیه
اگر بنا بر حمایت از بازار سرمایه ومبارزه با بازارهای دلال بازی موازی باشه ، میشه گفت قطعا امسال خیلی بیشتر از سرمای‌گذاری تون سود میکنید
11 حقوقی بیش از 18 میلیون سهم <خساپا> خرید زدن !
 11 یار <خساپا> ( اوشن )
سلام <خلنت> چطوره ..؟؟
خوبه سلام میرسونه
اون 11 نفر بازم دارن میخرن
فکر کنم شاسی بلند گرفتن !
<ونوین> هم رشد نمی‌کنه بفروشیم یا نگه داریم . اگه بهتره بفروشیم
<خمحرکه>
حمایت خوب در 1000 تومن و برگشت سهم
<خریخت> در آستانه صف خرید !
عاشقتم
کانال اسمارت <بورس> رو اگه داشته باشی متوجه میشی
سلام لطفا <پکویر> رو تحلیل کنید دوستان عزیز
خوووب پس فهمیدیم این اصطلاح زیر سر کیه
آفرین به این هوش
استاد این گروه کیه لطفا یه تحلیل از <شستا> بزارین ممنون میشم
اینهمه همه میگن <بورس> رشد میکنه شما میگی این نصفم از دست میدی
چرا انقدر با من لجی ؟
یعنی شما میگی <بورس> میریزه ؟
یا <شستا> ؟؟؟
الان <شتران> 5.50 هست توی جدول
من 20 هزار تا دارم
با قیمت فعلی لاستیک <پتایر> به زودی بالای 400
میشه تحلیلی در مورد سهم <فاراک> بدین
سهم بسیار پر پتانسیلی میگن
صف فروش <خپارس> مناسب خرید
<خلنت>
با عنایت به مجوز افزایش سرمایه به شماره مجوز DPM - IOP - 01A - 251 مورخ 1401 / 12 / 23  بر اساس تصمیمات مجمع عمومی فوق العاده مورخ 1402 / 02 / 05  افزایش سرمایه شرکت از مبلغ 300 ، 000 میلیون ریال به‌مبلغ 600 ، 000 میلیون ریال ( از محل سود انباشته مبلغ 300000 میلیون ریال ، ) در تاریخ 1402 / 02 / 24 در مرجع ثبت شرکت‌ها به ثبت رسیده است .
یکی از دوستان راجب <خلنت> پرسید
این خبر رو پیدا کردم
<خاهن>
حمایت مهم 600 حمایت بعدی 570 ، مقاومت پیش رو 650 در صورت عبور هدف اول 780 و هدف دوم 1200
<دامین>
<رتاپ>
فرصت خرید داده حتما کمی در سبد سهام خود داشته باشید
بیزحمت <خمحرکه> رو تحلیل کنید
مقاومت‌های مهم سهم 1150 و 1350 ، حمایت‌ها 1000 و 850 حدضرر شکست 1000
ممنون
سلام <خمحرکه> که اینهمه روش تاکید میکردین من الان 20 درصد ضررم همون که میگفتین مفت ترین سهم بازار
<خنصیر>
حوالی سقف تعدیل‌شده‌ی قبلی که بهش پولبک زده‌شده‌اردرهای حمایتی از حقوقی شاهدیم ، اگه از این محدوده بالا بزنه چارت قشنگی خواهیم داشت
( احتمالا کد prx در حال خرید باشه )
 <والبر>
در رشد اخیر بازار رشد خاصی نکرد و در ریزش اصلاح هم کرد ، زیر ارزش داره معامله میشه و به دید میان مدت گزینه ی کم ریسکی میتونه باشه
معاملات <خمحرکه> در مثبت‌های بالا
مفت ترین سهم بازار ه صبور نیستی سربه سر شدید بفروشید .
 بازار تعهدی نداده از روزی که می‌خرید صف باشه
رنج مثبت در
<خودرو>
، عبور سهم از محدوده 380 سیگنال خوبی برای کل بازار هست
کسی تحلیلی اخباری از سهم <شفارس> داره ؟
خریدید یانه
من 30 درصد سودم بدموقعه وارد شدی
لامبورگینی
خوب شد ازدواج مون پایه هاش سست نبود
دیروز تو منفی کامل ی خرید توپ زدم زش
نوش جونت
عالی
ایشالله پرسود باشی
<فولاد>
خبر مهمی داره دست به دست میشه مبنی بر این که <فولاد> ، با پول فروش
<فجر>
به دنبال خرید
<اپال>
هست باید منتظر شفاف‌سازی شرکت باشیم .
نوبت <خریخت> هست
<خمحرکه>
در روند صعودی پرشتاب قرار دارد با برگشت و تثبیت دوباره روی خطوط ایچیموکو می‌تواند در گام اول تا 2500 پیشروی کند و با شکست سقف تعدیل‌شده‌، در ادامه تا 4800 در میدلاین کانال ادامه مسیر صعود می‌تواند طی شود
نکته کلیدی : سقف کانال بزرگ اعداد بالای 30 هزار تومان را نشان می‌دهد که در حال حاضر غیر قابل دسترس به نظر میرسند ولی تجربه نشان داده که وقتی بازار وارد یک روند پرشتاب هیجانی می‌شود این مدل رشدها در <بورس> ایران همیشه میتوانند تکرار شوند
___
 _ com
معاملات امروز <خمحرکه> خیلی جالب‌بود .
 بارها این حرکت رو در سهام پرپتانسیل دیدم .
 با حفظ محدوده 1000 تومان یه پایین ترسناک به زیر محدوده زد و آماده جهش شد و به تدریج بالا اومد و یه دفعه شتاب گرفت
<خشرق>
<خاور>
حس پیروزی داره رو 1200 فروخته باشی و امروزم رو 1000 تومن دوباره وارد‌شده‌باشی حالا امیدوارم خودمو چشم نکنم
این حرکت <خمحرکه> ، به نظر میاد از اون حرکتهاست که میخواد بزنه تو گوش اهداف بالاتر
به قولی این توربمیری ، آن توبمیری نیست
امیدواریم
لعنت به این <شبریز>
عالی‌بود حرکتت
من از 570 آرام آرام خرید زدم
و فعلا هستم باهاش
1سال تمام سرمایه مون بلوکه شد به اسم دادن افزایش سرمایه الانم یکماه نشسته تو پرتفو و همچنان منفی سهامداران <شبریز> نمیخاین یه کاری کنین چقدر دیگه باید دزدی بشه از جیب منو شما
من از 7006 داشتم
<شبریز>
دزدیخوردن
حق
سهامدارن
پر سود باشی
صبور باش
بازگشت چراغ خاموش <خودرو> به <بورس> <کالا>
 به گزارش بازار نیوز ، همزمان با کش و قوس شورای رقابت با خودروسازان بخش خصوصی بر سر تعیین تکلیف اتومبیل‌های مونتاژی ، 500 دستگاه <خودرو> در <بورس> <کالا> عرضه شد .
 اقدامی که می‌توان آن را به نوعی بازگشت چراغ خاموش <خودرو> در <بورس> <کالا> در سال 1402 دانست .
<خشرق>
حمایت مهم حوالی 1500 مقاومت 1750
بعد از اصلاح و کف‌سازی مناسب اهداف 2400 و 3200
سلام آقا مانی <غاذر> تو ضررم بفروشم بره یا نگه دارم ؟؟ ممنون میشم جواب بدید
هم اکنون در تمام گروه‌های بورسی
اعلام خرید انواع و اقسام سهم‌ها
وگرفتن پشت بازو <همراه> با اموجی
همه رفتن رو استیج دارن فیگور میگیرن
یارو تو گروه ش دوشنبه گفته‌بود میریم برا شاخص 1800
الان پست زده دیدید فلان سهمو گفتیم چه شد و چه و فلان
همینجا خیلیا گفتن <بورس> رف واسه 1800
و <خریخت>
نوبت <وساپا> است
مقاومت مهمی محدوده 4750 داره در صورت عبور میتونه تا 5500 پیش بره
حمایت مهم حوالی 4300
حمایت و مقاومت‌های سهم رو خدمتتون عرض کردم ، دیگه خرید و فروش با خودتون هست
خدا خیرت بده ممنون
دوستان باور کنید تو این شرایط بد اقتصادی وضع هممون مثل هم هست
هیچکس نمیتونه رضایت داشته باشه
<بورس> آخرین سنگر ماست که بتونیم کمی از این فشارها رها بشیم
همگی تو یه سنگریم
پشت هم باشیم و با هم سود کنیم
متاسفانه همه منتظرن کی نوبتشون بشه پشت بازو بگیرن
<خاذین>
افشا الف زد
امروز و البته دیروز هم
در معاملات <خمحرکه> و <خریخت>
نسبت قدرت خریدار به فروشنده حدود 30 درصد بالاتر‌بود
این نکته میتونه در انتخاب سهم یا پیش‌بینی حدودی حرکت سهم مهم باشه
پشت بازو گرفتن هم اگه به قصد توهین به کسی نباشه هیچ ایرادی نداره
کل کل تو <بورس> هم جزو جذابیت‌های بازاره
s1
i: 280, prev_index: 108
s2
پشت بازو گرفتن هم اگه به قصد توهین به کسی نباشه هیچ ایرادی نداره
کل کل تو <بورس> هم جزو جذابیت‌های بازاره
<امین> جان برای منم ارسال کن
آقا علیرضا شما کلا بازار چه مثبت باشه چه منفی دیدتون منفی هست نمیدونم چرا و همیشه شاکی هستید
نه برادر
امروز استثنا اوکی‌بودم
کانال‌ها رو میدیدم جالب‌بود رفتاراشون
حالا باید نذر و نیاز کنیم ضایع نشیم
پیام‌ها را پاک کرده و از گروه لفت میدهیم
استاد <امین>
من همیشه از شاگردام خواهش کردم منو استاد صدا نکنن
نه برازنده شماس استاد باید گفت
سلام ، تحلیل <فمراد> لطفا
پیش‌بینی معاملات <خساپا> برای شنبه ؟
استاد <امین> سهام‌هایی که سیگنال کردیو بگو ، امروز من وقتم آزاده می‌خوام تحلیل و بررسی کنم ...
دیگه بستگی داره به سرمایه‌ای که تو <بورس> دارید محتاطانه ش میشه ده درصد از سبد
معاون بازاریابی و فروش گروه سایپا :
 از ابتدای سال 58 هزار <خودرو> فاکتور و تحویل مشتریان شد / رشد 30 درصدی تحویل <خودرو> به مشتریان نسبت به مدت مشابه سال قبل
حسین کاظمی طرقی افزود : در سال « مهار تورم و رشد تولید » گروه خودروسازی سایپا با برنامه‌ریزی دقیق موفق شد تولید محصولات خود را نسبت به سال گذشته به صورت چشم‌گیر افزایش دهد و در راستای پاسخ به درخواست‌های خرید متقاضیان اقدام کند .
 او تصریح کرد : از ابتدای سال جدید تاکنون تعداد 58 هزار دستگاه <خودرو> مشتریان فاکتور و تحویل‌شده‌که نسبت به مدت مشابه سال گذشته حدود 30 درصد رشد فاکتور و تحویل داشته است .
 کاظمی خاطر نشان کرد : با ادامه افزایش تولید در گروه خودروسازی سایپا روند رو به رشد تحویل <خودرو> به مشتریان براساس درخواست خرید ادامه خواهد داشت .
<ثبهساز>
نمودار تعدیل‌نشده‌لگاریتمی
بعضی وقتها نیاز نیست تحلیل پیچیده‌ای از سهم برای خرید یا نخریدن داشته باشید
نکته کلیدی :
 اکر فقط به این نتیجه برسید که اینجا در این قیمتها نباید بخرید کافی است
سلام آقا مانی
تحلیلتون رو <ثبهساز> چیه ؟
سلام
چارتی که گذاشتید خیلی واضح هست
دانش‌کاظمی : هیچ حبابی در <بورس> دیده نمی‌شود
عضو شورای عالی <بورس> :
 بازار سهام از مدت‌ها قبل به دنبال هماهنگی برای ایجاد تعادل‌بود که این امر باعث شد بازار تا بهمن 1401 در وضعیت رکود قرار بگیرد
اکنون نرخ ارز جدید باید معیاری برای ارزیابی معاملات بازار باشد و نباید در این زمینه سال 99 را مورد ارزیابی قرار داد .
 از فروردین 1401 تاکنون حداقل 25 شرکت وارد <بورس> و فرابورس شدند
حبابی در بازار سهام حس نمی‌شود و نگران وضعیت موجود نیستم
سیاست‌مداران و اقتصاددانان باید تجربه سال 99 را به یاد داشته باشند و مراقب باشند تا فنر رشد بازار را بیشتر از یک حد مشخص بالا نبرند و همچنین بیشتر از حد مشخص اقدام به سرکوب بازار نکنند .
بله مسئول عزیز میدونیم
حباب تو مسئولین ومدیران مملکت دیده میشه ، نه توبورس
مقاومت سهم محدوده 220 که در صورت عبور و تثبیت بالای این محدوده هدف میان مدت سهم 340
حمایت‌های سهم 195 ، 160
من همیشه میگم بازار سرمایه قابل پیش‌بینی نیست ولی توبلند مدت هیچ جا مثل <بورس> نیست فقط کافیه طمع نکنیم و حتما به حدسود وضرر پایبند باشیم
من فقط بااین بنده خدا بحثم شد که <خساپا> نوسانی گف
اره راستی اونم چند روزه نیستش بنظرم بازار نوسانشو گرفت
احتمال زیاد
هیچکدوم دوس نداریم ضرر کنیم
موقعی میدونیم بازار صعودیه برمیگرده
اخه چرا باضرر بفروشیم
<کویر> جامانده فلزی هاست ، پولبک هم زده و آماده رشد هست ، شنبه هر فرصتی بده برای خرید مناسبه .
سلام
لطفا <دسبحان> رو تحلیل کنید کف و حمایت هاش مقاومت هاش
مممنون
سلام <شبریز> فرصت خرید ، در صورت عبور از 2100 کوتاه مدتی تا 2900 و در ادامه 3900 رشد خواهد داشت
<شبریز>
با واکنش به کف کانال وارد روند صعودی‌شده‌است و با دید چنگال اندروز داخل کانال بزرگ می‌تواند به مرور از بالهای چنگال عبور کند
نکته کلیدی :
 حمایت اصلی فعلی که می‌تواند قبل از آن یا از خود این حمایت برگشت بزند در محدوده 1800 قرار دارد با برگشت از این حمایت اهداف بعدی میتوانند در 2900 و 3900 باشند
___
 _ com
سلام <شبریز> فرصت خرید ، در صورت عبور از 2100 کوتاه مدتی تا 2900 و در ادامه 3900 رشد خواهد داشت
<شبریز>
با واکنش به کف کانال وارد روند صعودی‌شده‌است و با دید چنگال اندروز داخل کانال بزرگ می‌تواند به مرور از بالهای چنگال عبور کند
نکته کلیدی :
 حمایت اصلی فعلی که می‌تواند قبل از آن یا از خود این حمایت برگشت بزند در محدوده 1800 قرار دارد با برگشت از این حمایت اهداف بعدی میتوانند در 2900 و 3900 باشند
___
 _ com
دوست عزیز سلام الان که درخت صبوری شما به میوه دادن رسیده حیف نیست به قول خودت سرمایه‌ات رو و به تاراج بذاری و با بیان مطالب هیجانی دیگران رو هم مضطرب و متضرر کنی ، این نماد رو تازه بزرگان بازار دارن سیگنال میکنن مثل گروه پرویز خالقی و گروه تالار <بورس> ، گروه دکتر کشمیری و .... لطفا صبور باشید و فرصت سوزی نکنید ممنون
سللام خوش آمدید
لطفا مطالب ، اخبار و تحلیلهای هر " سهم " یا " موضوع " را در تاپیک مربوط به خودش ارسال نمایید
مثلا مطالب مرتبط با " <خساپا> " را در تاپیک " <خودرو> و ساخت قطعات " ارسال بفرمایید
 پستهای غیرمرتبط با هماهنگی و پیشنهادات از این تاپیک حذف میشوند

 مطالب مرتبط با روند و کلیت بازار را در تاپیک روند و پیش‌بینی بازار ارسال کنید
رکورد
ثبت یک رکورد جدید در <بورس> <کالا>
رکورد ارزش معاملات بازار فیزیکی از ابتدای تاسیس <بورس> <کالا> شکسته شد
در معاملات روز دوشنبه 25 اردیبهشت ماه <بورس> <کالا> ، ارزش معاملات بازار فیزیکی به رقم بی‌سابقه 18 ، 828 میلیارد تومان رسید .
 رکورد قبلی ارزش معاملات بازار فیزیکی مربوط به معاملات 15 فروردین ماه با ارزشی معادل 16 ، 956 میلیارد تومان‌بود که پشت سر گذاشته شد .
سلام
حمایت‌ها 960 و840
تارگت‌ها 1400 و1600
بلندمدتی باشی سود خوبی میده
نکته‌ای که تو این خبر باید بهش توجه کنید ، تو سطر چهارمه ، که عملا با زبون بی‌زبونی دیدگاه مسئولین مملکتی رو نسبت به قیمت دلاری بازار بیان میکنه وعملا میگه ، باید بازارو باقیمت دلار ی مرکز مبادله ارز وطلا سنجید که مورد تائید نظام مقدس هست ، نه با قیمت بازار آزاد
واین یعنی اینکه ، اگرچه بازار نسبت به قیمت دلار مرکز مبادله ارز وطلا نیاز پائینتر می‌باشد ، ولی عملا نباید انتظار شارپی زیاد از بازار داشته باشیم .
کرمان
ممنون
<ثبهساز> 3450 تومن میاد
<فنوال> چطوره ؟؟
 ورود الان مناسبه یا اصلاح داره ؟
شاید منظور ریاله درسته ؟
قیمت الانش 400تومان هست
اره
سلام استاد ببخشید سهم <فنوال>
سلام
وقت بخیر
ممنونم .
خواهش میکنم
سللام خوش آمدید
لطفا مطالب ، اخبار و تحلیلهای هر " سهم " یا " موضوع " را در تاپیک مربوط به خودش ارسال نمایید
مثلا مطالب مرتبط با " <خساپا> " را در تاپیک " <خودرو> و ساخت قطعات " ارسال بفرمایید
 پستهای غیرمرتبط با هماهنگی و پیشنهادات از این تاپیک حذف می‌شوند
<خودرو>
به <بورس>
<کالا>
بر می‌گردد
علیزاده عضو ناظر در شورای عالی <بورس> و عضو کمیسیون اقتصادی مجلس : به دنبال اصلاح قانون شورای رقابت هستیم تا با مستثنا کردن <خودرو> از دستورالعمل‌ها و قوانین شورا ، مقدمات عرضه <خودرو> در <بورس> فراهم شود
گزارشات همگی هم عالی تا الان ... افزایش نرخ قیمت 10 درصدی قطعاتشون .. امیدواریم هفته آینده سبز باشد
جناب <امین> خان شما هم ناراحت نشید بلکه بیشتر مردم رو درک کنیم ، در این بازار انواع و اقسام انسانها حضور دارن . از حرفه‌ای تا مبتدی . که البته مبتدیان خیلی بیشترن . وقتی یک دوستی مثلا می‌پرسه <پدرخش> در کدوم گروه قرار داره تو خود بخوان حدیث مفصل از این مجمل
ببینم هفته آینده شاخص میبرن بالا
عزیز دل برادر دنبال کدام <خودرو> ، برای عرضه تو <بورس> میگردی ؟
 دیگه خودرویی نمونده ، چرا دلت تو خوش میکنی به این خبرهای ، صد تا یه غاز
ایرنخودرو که تا پایان سال و حتی بیشتر ، برای خودش تعهد ایجاد کرده ، تازه اگر برسه
سایپا هم که بهترین <خودرو> سدانش ، شاهین به لعنت خدا نمیارزه
از م ا د ر بزرگانی که بعد از ا ن ق ل ا ب به دنیا اومدن ، تا م ا د ر ا ن دارای 2 فرزند براشون سهمیه در نظر گرفتند ، و جالبه همه هم به خاطر نداشتن توان مالی در <پرداخت> قیمت <خودرو> ویا نیاز مالی ، دارند حواله هارو میفروشند
دوست عزیز بایدقبول کنی <بورس> ایران با سهم <خودرو> بالا وپایین میشه پس این اخبار رو روند سهم وکل بازار تاثیرگذار هست من کاری به این ندارم به کیا میدن من فقط درباره <بورس> میگم
f1
i: 331, prev_index: 280
f2

In [12]:
dataset.head()
# dataset[["embedding","sentiment"]]

,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text,channel_name,id,sentiment,annotator,annotation_id,created_at,updated_at,lead_time,embedding
0,channel1451535779,58838,2023-05-14T09:13:32,1684043012,🔰 خودرو محدوده 360 حمایت مهمی داره که با چند م...,,<خودرو> محدوده 360 حمایت مهمی داره که با چند م...,گلدن بورس,351,BUY,1,1,2023-05-21T13:06:07.424477Z,2023-05-21T13:06:07.424518Z,119.124,"[-0.00980202853679657, 0.0012244143290445209, ..."
1,channel1451535779,58842,2023-05-14T09:16:05,1684043165,🔰\nخنصیر هم محدودهه 2000 تومان روی حمایته برمی...,,<خنصیر> هم محدودهه 2000 تومان روی حمایته برمید...,گلدن بورس,352,BUY,1,2,2023-05-21T13:06:16.550024Z,2023-05-21T13:06:16.550058Z,8.163,"[-0.0033478252589702606, -0.023208031430840492..."
2,channel1451535779,58845,2023-05-14T09:19:36,1684043376,کدما از صف فروش به منفی 1 ✅\n,,<کدما> از صف فروش به منفی 1,گلدن بورس,353,IRRELEVENT,1,3,2023-05-21T13:14:13.435865Z,2023-05-27T13:20:05.024468Z,476.651,"[-0.015989402309060097, -0.011134997941553593,..."
3,channel1451535779,58846,2023-05-14T09:19:51,1684043391,وتوشه مثبت 2 🔥\n,,<وتوشه> مثبت 2,گلدن بورس,354,IRRELEVENT,1,4,2023-05-21T13:16:59.640285Z,2023-05-21T13:16:59.640338Z,132.469,"[-0.036382317543029785, -0.021262574940919876,..."
4,channel1451535779,58883,2023-05-14T10:13:26,1684046606,وتوشه رفت مثبت 3 ✅\n,58846.0,<وتوشه> رفت مثبت 3,گلدن بورس,355,BUY,1,5,2023-05-21T13:17:12.084779Z,2023-05-21T13:17:12.084825Z,11.896,"[-0.026954285800457, -0.021720044314861298, -0..."

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# fs_df = pd.read_csv(embedding_path)
dataset.dropna(axis=0, inplace=True)

dataset["embedding"] = dataset.embedding.apply(eval).apply(np.array)
# fs_df.head()

X_train, X_test, y_train, y_test = train_test_split(
    list(dataset.embedding.values), dataset.sentiment, test_size=0.2, random_state=42
)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
preds = clf.predict(X_test)
probas = clf.predict_proba(X_test)
clf
report = classification_report(y_test, preds)
print(report)

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)
/tmp/ipykernel_20633/599966227.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["embedding"] = dataset.embedding.apply(eval).apply(np.array)

              precision    recall  f1-score   support

      BARASI       1.00      0.25      0.40        12
         BUY       1.00      0.40      0.57        10
  IRRELEVENT       0.73      1.00      0.85        44
        SELL       0.00      0.00      0.00         1

    accuracy                           0.76        67
   macro avg       0.68      0.41      0.45        67
weighted avg       0.81      0.76      0.71        67

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    list(dataset.embedding.values), dataset.sentiment, test_size=0.2, random_state=42
)

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
preds = clf.predict(dataset.embedding)
probas = clf.predict_proba(X_test)
clf
report = classification_report(y_test, preds)
print(report)

ValueError: setting an array element with a sequence.

In [27]:
import pickle
filename = "stock_nlp_model_v1.pickle"

# save model
pickle.dump(clf, open(filename, "wb"))

# load model
loaded_model = pickle.load(open(filename, "rb"))

# you can use loaded model to compute predictions
y_predicted = loaded_model.predict(X_train)
y_predicted

ValueError: setting an array element with a sequence.

In [36]:
# X_test["pred"]=y_predicted
X_test

[array([-0.02433092, -0.01240689,  0.00979138, ..., -0.00116608,
         0.01661853, -0.01176978]),
 array([-0.01711572, -0.01455043,  0.00510644, ..., -0.01124727,
        -0.01423321, -0.00705799]),
 array([-0.02633973, -0.00714222, -0.00157817, ...,  0.01065888,
         0.03748544, -0.03046493]),
 array([-0.01291646,  0.00914754,  0.00704005, ..., -0.00073415,
         0.00652288, -0.01662719]),
 array([ 0.00167979, -0.00659456, -0.00626113, ..., -0.01361349,
         0.01114138, -0.00788788]),
 array([ 0.00168148, -0.00443938,  0.00240888, ...,  0.00385551,
        -0.00237463, -0.00047786]),
 array([-0.02571721,  0.00386424, -0.00151905, ..., -0.01628312,
         0.01228563, -0.01124628]),
 array([-0.01449361, -0.01413763,  0.00349627, ..., -0.02271937,
         0.00995482, -0.02967376]),
 array([-0.01820331, -0.01997553, -0.01874763, ..., -0.00906368,
         0.02217816, -0.03792566]),
 array([ 0.00012259, -0.01465429,  0.01338058, ..., -0.0107084 ,
         0.02051076,  0.00172181]),
 array([-0.00784898, -0.01757292,  0.01251053, ..., -0.01737896,
         0.00392126,  0.00105143]),
 array([-0.0402419 , -0.01836037, -0.00982882, ...,  0.00578808,
        -0.00172087, -0.0236024 ]),
 array([-0.02777375, -0.00205842, -0.00357481, ..., -0.00096935,
         0.01597523, -0.02140228]),
 array([-0.0265388 , -0.00905045, -0.00809378, ..., -0.01493496,
         0.00163287, -0.01420541]),
 array([-0.02869158, -0.00632842, -0.01464666, ..., -0.01111833,
         0.00532668, -0.01438682]),
 array([-0.01121496, -0.00727082, -0.01127797, ..., -0.03079703,
        -0.00844902, -0.02523996]),
 array([ 0.00344203,  0.00400689,  0.0020084 , ..., -0.00540418,
         0.0132528 , -0.01777171]),
 array([-0.02534851, -0.01079948, -0.000974  , ..., -0.02999639,
        -0.00837139, -0.02510114]),
 array([ 0.00229273, -0.02351651,  0.00054596, ..., -0.00821029,
        -0.01085525, -0.01718908]),
 array([-0.02293207, -0.01167702,  0.00186101, ...,  0.00169287,
        -0.00755611, -0.01651003]),
 array([-0.00890609, -0.00700598,  0.00542886, ...,  0.00273333,
        -0.0041438 , -0.00825325]),
 array([-0.01189618, -0.01651964, -0.00722177, ..., -0.02314278,
         0.00834261, -0.02898897]),
 array([-0.01232079, -0.00168443,  0.00839498, ..., -0.0062419 ,
        -0.01463008, -0.0184608 ]),
 array([-0.0207586 , -0.02708665,  0.0097204 , ..., -0.0104902 ,
         0.00433178, -0.00823298]),
 array([-0.02385999, -0.01209464, -0.01811109, ..., -0.00658242,
        -0.0011731 , -0.01968895]),
 array([ 0.01818892, -0.00060021, -0.00549321, ..., -0.00952504,
         0.0042406 , -0.00523225]),
 array([-0.00853376, -0.00399704,  0.00717781, ...,  0.00434446,
         0.01139409, -0.01972547]),
 array([-0.03418191, -0.02257888,  0.00376641, ..., -0.00086075,
        -0.01362834,  0.00829068]),
 array([-0.01187182, -0.01902086,  0.01099603, ...,  0.00214082,
        -0.01052894,  0.00538773]),
 array([-0.00680147, -0.00069738, -0.01298522, ...,  0.00672344,
         0.00787436, -0.01881784]),
 array([-6.32661348e-03, -2.42323685e-03, -3.20557010e-05, ...,
         9.94182099e-03,  1.42905489e-02, -3.03887017e-02]),
 array([-0.01216715, -0.01605468,  0.01815046, ..., -0.01494211,
        -0.00366114, -0.01580888]),
 array([-6.71614381e-03, -6.20484585e-03, -3.93864233e-03, ...,
        -4.56147718e-05, -6.45884546e-03, -3.88215209e-04]),
 array([-0.01621526, -0.01632098, -0.01215814, ..., -0.00094655,
        -0.00513087, -0.01538269]),
 array([-0.018812  ,  0.00054933,  0.00554688, ..., -0.00445957,
         0.00025844, -0.02223944]),
 array([-0.0207144 , -0.00062205,  0.00730043, ..., -0.00278822,
        -0.01318189, -0.01653704]),
 array([-0.01252711, -0.01261415, -0.00061933, ..., -0.01815795,
        -0.00280705, -0.00846969]),
 array([-0.01843536, -0.00114705, -0.01186114, ...,  0.00641933,
        -0.00777892, -0.00961695]),
 array([-0.01125744, -0.01504619, -0.00805366, ..., -0.00307114,
        -0.01461086, -0.01417553]),
 array([-0.01586672,  0.00723065,  0.00263843, ..., -0.00464312,
        -0.01291141, -0.01938682]),
 array([-0.03168934,  0.0061218 ,  0.0207095 , ...,  0.00685221,
         0.0028214 , -0.01166608]),
 array([-0.00847587, -0.00299274,  0.00507571, ..., -0.01306397,
         0.00474191, -0.00899948]),
 array([ 0.00789319,  0.00178372,  0.01008904, ..., -0.01408509,
         0.01134852, -0.01573363]),
 array([-0.00755751, -0.00484017,  0.0072888 , ..., -0.00996248,
        -0.00447405, -0.00890107]),
 array([-0.01727476, -0.02307758, -0.00108552, ..., -0.01536277,
         0.00144736, -0.01585748]),
 array([-0.02603668, -0.01769641, -0.01140045, ...,  0.00600436,
         0.00624893, -0.00925581]),
 array([-0.03222121,  0.00916885,  0.01097918, ..., -0.00475048,
        -0.00940979, -0.00072079]),
 array([-0.01685966,  0.00202576, -0.00661915, ..., -0.01792672,
         0.00347464, -0.01790005]),
 array([ 0.00021699, -0.00790491,  0.00430343, ..., -0.01691017,
         0.01251505, -0.02589015]),
 array([-0.01789879, -0.01984777,  0.00544587, ..., -0.01251589,
        -0.00794176, -0.01389476]),
 array([-0.01185695, -0.02692685,  0.00782398, ..., -0.00578732,
         0.02025899, -0.01709983]),
 array([-0.01668713, -0.02711001, -0.00556018, ..., -0.00488243,
         0.00950824, -0.03366379]),
 array([-0.00095604, -0.00570484, -0.00832258, ..., -0.00998181,
         0.00186415, -0.01883984]),
 array([-0.00462907, -0.00777335,  0.00072476, ..., -0.02327302,
        -0.01010468, -0.01873128]),
 array([ 0.00471432, -0.00538731, -0.00862506, ..., -0.00762729,
         0.02134836, -0.02343766]),
 array([-0.0118101 , -0.02070978, -0.00837419, ..., -0.02578954,
        -0.00532229,  0.00094656]),
 array([-0.0213339 , -0.01454019, -0.01434688, ..., -0.01318698,
         0.00468103, -0.02636014]),
 array([-0.01511211, -0.00461573,  0.00637459, ..., -0.01443126,
         0.00569708, -0.03665888]),
 array([ 0.00223141,  0.00217764, -0.01521973, ..., -0.00585447,
        -0.0021808 , -0.00579438]),
 array([-0.01545995, -0.00356251,  0.00169975, ...,  0.00565296,
        -0.00338943, -0.01119838]),
 array([ 0.01596594,  0.00276494, -0.01791051, ..., -0.00250427,
        -0.00463434, -0.01560773]),
 array([-6.05609082e-03,  1.66074806e-05,  7.05936877e-03, ...,
        -2.18006019e-02,  1.18804015e-02, -1.23240948e-02]),
 array([-0.00277157, -0.02102409, -0.00694497, ...,  0.01148488,
         0.00978917, -0.00395553]),
 array([-0.03638232, -0.02126257, -0.00383229, ..., -0.00864883,
        -0.00093626, -0.01192268]),
 array([-0.01189155, -0.00186278,  0.01700592, ..., -0.0225108 ,
         0.01540611, -0.02788971]),
 array([-0.00699297, -0.01053541,  0.00916369, ..., -0.01188592,
        -0.00437326, -0.00897985]),
 array([-0.02460842, -0.01511641, -0.03613255, ..., -0.02202565,
        -0.01329405, -0.02994439])]

In [72]:
# chats.drop(columns=["level_0"	,"index"],inplace=True)
chats.reset_index(inplace=True, drop=True)

rnd = round(len(chats) * 0.6)
print(rnd, len(chats))
labeled_chats = chats
# rnd
labeled_chats.loc[0:rnd, "pred"] = 1
labeled_chats.loc[rnd + 1 : len(chats) - 1, "pred"] = 0
# labeled_chats.head(3)
# chats

74 123

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

### Make infreneces

In [76]:
# pd.DataFrame({"BUY":[],"CHECK":[],"IRRELEVENT":[]})

In [172]:
reg = norm("\؟\|\?|بررسی|تحلیل").replace(" ", "")

# chats["text"].str.contains(reg, regex=True)
# labeled_chats["chat_id"](["71334"])
# labeled_chats[labeled_chats["reply_to_message_id"]==71331]
# labeled_chats[labeled_chats["reply_to_message_id"].isin([71331])]
# ["chat_id"](["71334"])
x = [1, 2, 3]
x.extend([2, 1])
x
# if["2"]:
#     print(1)
# tx="<IKCO1> و سحاد به احتمال زیاد صف خرید بشند ...	"
# rep=re.sub(rf"\bسحاد\b", f"<سحاد>", tx)
# rep
# re.findall(r"<[آا-ی\s]*>",rep )
# chats["text"].str.replace(r"<[آا-ی\s]*>", '<hi>', regex=True)
# re.findall(, tx)
# labeled_chats.drop(columns=["embedding"]).to_clipboard(sep=',')
# token_count("""",,"<BORS1> <KALA1> پیشنهاد افزایش سرمایه از دو محل سود انباشته و اندوخته داد
# <BORS1> <KALA1> از پیشنهاد هیات مدیره مبنی بر افزایش سرمایه 64 درصدی از دو محل سود انباشته و اندوخته خبر داد .
#  به گزارش پایگاه خبری <BORS1> پرس ، <BORS1> <KALA1> از برنامه افزایش سرمایه 64 درصدی از دو محل سود انباشته و اندوخته خبر داد .
#  بر اساس این گزارش ، "" <KALA1> "" در نظر دارد سرمایه فعلی را از 830 میلیارد به 1.36 هزار میلیارد تومان برساند . تامین مالی این شرکت در صورت موافقت از دو محل سود انباشته و سایر اندوخته‌ها به منظور الزام اجرای مصوبه هیات مدیره سازمان <BORS1> اعمال خواهد شد",گروه هزار تحلیل,1.0""")

[1, 2, 3, 2, 1]

In [31]:
pred=pd.read_csv("../../pred_chats.csv")
pred

,chat_id,person_id,org_text,date,reply_to_message_id,text,channel_name,embedding,pred
0,80800,5968334447,دنبال سهامی برید که ورود پول سنگین دارن\n\nمثل...,2023-05-28 04:16:09+00:00,48994.0,دنبال سهامی برید که ورود پول سنگین دارن\nمثل <...,smartboursegroup,[-0.009290884248912334 -0.0005007163854315877 ...,IRRELEVENT
1,80803,535558599,**#خزامیا**\n**#گزارش_فعالیت_ماهانه** **#دوره_...,2023-05-28 04:28:29+00:00,40302.0,** <خزامیا> **\n ** گزارش _ فعالیت _ ماهانه **...,smartboursegroup,[-0.019822005182504654 -0.016292426735162735 -...,BUY
2,80808,331083198,من با nav #واعتبار مشکل دارم چونکه قیمت سهم ب...,2023-05-28 05:20:58+00:00,80554.0,من با nav <واعتبار> مشکل دارم چونکه قیمت سهم ب...,smartboursegroup,[-0.006368598900735378 -0.019390957430005074 -...,IRRELEVENT
3,80809,640353386,#خاور هم مثل زامیاد فروش خاصی را زد و اردیبهشت...,2023-05-28 05:12:02+00:00,40302.0,<خاور> هم مثل زامیاد فروش خاصی را زد و اردیبهش...,smartboursegroup,[-0.029978256672620773 -0.014238354749977589 0...,BUY
4,80810,640353386,یه گزارش عالی دیگه از خودرویی ها👍,2023-05-28 05:37:17+00:00,80809.0,یه گزارش عالی دیگه از خودرویی ها,smartboursegroup,[-0.01432543434202671 0.011671598069369793 -0....,IRRELEVENT
5,80813,5242220299,#خاور\n#گزارش_فعالیت_ماهانه #دوره_1_ماهه **منت...,2023-05-28 05:32:31+00:00,40302.0,<خاور>\nگزارش _ فعالیت _ ماهانه دوره _ 1 _ ماه...,smartboursegroup,[-0.019530076533555984 -0.009085151366889477 -...,IRRELEVENT
6,80814,5242220299,#خساپا و حمایت مهم 310,2023-05-28 05:40:03+00:00,79998.0,<خساپا> و حمایت مهم 310,smartboursegroup,[-0.0078115384094417095 -0.006949529517441988 ...,IRRELEVENT
7,80815,5632416119,گند اصلی رو‌همین خساپا میزنه 😔,2023-05-28 05:41:27+00:00,40302.0,گند اصلی رو‌همین <خساپا> میزنه,smartboursegroup,[-0.008769921027123928 0.017339615151286125 0....,IRRELEVENT
8,80816,640353386,خمحرکه \nحمایت اول ۱۱۵۰۰ ریال,2023-05-28 05:42:39+00:00,40302.0,<خمحرکه> \nحمایت اول 11500 ریال,smartboursegroup,[-0.000292203389108181 -0.007439407519996166 -...,BUY
9,80817,5242220299,اون روزایی که همه میگفتن #خساپا یه تنه جلو باز...,2023-05-28 05:42:41+00:00,80815.0,اون روزایی که همه میگفتن <خساپا> یه تنه جلو با...,smartboursegroup,[-0.022523989900946617 0.001321359071880579 0....,IRRELEVENT
10,80818,5395869556,والا همینم از دست میده امروز,2023-05-28 05:42:49+00:00,80814.0,والا همینم از دست میده امروز,smartboursegroup,[-0.03116188943386078 0.0011326685780659318 -0...,IRRELEVENT
11,80820,5632416119,بهش میاد,2023-05-28 05:43:08+00:00,80818.0,بهش میاد,smartboursegroup,[-0.013092337176203728 -0.006094708573073149 -...,IRRELEVENT
12,80822,5242220299,امروز از دست نمیره رو همین محدوده برمیگرده احت...,2023-05-28 05:43:50+00:00,80818.0,امروز از دست نمیره رو همین محدوده برمیگرده احت...,smartboursegroup,[-0.015006573870778084 -0.008380980230867863 0...,IRRELEVENT
13,80823,5395869556,مگه میشه اخه بازار به دو تا سهم مسخره گره بخوره,2023-05-28 05:44:03+00:00,80820.0,مگه میشه اخه بازار به دو تا سهم مسخره گره بخوره,smartboursegroup,[-0.009922691620886326 -0.016414353623986244 0...,IRRELEVENT
14,80825,5395869556,والا بخدا,2023-05-28 05:44:23+00:00,80820.0,والا بخدا,smartboursegroup,[-0.01088112872093916 -0.003611775813624263 -0...,IRRELEVENT
15,80827,5681723072,خساپا و خودرو هم چي رو خراب كردن,2023-05-28 05:44:32+00:00,40302.0,<خساپا> و <خودرو> هم چی رو خراب کردن,smartboursegroup,[-0.00468277046456933 0.0017013181932270527 0....,BUY
16,80829,5395869556,و اینجور ک پیش میره میشه,2023-05-28 05:45:14+00:00,80822.0,و اینجور ک پیش میره میشه,smartboursegroup,[-0.004647191613912582 -0.013772699981927872 -...,IRRELEVENT
17,80835,5242220299,احتمالش کمه از دست بره، باید منتظر بمونیم,2023-05-28 05:46:54+00:00,80829.0,احتمالش کمه از دست بره ، باید منتظر بمونیم,smartboursegroup,[-0.018268991261720657 -0.021074678748846054 0...,IRRELEVENT
18,80839,5395869556,نظاره گریم فعلا,2023-05-28 05:47:26+00:00,80835.0,نظاره گریم فعلا,smartboursegroup,[-0.008088121190667152 0.006877563428133726 -0...,IRRELEVENT
19,80843,80992556,خساپا از همین محدوده بر میگرده شک نکنید,2023-05-28 05:48:54+00:00,40302.0,<خساپا> از همین محدوده بر میگرده شک نکنید,smartboursegroup,[-0.0004967441200278699 -0.007762300316244364 ...,IRRELEVENT
20,80844,5632416119,بازی ، همینه,2023-05-28 05:48:20+00:00,80843.0,بازی ، همینه,smartboursegroup,[-0.019838523119688034 -0.02237674407660961 -0...,IRRELEVENT
21,80852,640353386,گزارشهای دو ماه خمحرکه هنوز ارسال نشده \nبعید ...,2023-05-28 05:50:11+00:00,80842.0,گزارشهای دو ماه <خمحرکه> هنوز ارسال‌نشده‌\nبعی...,smartboursegroup,[-0.016882607713341713 -0.01816568523645401 -0...,IRRELEVENT
22,80858,5681723072,خساپا صف فروش ٢٨ ميليوني,2023-05-28 05:54:43+00:00,40302.0,<خساپا> صف فروش 28 میلیونی,smartboursegroup,[-0.019847726449370384 -0.008445410057902336 -...,IRRELEVENT
23,80868,5681723072,اين صف خساپا دو روز طول ميكشه تخليه بشه,2023-05-28 06:09:50+00:00,40302.0,این صف <خساپا> دو روز طول میکشه تخلیه بشه,smartboursegroup,[-0.019501620903611183 0.0022625382989645004 0...,IRRELEVENT
24,80869,68282650,اول گفتن بخاطر سر رسید اعتبار خودرو عه\nدیروزم...,2023-05-28 06:05:31+00:00,40302.0,اول گفتن بخاطر سر رسید اعتبار <خودرو> عه\nدیرو...,smartboursegroup,[0.0009673517779447138 -0.0046892547979950905 ...,IRRELEVENT
25,80871,80992556,کل صف خساپا خود حقوقی گذاشته,2023-05-28 05:58:14+00:00,40302.0,کل صف <خساپا> خود حقوقی گذاشته,smartboursegroup,[-0.011834324337542057 -0.0077745672315359116 ...,IRRELEVENT
26,80873,5395869556,از کجا معلومه ؟,2023-05-28 05:58:37+00:00,80871.0,از کجا معلومه ؟,smartboursegroup,[0.005346603691577911 0.0005727375391870737 -0...,IRRELEVENT
27,80875,68282650,ولمون کن بابا,2023-05-28 06:05:42+00:00,80871.0,ولمون کن بابا,smartboursegroup,[-0.0007598946685902774 -0.007326932158321142 ...,IRRELEVENT
28,80876,413058452,شما به ما بگو موج منفی زمان همه چی و مشخص میکن...,2023-05-28 06:01:14+00:00,40783.0,شما به ما بگو موج منفی زمان همه چی و مشخص میکن...,smartboursegroup,[-0.006454362068325281 -0.005230879411101341 0...,IRRELEVENT
29,80880,509896159,تورمو نن جون مهدی فهمید این کوتوله نفهمید!!!\n...,2023-05-28 05:59:48+00:00,40783.0,تورمو نن جون مهدی فهمید این کوتوله نفهمید !!!\...,smartboursegroup,[-0.007653053384274244 -0.01877705752849579 0....,IRRELEVENT
30,80886,80992556,از تعداد یاد بگیر که فیکه,2023-05-28 06:00:53+00:00,80875.0,از تعداد یاد بگیر که فیکه,smartboursegroup,[-0.01073206402361393 0.012021523900330067 -0....,IRRELEVENT
31,80910,80992556,خساپا تا الان به اندازه حجم معاملات روزانه تو...,2023-05-28 06:09:10+00:00,40302.0,<خساپا> تا الان به اندازه حجم معاملات روزانه ت...,smartboursegroup,[0.0004388725501485169 0.010959634557366371 0....,IRRELEVENT
32,80911,690089289,**ظاهرا در بورس تهران:\n\nایران با امریکا تواف...,2023-05-28 11:18:44+00:00,40302.0,** ظاهرا در <بورس> تهران :\n ایران با امریکا ت...,smartboursegroup,[-0.013071171008050442 -0.02488444559276104 -0...,IRRELEVENT
33,80918,5681723072,هيچكي فكر كنم تو سازمان بورس نيست,2023-05-28 06:11:50+00:00,40302.0,هیچکی فکر کنم تو سازمان <بورس> نیست,smartboursegroup,[-0.014330409467220306 -0.004119017627090216 -...,IRRELEVENT
34,80919,6043183100,احتمالش هست یه نوسان بدن ...خساپا رو 3149 خرید...,2023-05-28 06:13:10+00:00,40302.0,احتمالش هست یه نوسان بدن ... <خساپا> رو 3149 خ...,smartboursegroup,[-0.00686722993850708 -0.003236762946471572 0....,IRRELEVENT
35,80921,115461758,میخوان نفروشیم تا بیشتر ازمون دزدی کنن..واقعا ...,2023-05-28 06:12:10+00:00,80903.0,میخوان نفروشیم تا بیشتر ازمون دزدی کنن .. واقع...,smartboursegroup,[-0.017457617446780205 0.0058137779124081135 -...,IRRELEVENT
36,80922,80992556,همه رفتن استقبال پادشاه عمان😀,2023-05-28 06:12:11+00:00,80918.0,همه رفتن استقبال پادشاه عمان,smartboursegroup,[-0.013447754085063934 -0.008394978009164333 -...,IRRELEVENT
37,80924,80992556,۳۱۴۹,2023-05-28 06:12:32+00:00,80919.0,3149,smartboursegroup,[-5.262052218313329e-05 -0.0004741516313515603...,IRRELEVENT
38,80926,6043183100,بله,2023-05-28 06:12:51+00:00,80924.0,بله,smartboursegroup,[-0.01905616745352745 -0.021471180021762848 -0...,IRRELEVENT
39,80929,152101023,ختور بنظرتون بفروشم؟,2023-05-28 06:13:23+00:00,40302.0,<ختور> بنظرتون بفروشم ؟,smartboursegroup,[-0.025721080601215363 -0.02391083724796772 -0...,IRRELEVENT
40,80932,640353386,به نظرم هیچی نفروشید,2023-05-28 06:13:54+00:00,80929.0,به نظرم هیچی نفروشید,smartboursegroup,[-0.007161842193454504 -0.007576374337077141 -...,IRRELEVENT
41,80949,6043183100,مکدی تایم روزانه برای خساپا . اون فلش رو که تو...,2023-05-28 06:21:06+00:00,80898.0,مکدی تایم روزانه برای <خساپا> . اون فلش رو که ...,smartboursegroup,[-0.015595286153256893 -0.011689811013638973 0...,IRRELEVENT
42,80953,690089289,کانال یا گروه دارین ؟؟؟,2023-05-28 06:24:36+00:00,80949.0,کانال یا گروه دارین ؟؟؟,smartboursegroup,[-0.0072318073362112045 -0.016748709604144096 ...,IRRELEVENT
43,80954,5395869556,نقطه کراس مهم نیس اون پایینش کجا ختم میشه😂,2023-05-28 06:25:48+00:00,80949.0,نقطه کراس مهم نیس اون پایینش کجا ختم میشه,smartboursegroup,[-0.006216998212039471 -0.004934333264827728 0...,IRRELEVENT
44,80955,6043183100,چطور ؟ نه ندارم ....کمک به هموطنام میکنم کمتر ...,2023-05-28 06:26:10+00:00,80953.0,چطور ؟ نه ندارم .... کمک به هموطنام میکنم کمتر...,smartboursegroup,[-0.009249689057469368 0.005349802318960428 0....,IRRELEVENT
45,80960,640353386,این روزها بازار حجم خوبی در کل نداشت و انرژی ر...,2023-05-28 06:32:06+00:00,40302.0,این روزها بازار حجم خوبی در کل نداشت و <انرژی>...,smartboursegroup,[-0.014345042407512665 -0.004057351034134626 0...,IRRELEVENT
46,80966,5395869556,جناب منصور تازه مثلا از اصلاح دراومدیم 🤔,2023-05-28 06:30:45+00:00,80960.0,جناب منصور تازه مثلا از اصلاح دراومدیم,smartboursegroup,[-0.00294599705375731 -0.007855991832911968 -0...,IRRELEVENT
47,80972,5827292508,کاما از دست رفت☹,2023-05-28 06:32:28+00:00,40246.0,<کاما> از دست رفت,smartboursegroup,[-0.029014306142926216 -0.007863009348511696 -...,IRRELEVENT
48,80977,1898661064,تا وقتی پول تزریق نشه تو بورس همینه از دیروزم ...,2023-05-28 06:33:03+00:00,40302.0,تا وقتی پول تزریق نشه تو <بورس> همینه از دیروز...,smartboursegroup,[-0.013985460624098778 -0.00859292782843113 -0...,IRRELEVENT
49,80978,951550300,خوبه دیگه پول بره جیب مافیای خودرو ک.ل تولید,2023-05-28 06:33:43+00:00,80977.0,خوبه دیگه پول بره جیب مافیای <خودرو> ک . ل تولید,smartboursegroup,[-0.01484137773513794 0.006923358887434006 -0....,IRRELEVENT
50,80980,80992556,گفتن تو رهن نیست که بتونن از فوروشش مالیات بگی...,2023-05-28 06:33:50+00:00,80977.0,گفتن تو رهن نیست که بتونن از فوروشش مالیات بگی...,smartboursegroup,[-0.016012080013751984 -0.006946416571736336 0...,IRRELEVENT
51,80982,1898661064,دو سر دارن سود میبرن هم ماشین کردن تو پاچه هم ...,2023-05-28 06:35:14+00:00,80980.0,دو سر دارن سود میبرن هم ماشین کردن تو پاچه هم ...,smartboursegroup,[-0.0009487106581218541 -0.015660222619771957 ...,IRRELEVENT
52,80983,640353386,بله درسته \nاون اصلاح تا حدود زیادی ترمیم شد \...,2023-05-28 06:43:27+00:00,80966.0,بله درسته \nاون اصلاح تا حدود زیادی ترمیم شد \...,smartboursegroup,[0.006544899195432663 0.0022205328568816185 0....,IRRELEVENT
53,80984,80992556,دوستان اپشن کار هر کس تو این قیمت اختیار شستا ...,2023-05-28 06:35:39+00:00,40302.0,دوستان اپشن کار هر کس تو این قیمت اختیار <شستا...,smartboursegroup,[-0.006006717681884766 -0.010523094795644283 0...,IRRELEVENT
54,80986,951550300,توی روند نزولی اصصصلا سمتش نرید,2023-05-28 06:40:44+00:00,80984.0,توی روند نزولی اصصصلا سمتش نرید,smartboursegroup,[0.0010363656328991055 -0.008062116801738739 0...,IRRELEVENT
55,80987,80992556,درسته ولی خود سهم اصلیش تو قیمت ۱۳۵ تا ۱۴۰ خود...,2023-05-28 06:40:37+00:00,80986.0,درسته ولی خود سهم اصلیش تو قیمت 135 تا 140 خود...,smartboursegroup,[0.002752967644482851 0.006882418878376484 0.0...,IRRELEVENT
56,80988,951550300,شیشه میکشی؟,2023-05-28 06:40:43+00:00,80983.0,شیشه میکشی ؟,smartboursegroup,[0.005130348261445761 -0.011008872650563717 -0...,IRRELEVENT
57,80989,640353386,فقط گاهی سیگار,2023-05-28 06:41:47+00:00,80988.0,فقط گاهی سیگار,smartboursegroup,[-0.014197718352079391 0.0034992964938282967 0...,IRRELEVENT
58,80990,951550300,از کجا معلوم نگه داره بازم,2023-05-28 06:41:52+00:00,80987.0,از کجا معلوم نگه داره بازم,smartboursegroup,[-0.006207152735441923 -0.00894701573997736 -0...,IRRELEVENT
59,80991,951550300,این توهم سیگار نیس توهم شیشه اس,2023-05-28 06:42:20+00:00,80989.0,این توهم سیگار نیس توهم شیشه اس,smartboursegroup,[1.9398125004954636e-05 -0.0021990523673594 -0...,IRRELEVENT
60,80992,640353386,اشکال نداره \nشما درست میفرمایید,2023-05-28 06:42:43+00:00,80991.0,اشکال نداره \nشما درست میفرمایید,smartboursegroup,[0.016069384291768074 0.007795602083206177 0.0...,IRRELEVENT
61,80997,951550300,مگه اعتماد سرمایه گذار به این راحتی برمیگرده؟؟...,2023-05-28 06:44:14+00:00,80992.0,مگه اعتماد سرمایه‌گذار به این راحتی برمیگرده ؟...,smartboursegroup,[-0.005191185977309942 -0.006038134917616844 0...,IRRELEVENT
62,80999,640353386,نظرتون محترمه 🙏,2023-05-28 06:44:41+00:00,80997.0,نظرتون محترمه,smartboursegroup,[0.0031271660700440407 -0.016392899677157402 -...,IRRELEVENT
63,81027,68282650,پشمام\nباورم نمیشه همچین چیز ریسکی رو اینجوری ...,2023-05-28 06:51:48+00:00,80984.0,پشمام\nباورم نمیشه همچین چیز ریسکی رو اینجوری ...,smartboursegroup,[-0.018257662653923035 -0.01096736453473568 -0...,IRRELEVENT
64,81044,1335308611,🎺🎺🎺🎺با پرچمداری #خزامیا\nشاخص گروه خودرو وقطعا...,2023-05-28 12:58:59+00:00,40302.0,با پرچمداری <خزامیا>\nشاخص گروه <خودرو> وقطعات...,smartboursegroup,[-0.024201547726988792 -0.013240651227533817 -...,BUY
65,81045,1335308611,جدی بگیرید,2023-05-28 06:54:18+00:00,81044.0,جدی بگیرید,smartboursegroup,[-0.0057711233384907246 0.009433439932763577 -...,IRRELEVENT
66,81049,951550300,میخوام جدی بگیرما ولی هی خندم میگیره 🤭,2023-05-28 07:03:38+00:00,81045.0,میخوام جدی بگیرما ولی هی خندم میگیره,smartboursegroup,[-0.025117997080087662 0.004951204173266888 -0...,IRRELEVENT
67,81050,5632416119,عالی بود 😅😅😅😅😅😅,2023-05-28 06:55:35+00:00,81049.0,عالی بود,smartboursegroup,[-0.01065484993159771 0.00482929265126586 0.00...,IRRELEVENT
68,81054,1671623706,هم بگه موشک دارم و قدرت ...هم ناتوانی خودشو تو...,2023-05-28 06:56:24+00:00,40302.0,هم بگه موشک دارم و قدرت ... هم ناتوانی خودشو ت...,smartboursegroup,[-0.02351897768676281 -0.01927446573972702 0.0...,IRRELEVENT
69,81055,115461758,داداش الان بازار بورس ایران با باخموت اوکراین ...,2023-05-28 06:56:48+00:00,81044.0,داداش الان بازار <بورس> ایران با باخموت اوکرای...,smartboursegroup,[-0.009383436292409897 0.0060559045523405075 0...,IRRELEVENT
70,81058,1335308611,اتفاقا وقتی همه می‌ترسند تو طمع کن,2023-05-28 06:57:18+00:00,81055.0,اتفاقا وقتی همه می‌ترسند تو طمع کن,smartboursegroup,[-0.014597831293940544 -0.00814914796501398 0....,IRRELEVENT
71,81059,951550300,استاد رائفی پور نقابتو بردار بگو که خودتی,2023-05-28 06:57:45+00:00,81054.0,استاد رائفی پور نقابتو بردار بگو که خودتی,smartboursegroup,[-0.0058252629823982716 5.4953357903286815e-05...,IRRELEVENT
72,81061,951550300,باشه,2023-05-28 06:57:53+00:00,81058.0,باشه,smartboursegroup,[-0.016175899654626846 -0.024130428209900856 -...,IRRELEVENT
73,81062,1671623706,کلمات فیلتری ..تو چشم رائفی پور🤣,2023-05-28 06:58:16+00:00,81059.0,کلمات فیلتری .. تو چشم رائفی پور,smartboursegroup,[0.010355235077440739 -0.00698029575869441 -0....,IRRELEVENT
74,81067,79308672,سلام استاد لطفا لطفا حمایت های بعدی فپنتا,2023-05-28 06:59:02+00:00,40246.0,سلام استاد لطفا لطفا حمایت‌های بعدی <فپنتا>,smartboursegroup,[-0.03605806082487106 0.002820811700075865 -0....,IRRELEVENT
75,81071,115461758,ولی با این صف فروشی که همه بازار بسته فردا هم ...,2023-05-28 06:59:47+00:00,81058.0,ولی با این صف فروشی که همه بازار بسته فردا هم ...,smartboursegroup,[-0.021837487816810608 -0.010892481543123722 -...,IRRELEVENT
76,81078,951550300,نه فردا از نیمه ی دوم برمیگرده عمو اسمارت بورس...,2023-05-28 07:00:41+00:00,81071.0,نه فردا از نیمه ی دوم برمیگرده عمو اسمارت <بور...,smartboursegroup,[-0.022695790976285934 -0.004882772918790579 -...,IRRELEVENT
77,81081,1671623706,بازار از پارسال تا الان ۳دفعه سود داده ..دوبلش...,2023-05-28 07:03:54+00:00,40302.0,بازار از پارسال تا الان 3دفعه سود داده .. دوبل...,smartboursegroup,[-0.019855227321386337 0.0010309572098776698 -...,IRRELEVENT
78,81084,5632416119,دیگه مهم نیست \n\nبورس کار خودشو کرد 😅😅😅,2023-05-28 07:02:52+00:00,81083.0,دیگه مهم نیست \n<بورس> کار خودشو کرد,smartboursegroup,[-0.013309436850249767 0.0029980468098074198 0...,IRRELEVENT
79,81087,80992556,طالبان دارن با تانک تو بازار بورس میچرخن همه ف...,2023-05-28 07:03:53+00:00,81084.0,طالبان دارن با تانک تو بازار <بورس> میچرخن همه...,smartboursegroup,[-0.02162979170680046 -0.013024462386965752 -0...,IRRELEVENT
80,81088,281541484,بورس دار دیه اون ۱۸ نفر رو میده,2023-05-28 07:04:34+00:00,40302.0,<بورس>‌دار دیه اون 18 نفر رو میده,smartboursegroup,[-0.02991745062172413 -0.008234784938395023 0....,IRRELEVENT
81,81089,80992556,دیه ندارن همشون یکی یک جفت دمپایی داشتن😀چجوری ...,2023-05-28 07:05:34+00:00,81088.0,دیه ندارن همشون یکی یک جفت دمپایی داشتنچجوری ب...,smartboursegroup,[-0.015436690300703049 -0.0051951645873487 0.0...,IRRELEVENT
82,81090,1898661064,برای همدردی با برادران افغانستانی این کارو کرد...,2023-05-28 07:05:18+00:00,81087.0,برای همدردی با برادران افغانستانی این کارو کرد...,smartboursegroup,[-0.018613070249557495 -0.009428231045603752 -...,IRRELEVENT
83,81091,1275940942,آدم تحلیل های اسمارت بورس را که می‌بینه واقعا ...,2023-05-28 07:08:05+00:00,40783.0,آدم تحلیل‌های اسمارت <بورس> را که می‌بینه واقع...,smartboursegroup,[-0.011042890138924122 -0.0023815673775970936 ...,IRRELEVENT
84,81094,951550300,۱۸ تا اب طالبی مهمون کردیم برادران رو,2023-05-28 07:06:19+00:00,81088.0,18 تا اب طالبی مهمون کردیم برادران رو,smartboursegroup,[-0.00866519846022129 -0.006741771940141916 -0...,IRRELEVENT
85,81097,80992556,اخه طالبی سبزه من نمیدونم چرا قرمز شد طبق تحل...,2023-05-28 07:07:04+00:00,81094.0,اخه طالبی سبزه من نمیدونم چرا قرمز شد طبق تحلی...,smartboursegroup,[-0.008620521984994411 -0.025383364409208298 0...,IRRELEVENT
86,81107,407745591,اگه برای ۴تا ترقه بازی با طالبان بورس ب چوخ رف...,2023-05-28 07:09:38+00:00,40783.0,اگه برای 4تا ترقه بازی با طالبان <بورس> ب چوخ ...,smartboursegroup,[-0.03352642431855202 -0.004546124953776598 -0...,IRRELEVENT
87,81109,389665592,تو این ترقه بازی ادم کشته شده😬,2023-05-28 07:14:28+00:00,81107.0,تو این ترقه بازی ادم کشته شده,smartboursegroup,[-0.020924227312207222 -0.01580391451716423 -0...,IRRELEVENT
88,81112,5827292508,حمایت کاما تو چه قیمتیه؟؟؟؟,2023-05-28 07:11:03+00:00,40246.0,حمایت <کاما> تو چه قیمتیه ؟؟؟؟,smartboursegroup,[0.006527826189994812 -0.0157720185816288 -0.0...,IRRELEVENT
89,81118,488053274,قشرین,2023-05-28 07:13:17+00:00,81114.0,<قشرین>,smartboursegroup,[-0.027845017611980438 -0.011170999146997929 -...,BUY
90,81119,389665592,اوووو 😂😂 قشرین؟,2023-05-28 07:12:27+00:00,81116.0,اوووو <قشرین> ؟,smartboursegroup,[-0.010573582723736763 -0.028924694284796715 -...,IRRELEVENT
91,81121,389665592,به اقای حسینی افتخار دادین به گروه,2023-05-28 07:12:51+00:00,81118.0,به اقای حسینی افتخار دادین به گروه,smartboursegroup,[-0.00441996892914176 -0.0035116635262966156 -...,IRRELEVENT
92,81125,57500011,خزامیا بخرید تا رستگار شوید,2023-05-28 07:13:48+00:00,40302.0,<خزامیا> بخرید تا رستگار شوید,smartboursegroup,[0.007576258387416601 -0.012001861818134785 -0...,BUY
93,81130,407745591,هر روز تو این مملکت آدما دارن کشته میشن فقط بی...,2023-05-28 07:15:12+00:00,81109.0,هر روز تو این مملکت آدما دارن کشته میشن فقط بی...,smartboursegroup,[-0.0008586401818320155 -0.009028901346027851 ...,IRRELEVENT
94,81131,1348305097,این منفی خوردنای الکی بازار رو ازش استقبال میک...,2023-05-28 07:15:18+00:00,40783.0,این منفی خوردنای الکی بازار رو ازش استقبال میک...,smartboursegroup,[-0.029332904145121574 -0.018854942172765732 0...,IRRELEVENT
95,81145,389665592,اونا که فدا سر نظام😏 فقط موندم این گردن کلفتای...,2023-05-28 07:17:32+00:00,81130.0,اونا که فدا سر نظام فقط موندم این گردن کلفتای ...,smartboursegroup,[-0.010067111812531948 -0.01124326977878809 -0...,IRRELEVENT
96,81154,5753606911,#بخاور همچنان فرصت خرید\n\nاین سهم مثل #واعتبا...,2023-05-28 07:18:45+00:00,40207.0,بخاور همچنان فرصت خرید\nاین سهم مثل <واعتبار> ...,smartboursegroup,[-0.00359554635360837 -0.017865577712655067 0....,IRRELEVENT

In [32]:
votes = {}
communities = labeled_chats["channel_name"].unique()  ##Telegram groups and channels
for com in communities:
    com_chats = labeled_chats[labeled_chats["channel_name"] == com]
    votes[com] = {}
    print("****", com)
    for index, row in com_chats.iterrows():
        stock_interface = {
            "BUY": set(),
            "CHECK": set(),
            "IRRELEVENT": set(),
            "SELL": set(),
        }
        included_stocks = re.findall(r"<([ا-ی]*)>", row["text"])
        print("*_ORG_>", list(set(included_stocks)))
        # if row["text"].str.contains('بررسی|تحلیل|?|؟', regex=True)
        if row["reply_to_message_id"]:
            if row["reply_to_message_id"]:
                # com_chats[]
                replied_from_filter = labeled_chats["reply_to_message_id"].isin(
                    [row["reply_to_message_id"]]
                )
                print(
                    'row["reply_to_message_id"],',
                    len(labeled_chats[replied_from_filter]),
                    labeled_chats[replied_from_filter]["text"],
                )
                replied_from_stocks = re.findall(
                    r"<([ا-ی]*)>", labeled_chats[replied_from_filter]["text"]
                )
                included_stocks.extend(replied_from_stocks)
                print("*_EXTEND_ORG_>", included_stocks)
                # print("reply_to_message_id", row["reply_to_message_id"])
        for stock in list(set(included_stocks)):
            votes[com][stock] = (
                votes[com][stock] if (stock in votes[com]) else stock_interface
            )
            print("\t", stock)
            if row["pred"] == "BUY":
                votes[com][stock]["BUY"].add(row["chat_id"])
            if row["pred"] == "SELL":
                votes[com][stock]["SELL"].add(row["chat_id"])
                # print("\t", "[buy]])", votes[com][stock]["buy"])
            elif row["pred"] == "CHECK":
                votes[com][stock]["CHECK"].add(row["chat_id"])
            elif row["pred"] == "IRRELEVENT":
                votes[com][stock]["IRRELEVENT"].add(row["chat_id"])
                # print("\t", "[sell]])", votes[com][stock]["sell"])
            print("\t", votes[com][stock])

NameError: name 'labeled_chats' is not defined

In [ ]:
def handle_votes(labeled_chats):
    votes = {}
    # votes_df = pd.DataFrame(
    #     columns=["chanell_name", "stock", "BUY", "SELL", "CHECK", "IRRELEVENT"],
    # # )
    # votes_df.loc[0] = np.nan
    # votes_df.set_index(["chanell_name", "stock"],inplace=True)

    communities = labeled_chats["channel_name"].unique()  ##Telegram groups and channels
    for com in communities:
        com_chats = labeled_chats[labeled_chats["channel_name"] == com]
        votes[com] = {}
        # com_votes = pd.DataFrame()
        print("****", com)
        for _, row in com_chats.iterrows():
            stock_interface = {
                "BUY": set(),
                "CHECK": set(),
                "IRRELEVENT": set(),
                "SELL": set(),
            }
            included_stocks = re.findall(r"<([ا-ی]*)>", row["text"])
            print("*_ORG_>", list(set(included_stocks)))
            # if row["text"].str.contains('بررسی|تحلیل|?|؟', regex=True)
            if row["reply_to_message_id"]:
                # com_chats[]
                replied_from_filter = labeled_chats["reply_to_message_id"].isin(
                    [row["reply_to_message_id"]]
                )
                print(
                    'row["reply_to_message_id"],',
                    len(labeled_chats[replied_from_filter]),
                    labeled_chats[replied_from_filter]["text"],
                )
                replied_from_stocks = re.findall(
                    r"<([ا-ی]*)>", str(labeled_chats[replied_from_filter]["text"])
                )
                included_stocks.extend(replied_from_stocks)
                print("*_EXTEND_ORG_>", included_stocks)
                # print("reply_to_message_id", row["reply_to_message_id"])

            for stock in list(set(included_stocks)):
                votes[com][stock] = (
                    votes[com][stock] if (stock in votes[com]) else stock_interface
                )
                stock_interface = {
                    "BUY": set(),
                    "CHECK": set(),
                    "IRRELEVENT": set(),
                    "SELL": set(),
                }
                # inital_stock = pd.Series(
                #     {
                #         "chanell_name": com,
                #         "stock": stock,
                #         "BUY": 0,
                #         "SELL": 0,
                #         "CHECK": 0,
                #         "IRRELEVENT": 0,
                #     }
                # )

                # try:
                #     # pass
                #     votes_df.loc[(com, stock), :] = (
                #         votes_df.loc[(com, stock), :]
                #         if (votes_df.loc[(com, stock), :])
                #         else inital_stock
                #     )
                #     # votes_df.loc[(com,stock), :] = (
                #     # votes_df.loc[(com,stock), :] if (votes_df.loc[(com,stock), :]) else inital_stock
                # # )
                # except:
                #     votes_df.reset_index(inplace=True)
                #     votes_df = votes_df.append(inital_stock, ignore_index=True)
                #     votes_df.set_index(["chanell_name", "stock"],inplace=True)

                # pd.concat([])
                print("\t", stock)
                # repeated_stock_count = len(included_stocks)
                # stock_filter =
                if row["pred"] == "BUY":
                    votes[com][stock]["BUY"].add(row["chat_id"])
                    # votes_df.loc[(com, stock), "BUY"] += repeated_stock_count
                if row["pred"] == "SELL":
                    votes[com][stock]["SELL"].add(row["chat_id"])
                    # votes_df.loc[(com, stock), "SELL"] += repeated_stock_count
                    # print("\t", "[buy]])", votes[com][stock]["buy"])
                elif row["pred"] == "CHECK":
                    votes[com][stock]["CHECK"].add(row["chat_id"])
                    # votes_df.loc[(com, stock), "CHECK"] += repeated_stock_count
                elif row["pred"] == "IRRELEVENT":
                    votes[com][stock]["IRRELEVENT"].add(row["chat_id"])
                    # votes_df.loc[(com, stock), "IRRELEVENT"] += repeated_stock_count
                    # print("\t", "[sell]])", votes[com][stock]["sell"])
                # print("\t", votes_df.loc[(com, stock),:])
    print(votes)
    return votes
    # print(com_chats["channel_name"].unique())

In [127]:
votes

{'گروه هزار تحلیل': {'ملت': {'buy': {361027,
    361050,
    361062,
    361071,
    361083,
    361086,
    361088,
    361092,
    361113,
    361143,
    361157,
    361171,
    361180,
    361183,
    361184,
    361191,
    361198,
    361223,
    361263,
    361278,
    361279,
    361285,
    361289,
    361295,
    361311},
   'sell': set(),
   'attention': set()},
  'خودرو': {'buy': {361027,
    361050,
    361062,
    361071,
    361083,
    361086,
    361088,
    361092,
    361113,
    361143,
    361157,
    361171,
    361180,
    361183,
    361184,
    361191,
    361198,
    361223,
    361263,
    361278,
    361279,
    361285,
    361289,
    361295,
    361311},
   'sell': set(),
   'attention': set()},
  'بورس': {'buy': {361043,
    361051,
    361053,
    361058,
    361061,
    361062,
    361080,
    361102,
    361108,
    361113,
    361130,
    361132,
    361143,
    361155,
    361162,
    361177,
    361179,
    361206,
    361210,
    361223,
    361234,
    361256,
    361257,
    361279,
    361280,
    361284,
    361295,
    361299,
    361306},
   'sell': set(),
   'attention': set()},
  'کالا': {'buy': {361043,
    361051,
    361053,
    361058,
    361061,
    361062,
    361080,
    361102,
    361108,
    361113,
    361130,
    361132,
    361143,
    361155,
    361162,
    361177,
    361179,
    361206,
    361210,
    361223,
    361234,
    361256,
    361257,
    361279,
    361280,
    361284,
    361295,
    361299,
    361306},
   'sell': set(),
   'attention': set()},
  'خساپا': {'buy': {361050, 361083, 361131, 361157, 361211, 361254, 361278},
   'sell': set(),
   'attention': set()},
  'وخارزم': {'buy': {361052, 361054, 361055},
   'sell': set(),
   'attention': set()},
  'وتجارت': {'buy': {361055}, 'sell': set(), 'attention': set()},
  'حپترو': {'buy': {361080}, 'sell': set(), 'attention': set()},
  'خاور': {'buy': {361083, 361131, 361157, 361211, 361278},
   'sell': set(),
   'attention': set()},
  'شستا': {'buy': {361083, 361131, 361157, 361211, 361278},
   'sell': set(),
   'attention': set()},
  'دکوثر': {'buy': {361097}, 'sell': set(), 'attention': set()},
  'ثشاهد': {'buy': {361106}, 'sell': set(), 'attention': set()},
  'ددام': {'buy': {361107}, 'sell': set(), 'attention': set()},
  'تپکو': {'buy': {361116}, 'sell': set(), 'attention': set()},
  'پارسیان': {'buy': {361117}, 'sell': set(), 'attention': set()},
  'قشکر': {'buy': {361125}, 'sell': set(), 'attention': set()},
  'برکت': {'buy': {361127, 361156}, 'sell': set(), 'attention': set()},
  'وپارس': {'buy': {361131}, 'sell': set(), 'attention': set()},
  'کساپا': {'buy': {361132, 361242}, 'sell': set(), 'attention': set()},
  'پرداخت': {'buy': {361152, 361206}, 'sell': set(), 'attention': set()},
  'وبملت': {'buy': {361157}, 'sell': set(), 'attention': set()},
  'وبصادر': {'buy': {361157}, 'sell': set(), 'attention': set()},
  'تکنو': {'buy': {361166}, 'sell': set(), 'attention': set()},
  'پارس': {'buy': {361180}, 'sell': set(), 'attention': set()},
  'دارو': {'buy': {361181, 361249}, 'sell': set(), 'attention': set()},
  'امید': {'buy': {361183, 361221, 361223}, 'sell': set(), 'attention': set()},
  'وکار': {'buy': {361211}, 'sell': set(), 'attention': set()},
  'امین': {'buy': {361223, 361285}, 'sell': set(), 'attention': set()},
  'چکارن': {'buy': {361235}, 'sell': set(), 'attention': set()},
  'چکاپا': {'buy': {361236}, 'sell': set(), 'attention': set()},
  'شبندر': {'buy': {361239, 361246, 361288},
   'sell': set(),
   'attention': set()},
  'شپدیس': {'buy': {361240}, 'sell': set(), 'attention': set()},
  'خگستر': {'buy': {361241}, 'sell': set(), 'attention': set()},
  'خپارس': {'buy': {361254}, 'sell': set(), 'attention': set()},
  'خزامیا': {'buy': {361254}, 'sell': set(), 'attention': set()},
  'میدکو': {'buy': {361261}, 'sell': set(), 'attention': set()},
  'کگاز': {'buy': {361306}, 'sell': set(), 'attention': set()}},
 'گروه بازار': {'همراه': {'buy': {751441}, 'sell': set(), 'attention': set()},
  'فلامی': {'buy': {751447, 751493}, 'sell': set(), 'attention': set()},
  'حتاید': {'buy': {751447, 751493}, 'sell': set(), 'attention': set()},
  'کترام': {'buy': {751458}, 'sell': set(), 'attention': set()},
  'بورس': {'buy': {751462, 751476, 751480}, 'sell': set(), 'attention': set()},
  'شفا': {'buy': {751467}, 'sell': set(), 'attention': set()},
  'خودرو': {'buy': {751505}, 'sell': set(), 'attention': set()}},
 'بورسگرام | Boursegram': {'شستا': {'buy': {71138},
   'sell': set(),
   'attention': set()},
  'بورس': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'ختور': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خگستر': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خمحرکه': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خساپا': {'buy': {71156}, 'sell': {71232, 71233, 71245}, 'attention': set()},
  'کماسه': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'دامین': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'سپید': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'حکشتی': {'buy': set(),
   'sell': {71170, 71171, 71174, 71175, 71176},
   'attention': set()},
  'خزامیا': {'buy': set(),
   'sell': {71170, 71171, 71174, 71175, 71176},
   'attention': set()},
  'خودرو': {'buy': set(),
   'sell': {71173, 71176, 71242, 71245, 71276},
   'attention': set()},
  'دزهراوی': {'buy': set(), 'sell': {71186}, 'attention': set()},
  'غبهنوش': {'buy': set(),
   'sell': {71188, 71191, 71204, 71220},
   'attention': set()},
  'غزر': {'buy': set(), 'sell': {71196}, 'attention': set()},
  'امید': {'buy': set(), 'sell': {71227}, 'attention': set()},
  'فاراک': {'buy': set(), 'sell': {71306}, 'attention': set()},
  'کرازیح': {'buy': set(), 'sell': {71308}, 'attention': set()},
  'خپارس': {'buy': set(), 'sell': {71317}, 'attention': set()},
  'خنصیر': {'buy': set(), 'sell': {71323}, 'attention': set()},
  'کالا': {'buy': set(), 'sell': {71326}, 'attention': set()}}}

In [202]:
# # @ BOUNDS : []
# # chat_list
# telegram_chanells = [chat_list_2, chat_list_2]

# channels_limit_bound = []
# for chanell in telegram_chanells:
#     chanell_bound = []
#     token_count = 0
#     i = 0
#     while i < len(chanell):
#         chat = chanell[i]
#         chat_tokens_count = len(enc.encode(chat["text"]))
#         # print(i)
#         if token_count + chat_tokens_count > 8192 :
#             # print(i,len(chanell),chat_tokens_count,token_count,token_count + chat_tokens_count > 4096,i + 1 == len(chanell),)

#             chanell_bound.append(i - 1)
#             token_count = 0
#         elif i + 1 == len(chanell):
#             chanell_bound.append(i)
#             token_count = 0
#             i += 1
#         else:
#             token_count += chat_tokens_count
#             i += 1
#     channels_limit_bound.append(chanell_bound)
# channels_limit_bound

In [74]:
# for _ in range(100):
#     completion_with_backoff()
#     print(_)

In [155]:
enc = tiktoken.get_encoding("cl100k_base")
x = """۷ ملک دیگر بانک فرابورسی کارشناسی شدند/ افزایش ارزش دارایی‌ها
به گزارش پایگاه خبری بورس پرس، به‌دنبال ارائه پیشین گزارش‌های کارشناسی املاک بانک آینده در سامانه کدال، ارزیابی‌های جدیدی از املاک این بانک حاضر در بازار پایه و غایب 19 ماهه از تابلو معاملات افشا شد.
🔹بر اساس این گزارش، املاک و دارایی‌های ارزیابی شده از شرکت‌های زیرمجموعه بانک آینده که توسط هیأت کارشناسان رسمی دادگستری مرکز وکلا و کارشناسان رسمی قوه قضائیه انجام شده، بیانگر افزایش ارزش چشمگیر دارایی‌های مزبور، نسبت به گذشته است.
🔹جدیدترین موارد افشا شامل ملک سعادت آباد متعلق به شرکت تجارت الکترونیک فردا، ملک شیخ بهایی متعلق به شرکت توسعه تجارت نگین بینالود، ملک جردن متعلق به شرکت دقایق‌گستر پویا، املاک زرتشت و حکیم متعلق به شرکت آشیان‌سازان کیهان،"""
len(enc.encode(x))

510

In [140]:
# %%time
# def add(x, y):
#     return  x+y['text']
#     # return  x+"**"+y

# # list = [2, 4, 7, 3]
# reduce(add, telegram_chanells[0][:7+1],"")

# def concatenate_chanell_chat(chanell):
#     chats=""
#     for chat in chanell:
#         # chats+=("\n".join(chat['text'])+"**")
#         chats+=chat['text']
#     return chats

# x==concatenate_chanell_chat(telegram_chanells[0][:7+1])
# telegram_chanells[0][:7+1]

In [67]:
import os


# openai.Model.retrieve("gpt-3.5-turbo")
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )
# embeddings = response['data'][0]['embedding']
def request_openai(prompt):
    return openai.Completion.create(
        model="gpt-3.5-turbo", prompt="generate some ", temperature=1, max_tokens=5
    )

In [71]:
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )

# import os
# import openai

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello!"}]
)

completion
completion
# print(completion.choices[0].message)
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")

<OpenAIObject chat.completion id=chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN at 0x7fcde1e1c770> JSON: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello there! How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "created": 1683976467,
  "id": "chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 10,
    "prompt_tokens": 10,
    "total_tokens": 20
  }
}

In [105]:
# print(completion)
# print(completion)
# print(completion)
# print(completion)
# for i in range(20):
#     openai.ChatCompletion.create(
#   model="gpt-3.5-turbo",
#   messages=[
#     {"role": "user", "content": "Hello!"}
#   ]
# )

In [108]:
len(enc.encode("Hello!" * 1000))

2000

In [51]:
df = pd.DataFrame({'A': ['a','a', 'b', 'a'], 'B': ['b','a', 'a', 'c'],
                   'C': [1, 2, 3,4]})
df

   A  B  C
0  a  b  1
1  a  a  2
2  b  a  3
3  a  c  4

In [5]:
a={}
a.

AttributeError: 'str' object has no attribute 'conjugate'