In [1]:
import tiktoken
import os
from parsivar import Normalizer
import pandas as pd
import numpy as np
import json
import shortuuid
import regex as re
import time
from functools import reduce
import openai  # for OpenAI API calls
from tenacity import (
    retry,
    stop_after_attempt,
    wait_random_exponential,
)  # for exponential backoff

# from openai.embeddings_utils import get_embedding, cosine_similarity;
# import matplotlib

### Openai api notes for embedding

1. Embedding :

-   Each input must not exceed 8192 tokens in length.
-   Model Name => text-embedding-ada-002

In [14]:
uuid = shortuuid.ShortUUID(alphabet="0123456789abcdefghijklmnopqrstuvwxyz")
enc = tiktoken.get_encoding("cl100k_base")
pd.set_option("display.max_rows", None)
openai.api_key = "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"

In [4]:
# with open('../../dataset/majid/result.json', encoding='utf-8') as file:
#     maj = json.loads(file.reaad())
# maj

In [5]:
# with open('../../dataset/BOURSGRAM/boursgram.json', encoding='utf-8') as file:
#     boursgram_data = json.loads(file.read())
# boursgram_data

In [6]:
# with open('result.json', encoding='utf-8') as file:
#     result = json.loads(file.read())
# len(result)

In [106]:
stocks = pd.read_csv("../stocks/stocks_tsetmcs.csv")
stocks = stocks[["sym_name", "name", "sym", "gp_name"]]
exlude_list = ["ما", "تمدن"]
stocks = stocks[~stocks["sym_name"].isin(exlude_list)]
stocks.head()

,sym_name,name,sym,gp_name
0,18719101,اوراق مشاركت ايران‌ خودرو,IKCQ1,خودرو و ساخت قطعات
1,آباد,توريستي ورفاهي آبادگران ايران,ABAD1,هتل و رستوران
2,آبادا,توليد نيروي برق آبادان,NBAB1,عرضه برق، گاز، بخاروآب گرم
3,آبادح,ح . ‌توريستي‌ورفاهي‌آبادگران‌,ABAX1,هتل و رستوران
4,آپ,آسان پرداخت پرشين,APPE1,رايانه و فعاليت‌هاي وابسته به آن

In [117]:
# txt="""# فولاژ
# در آستانه صف خرید به دلیل رشد 50 درصدی متوقف شد
#     """

# with open('./stocks/stk_id.json', encoding='utf-8') as file:
#     stocks = json.loads(file.read())
# len(stocks)
# stocks


def norm(txt):
    return Normalizer().normalize(txt)


def token_count(txt):
    return len(enc.encode(txt))


def if_chatlist_id_included(chatlist, ID):
    #     print("CHATLIS__",chat_list)
    for chat in chatlist:
        if ID in chat["id_list"]:
            return True
    return False


def is_id_in_chatlist(chatlist, ID):
    #     print("CHATLIS__",chat_list)
    for chat in chatlist:
        if ID == chat["chat_id"]:
            return True
    return False


def if_stock_included(txt):
    for index, row in stocks.iterrows():
        if norm(row["sym_name"]) in norm(txt):
            #             print("if_stock_included__")
            #             print(f"_*_{norm(txt)}_*_",row["sym_name"])
            return True
    return False


# if stock name is included in the text it will be replaced by stocks ID RETURNS: (if_is_included,text)
def if_stock_included_replace(txt):
    txt = norm(txt)
    #     txt_list=txt.split()

    for index, row in stocks.iterrows():
        norm_sym = norm(row["sym_name"]).replace("\u200c", " ")
        # txt = re.sub(rf"\b{norm_sym}\b", f"<{row['sym']}>", txt)
        txt = re.sub(rf"\b{norm_sym}\b", f"<{norm_sym}>", txt)
    #     print("replace_stock_with_idـ",norm_sym)
    # if re.findall(r"<[0-9A-Za-z]*>", txt):
    
    if re.findall(r"<[آا-ی\s]*>", txt):
        return True, txt
    return False, txt


def clean_text(txt):
    replacement_patterns = {
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+": "",  # website
        r"[\w\.-]+@[\w\.-]+": "",  # email
        r"@[A-Za-z0-9]*": "",  # @ID
        r"#": "",
        r"\n{2,}": "\n",
    }
    for pattern, replacement in replacement_patterns.items():
        txt = re.sub(pattern, replacement, txt)
    return txt

In [75]:
# with open('./majid/result.json', encoding='utf-8') as file:
#     maj = json.loads(file.read())
# maj

### Preprocessing public_supergroup

-   GROUPS List :
    1. BOURSGRAM بورسگرام

In [37]:
SUBGROUPS = {
    "1727038436": {
        "name": "بورسگرام | Boursegram",
        "40231": {"name": "غذایی"},
        "40209": {"name": "حمل و نقل"},
        "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
        "40211": {"name": "بانکها"},
        "40302": {"name": "خودرو و ساخت قطعات"},
        "48994": {"name": "آپشن (اختیار معامله)"},
        "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
        "40230": {"name": "دارویی"},
        "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
        "40203": {"name": "انبوه سازي_ساختمانی"},
        "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
        "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
        "40253": {"name": "زراعت"},
        "40236": {"name": "قند و شكر"},
        "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
        "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
        "40206": {
            "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
        },
        "40207": {"name": "بیمه"},
        "40227": {"name": "محصولات شيميايي"},
        "40219": {"name": "سیمان"},
        "40210": {"name": "لیزینگ"},
        "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
        "40247": {"name": "لاستيك و پلاستيك"},
        "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
        "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
        "40217": {"name": "هتل و رستوران"},
        "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
        "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
        "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
    }
}

# BOURSGRAM_SUBGROUPS = {
#     "40231": {"name": "غذایی"},
#     "40209": {"name": "حمل و نقل"},
#     "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
#     "40211": {"name": "بانکها"},
#     "40302": {"name": "خودرو و ساخت قطعات"},
#     "48994": {"name": "آپشن (اختیار معامله)"},
#     "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
#     "40230": {"name": "دارویی"},
#     "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
#     "40203": {"name": "انبوه سازي_ساختمانی"},
#     "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
#     "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
#     "40253": {"name": "زراعت"},
#     "40236": {"name": "قند و شكر"},
#     "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
#     "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
#     "40206": {
#         "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
#     },
#     "40207": {"name": "بیمه"},
#     "40227": {"name": "محصولات شيميايي"},
#     "40219": {"name": "سیمان"},
#     "40210": {"name": "لیزینگ"},
#     "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
#     "40247": {"name": "لاستيك و پلاستيك"},
#     "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
#     "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
#     "40217": {"name": "هتل و رستوران"},
#     "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
#     "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
#     "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
# }

In [21]:
"40202" in BOURSGRAM_SUBGROUPS
# BOURSGRAM_SUBGROUPS["40202"]

{'name': 'رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري'}

In [9]:
# %%time
# def preprocess_subgroup():
messages = boursgram_data["messages"]
chat_list_2 = []
for mess in messages:
    txt = ""
    if "actor_id" in mess:
        continue

    date = mess["edited"] if ("edited" in mess) else mess["date"]
    date_unixtime = (
        mess["edited_unixtime"]
        if ("edited_unixtime" in mess)
        else mess["date_unixtime"]
    )

    chat_info = {
        "person_id": mess["from_id"],
        "chat_id": mess["id"],
        "date": date,
        "date_unixtime": date_unixtime,
        "org_txt": mess["text"],
        "reply_to_message_id": "",
    }

    for tx in mess["text_entities"]:
        txt += clean_text(tx["text"]).strip() + "\n"

    #     chat_info["text"]= txt
    is_stock_included, txt = if_stock_included_replace(txt.strip())

    # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
    if (
        ("reply_to_message_id" in mess)
        and mess["reply_to_message_id"] not in SUBGROUPS[""]
    ) and (is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
        #         txt_rep = replace_stock_with_id(txt.strip())
        chat_info["text"] = txt
        chat_list_2.append(chat_info)
        #                 print(cht["id_list"])
        # print("looooool")
    #     is_included,txt = replace_stock_with_id(txt.strip())
    elif is_stock_included:
        chat_info["text"] = txt
        chat_list_2.append(chat_info)
# print(chat_list_1)
#

In [9]:
# # %%time
# def preprocess_subgroup(data):
#     print("__> preprocess_subgroup", data["name"])
#     # messages = boursgram_data["messages"]
#     chat_list = []
#     for mess in data["messages"]:
#         txt = ""
#         if "actor_id" in mess:
#             continue

#         date = mess["edited"] if ("edited" in mess) else mess["date"]
#         date_unixtime = (
#             mess["edited_unixtime"]
#             if ("edited_unixtime" in mess)
#             else mess["date_unixtime"]
#         )

#         for tx in mess["text_entities"]:
#             txt += clean_text(tx["text"]).strip() + "\n"
#         is_stock_included, rep_txt = if_stock_included_replace(txt.strip())

#         chat_info = {
#             "person_id": mess["from_id"],
#             "chat_id": mess["id"],
#             "date": date,
#             "date_unixtime": date_unixtime,
#             "org_txt": txt,
#             "reply_to_message_id": "",
#             "text":rep_txt
#         }

#         #     chat_info["text"]= txt

#         # if (data["type"]== "public_supergroup" and mess["reply_to_message_id"] not in SUBGROUPS["id"] ) or (data["type"] != "public_supergroup" ):

#         # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
#         if (
#             ("reply_to_message_id" in mess)
#             and (mess["reply_to_message_id"] not in SUBGROUPS["id"])
#             and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
#         ):
#             chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
#             #         txt_rep = replace_stock_with_id(txt.strip())
#             # chat_info["text"] = txt
#             chat_list.append(chat_info)
#             #                 print(cht["id_list"])
#             # print("looooool")
#         #     is_included,txt = replace_stock_with_id(txt.strip())
#         elif is_stock_included:
#             # chat_info["text"] = txt
#             chat_list.append(chat_info)

#     return {**data, "messages": chat_list}


# # print(chat_list_1)
# #

In [118]:
# %%time
def preprocess_subgroup(data):
    data_id = str(data["id"])
    print("__> preprocess_subgroup", data["name"])
    # messages = boursgram_data["messages"]
    chat_list = []
    for mess in data["messages"]:
        txt = ""
        if "actor_id" in mess:
            continue

        date = mess["edited"] if ("edited" in mess) else mess["date"]
        date_unixtime = (
            mess["edited_unixtime"]
            if ("edited_unixtime" in mess)
            else mess["date_unixtime"]
        )

        for tx in mess["text_entities"]:
            txt += clean_text(tx["text"]).strip() + "\n"

        if token_count(txt) > 500:
            continue
        is_stock_included, rep_txt = if_stock_included_replace(txt.strip())

        chat_info = {
            "person_id": mess["from_id"],
            "chat_id": mess["id"],
            "date": date,
            "date_unixtime": date_unixtime,
            "org_txt": txt,
            "reply_to_message_id": "",
            "text": rep_txt,
        }

        #     chat_info["text"]= txt

        # if (data["type"]== "public_supergroup" and mess["reply_to_message_id"] not in SUBGROUPS["id"] ) or (data["type"] != "public_supergroup" ):

        # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        if (
            ("reply_to_message_id" in mess)
            and (
                (  ## checks in public_supergroup that have subgroups,wheter the replied messaged is not replied to the subgroup ID
                    data["type"] == "public_supergroup"
                    and (data_id in SUBGROUPS)
                    and (mess["reply_to_message_id"] not in SUBGROUPS[data_id])
                )
                or (data["type"] != "public_supergroup")
            )
            and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
        ):
            chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
            #         txt_rep = replace_stock_with_id(txt.strip())
            # chat_info["text"] = txt
            chat_list.append(chat_info)
            #                 print(cht["id_list"])
            # print("looooool")
        #     is_included,txt = replace_stock_with_id(txt.strip())
        elif is_stock_included:
            # chat_info["text"] = txt
            chat_list.append(chat_info)

    return {**data, "messages": chat_list}


# print(chat_list_1)
#

In [147]:
# chat_list_2
# bours_df=pd.DataFrame(chat_list_2)
# bours_df.head()
# x="  'text': '\u200c\nواقعیت ماجرای شاسی
# بلندها و ارتباطشان با استیضاح وزیر صمت\nمنابع < PKLJ1 > تایید کردند در ابتدای تابستان 1400 یعنی تنها چند هفته بعد از انتخابات ریاس"
# clean_text(x)

### Preprocessing telegram public_channel and simplegroups

In [146]:
# # %%time

# messages = maj["messages"]
# maj_list = []
# for mess in messages:
#     txt = ""
#     date = mess["edited"] if ("edited" in mess) else mess["date"]
#     date_unixtime = (
#         mess["edited_unixtime"]
#         if ("edited_unixtime" in mess)
#         else mess["date_unixtime"]
#     )
#     for tx in mess["text_entities"]:
#         txt += clean_text(tx["text"]).strip() + "\n"
#     chat_info = {
#         "person_id": mess["from_id"],
#         "chat_id": mess["id"],
#         "date": date,
#         "date_unixtime": date_unixtime,
#         "org_txt":txt,
#         "reply_to_message_id":""
#     }

#     #     chat_info["text"]= txt
#     is_stock_included, txt = if_stock_included_replace(txt.strip())

#     if ("reply_to_message_id" in mess) and (
#         is_id_in_chatlist(maj_list, mess["reply_to_message_id"])
#     ):
#         chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
#         #         txt_rep = replace_stock_with_id(txt.strip())
#         chat_info["text"] = txt
#         maj_list.append(chat_info)
#         #                 print(cht["id_list"])
#         print("looooool")
#     #     is_included,txt = replace_stock_with_id(txt.strip())
#     elif is_stock_included:
#         chat_info["text"] = txt
#         maj_list.append(chat_info)
# #     elif if_stock_included(txt):
# # #         print("if_included_ch",txt)
# #         txt_rep = replace_stock_with_id(txt.strip())
# #         chat_info["text"]=txt_rep
# #         chat_list_2.append(chat_info)
# # print(chat_list_1)

In [145]:
# chat_list_2
# pd.DataFrame(maj_list) ,pd.DataFrame(bours_df)
# pd.concat([maj_df ,bours_df]).head()
# pd.DataFrame(maj_list)
# maj_df=pd.DataFrame(maj_list)
# majcol=maj_df[['person_id', 'chat_id', 'date', 'date_unixtime', 'org_txt', 'text','reply_to_message_id']].columns
# print(majcol)
# print(list(bours_df.columns)==list(majcol))
# maj_df=maj_df[['person_id', 'chat_id']]
# print(maj_df)
# bours_df.columns==maj_df.columns
# chat_list_2[1].keys()
# len(chat_list_2)
# len(enc.encode(chat_list_2[0]["text"]))
# chat_list_2[0]
# for index, row in df.iterrows():
#     print(row['c1'], row['c2'])

In [119]:
# datafile_names =
concatenated_data = pd.DataFrame()
chats_path = "./data/chats/"
for json_file in os.listdir(chats_path):
    # file = pd.read_csv("./data/"+json_file)
    # df = pd.DataFrame()
    with open(chats_path + json_file, encoding="utf-8") as file:
        file = json.loads(file.read())
        df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        df["channel_name"] = file["name"]
        # df.set_index("channel_name",inplace=True)
        concatenated_data = pd.concat([concatenated_data, df])

        # if file["type"] == "public_supergroup":
        #     df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])
        # else:
        #     df = pd.DataFrame(preprocess_chanell_group(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])

concatenated_data = concatenated_data.reindex()
concatenated_data.to_csv("./data/concatenated.csv", index=False)
concatenated_data.head()
# concatenated_data.con
# pd.to

__> preprocess_subgroup گروه هزار تحلیل
__> preprocess_subgroup گروه بازار
__> preprocess_subgroup بورسگرام | Boursegram

,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text,channel_name
0,user956857432,361027,2023-04-15T00:38:55,1681506535,درود هموطن با نخریدن خودرو و دوری از معاملات خ...,,درود هموطن با نخریدن <خودرو> و دوری از معاملات...,گروه هزار تحلیل
1,channel1247075296,361043,2023-04-15T10:04:39,1681540479,بورس کالا پیشنهاد افزایش سرمایه از دو محل سود ...,,<بورس> <کالا> پیشنهاد افزایش سرمایه از دو محل ...,گروه هزار تحلیل
2,user164684213,361050,2023-04-15T11:56:44,1681547204,خودرو و خساپا به احتمال زیاد صف خرید بشند قابل...,,<خودرو> و <خساپا> به احتمال زیاد صف خرید بشند ...,گروه هزار تحلیل
3,user164684213,361051,2023-04-15T11:57:46,1681547266,از فراکاب ها بورس هم وضعیت خوبی داره مدتی درجا...,,از فراکاب‌ها <بورس> هم وضعیت خوبی داره مدتی در...,گروه هزار تحلیل
4,user164684213,361052,2023-04-16T07:36:10,1681617970,وخارزم در حال شکستن مقاومت ، هدف بالاست. بررسی\n,,<وخارزم> در حال شکستن مقاومت ، هدف بالاست . بررسی,گروه هزار تحلیل

In [200]:
# len(concatenated_data)
# # concatenated_data.
# # concatenated_data.set_index([range(1,len(concatenated_data)+1),"channel_name"])
# concatenated_data['index']=range(1,len(concatenated_data)+1)
# concatenated_data
# while
# concatenated_data.iloc[1:3]

In [120]:
# len(concatenated_data)
# chats=concatenated_data.set_index("channel_name")
chats = concatenated_data
chats = chats[chats["text"] != ""]

# len(enc.encode("".join(list(chats[49:121]["text"]))))

chats["embedding"] = np.nan
embed_index = chats.columns.get_loc("embedding")

/tmp/ipykernel_7772/2233699042.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chats["embedding"] = np.nan

In [199]:
# df['Row Sum'] = chats["te"].apply(row_sum, axis=1)
# len(enc.encode("".join( list(chats[49: 110]["text"]))))

# chats.iloc[0 : 48, text_index]
# embed = embedding_with_backoff(list(chats.iloc[49:210, text_index]))
# embed

In [216]:
# a=["a",1]
# a=pd.DataFrame({"a":range(10),"b":range(10)})
# a.iloc[0:5,1]=list(range(100,105))
# a
# a.loc[0:1]
# eval(str(a))
# embed["data"][1]["index"]

# len(x)x=list(str(emb["embedding"]) for emb in embed["data"])
chats.drop

,level_0,index,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text,channel_name,test
0,0,0,user956857432,361027,2023-04-15T00:38:55,1681506535,درود هموطن با نخریدن خودرو و دوری از معاملات خ...,,درود هموطن با نخریدن <IKCO1> و دوری از معاملات...,گروه هزار تحلیل,"[-0.004583475645631552, 0.000674283888656646, ..."
1,1,1,channel1247075296,361043,2023-04-15T10:04:39,1681540479,بورس کالا پیشنهاد افزایش سرمایه از دو محل سود ...,,<BORS1> <KALA1> پیشنهاد افزایش سرمایه از دو مح...,گروه هزار تحلیل,"[-0.02429431676864624, -0.014644262380897999, ..."
2,2,2,user164684213,361050,2023-04-15T11:56:44,1681547204,خودرو و خساپا به احتمال زیاد صف خرید بشند قابل...,,<IKCO1> و <SIPA1> به احتمال زیاد صف خرید بشند ...,گروه هزار تحلیل,"[-0.002862186636775732, -0.020522119477391243,..."
3,3,3,user164684213,361051,2023-04-15T11:57:46,1681547266,از فراکاب ها بورس هم وضعیت خوبی داره مدتی درجا...,,از فراکاب‌ها <BORS1> هم وضعیت خوبی داره مدتی د...,گروه هزار تحلیل,"[0.007988776080310345, -0.023250915110111237, ..."
4,4,4,user164684213,361052,2023-04-16T07:36:10,1681617970,وخارزم در حال شکستن مقاومت ، هدف بالاست. بررسی\n,,<IKHR1> در حال شکستن مقاومت ، هدف بالاست . بررسی,گروه هزار تحلیل,"[-0.021470045670866966, -0.023386044427752495,..."
5,5,5,user164684213,361053,2023-04-15T12:11:31,1681548091,بورس صف خرید قدرتمند\n,,<BORS1> صف خرید قدرتمند,گروه هزار تحلیل,"[-0.024858329445123672, -0.019742438569664955,..."
6,6,6,user164684213,361054,2023-04-15T12:18:35,1681548515,کندل های وخارزم نشان از صف خرید میدند بررسی مج...,,کندل‌های <IKHR1> نشان از صف خرید میدند بررسی مجدد,گروه هزار تحلیل,"[0.005701655056327581, -0.010902213864028454, ..."
7,7,7,user164684213,361055,2023-04-15T12:30:38,1681549238,وتجارت و وخارزم هم صف خرید فردا حوالی صف خرید ...,,<BTEJ1> و <IKHR1> هم صف خرید فردا حوالی صف خری...,گروه هزار تحلیل,"[-0.018122000619769096, 0.0011959766270592809,..."
8,8,8,user1075476350,361058,2023-04-15T13:59:53,1681554593,سلام من پول قابل توجهی تو بورس ندارم ولی این ر...,,سلام من پول قابل‌توجهی تو <BORS1> ندارم ولی ای...,گروه هزار تحلیل,"[-0.0030234032310545444, -0.021200519055128098..."
9,9,9,channel1247075296,361061,2023-04-15T18:45:04,1681571704,رکورد حقیقی‌ها در سبزترین روز بورس ۱۴۰۲\n▪️امر...,,رکورد حقیقی‌ها در سبزترین روز <BORS1> 1402\nام...,گروه هزار تحلیل,"[-0.012641439214348793, -0.017003342509269714,..."
10,10,10,user164684213,361062,2023-04-15T20:30:44,1681578044,زمزمه عرضه خودرو در بورس کالا بالا گرفت ظاهرا ...,,زمزمه عرضه <IKCO1> در <BORS1> <KALA1> بالا گرف...,گروه هزار تحلیل,"[-0.018546128645539284, -0.03651611879467964, ..."
11,11,11,user956857432,361071,2023-04-16T07:36:35,1681617995,درود هموطن قبل از هر مطلبی یک احوال پرسی از دل...,,درود هموطن قبل از هر مطلبی یک احوال پرسی از دل...,گروه هزار تحلیل,"[-0.017796175554394722, -0.011418316513299942,..."
12,12,12,channel1247075296,361080,2023-04-16T11:21:19,1681631479,برنامه افزایش سرمایه ۴۰۰ درصدی شرکت حمل و نقلی...,,برنامه افزایش سرمایه 400 درصدی شرکت حمل و نقلی...,گروه هزار تحلیل,"[-0.01553722657263279, -0.016692206263542175, ..."
13,13,13,channel1247075296,361083,2023-04-16T16:13:08,1681648988,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 12...,گروه هزار تحلیل,"[-0.023397494107484818, -0.006529929116368294,..."
14,14,14,channel1247075296,361086,2023-04-16T17:09:11,1681652351,نقشه بازار گروه خودرو و قطعات\n\n\n,,نقشه بازار گروه <IKCO1> و قطعات,گروه هزار تحلیل,"[-0.024104328826069832, -0.0037443945184350014..."
15,15,15,channel1247075296,361088,2023-04-16T17:09:16,1681652356,سید رضا فاطمی‌امین، وزیر صنعت، معدن و تجارت\n▪...,,سید رضا فاطمی‌امین ، وزیر صنعت ، معدن و تجارت\...,گروه هزار تحلیل,"[-0.0012687182752415538, -0.03085307590663433,..."
16,16,16,channel1247075296,361092,2023-04-16T15:12:34,1681645354,قیمت روز خودروهای سایپا ، ایران خودرو / 27 فرو...,,قیمت روز خودروهای سایپا ، ایران <IKCO1> / 27 ف...,گروه هزار تحلیل,"[-0.0024601223412901163, 0.008057791739702225,..."
17,17,17,user66948699,361097,2023-04-16T16:45:21,1681650921,سلام لطفا سهم دکوثر را تحلیل می فرمائید.\n,,سلام لطفا سهم <DKSR1> را تحلیل می‌فرمائید .,گروه هزار تحلیل,"[0.012000229209661484, 0.01010510791093111, -0..."
18,18,18,user78697984,361102,2023-04-16T21:20:56,1681667456,هر نماد بورسی را که می خواهیم بخریم باید قیمت ...,,هر نماد بورسی را که می‌خواهیم بخریم باید قیمت ...,گروه هزار تحلیل,"[-0.007994123734533787, -0.004053172655403614,..."
19,19,19,user39888679,361106,2023-04-17T03:56:14,1681691174,ثشاهد\n\n,,<SAHD1>,گروه هزار تحلیل,"[-0.01280839554965496, 0.016244124621152878, -..."
20,20,20,user949621278,361107,2023-04-17T05:44:32,1681697672,ددام\n\n,,<DAML1>,گروه هزار تحلیل,"[-0.028163084760308266, -0.002301992615684867,..."
21,21,21,user115241482,361108,2023-04-17T06:02:57,1681698777,سلام دوستان \n🚚🚍\nکسی وانت نیسان خواست برای جا...,,سلام دوستان \n\nکسی وانت نیسان خواست برای جا ب...,گروه هزار تحلیل,"[0.004818926099687815, 0.004698369186371565, 0..."
22,22,22,channel1247075296,361113,2023-04-17T08:32:46,1681707766,ادعای خاندوزی درباره عرضه خودرو در بورس تکذیب ...,,ادعای خاندوزی درباره عرضه <IKCO1> در <BORS1> ت...,گروه هزار تحلیل,"[-0.02639629878103733, -0.027682911604642868, ..."
23,23,23,user94813446,361116,2023-04-17T08:57:24,1681709244,پس تپکو چی؟؟؟؟\n,,پس <HPKO1> چی ؟؟؟؟,گروه هزار تحلیل,"[-0.005039392039179802, -0.0037795440293848515..."
24,24,24,channel1247075296,361117,2023-04-17T09:11:37,1681710097,تغییر‌_سهام_سهامداران_فعال\n▪️افزایش سرمایه ها...,,تغییر‌ _ سهام _ سهامداران _ فعال\nافزایش سرمای...,گروه هزار تحلیل,"[-0.022688666358590126, -0.005818566773086786,..."
25,25,25,user530267594,361125,2023-04-17T10:14:56,1681713896,قشکر\n؟؟؟\n,,<SHKR1> \n؟؟؟,گروه هزار تحلیل,"[-0.00942434836179018, -0.005405827425420284, ..."
26,26,26,user164684213,361127,2023-04-17T10:36:27,1681715187,برکت واچ\n,,<BRKT1> واچ,گروه هزار تحلیل,"[-0.022332098335027695, -0.0025152498856186867..."
27,27,27,channel1247075296,361130,2023-04-17T12:23:29,1681721609,فرابورس ایران پیشنهادی برای افزایش دامنه نوسان...,,فرابورس ایران پیشنهادی برای افزایش دامنه نوسان...,گروه هزار تحلیل,"[-0.009814648889005184, -0.010899889282882214,..."
28,28,28,channel1247075296,361131,2023-04-17T16:18:05,1681735685,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 74...,گروه هزار تحلیل,"[-0.02375209517776966, -0.0060776215977966785,..."
29,29,29,channel1247075296,361132,2023-04-17T16:18:12,1681735692,زیرمجموعه سایپا پیشنهاد افزایش سرمایه ۳۱۸ درصد...,,زیرمجموعه سایپا پیشنهاد افزایش سرمایه 318 درصد...,گروه هزار تحلیل,"[-0.013429343700408936, -0.006413913797587156,..."
30,30,30,channel1247075296,361143,2023-04-17T16:18:53,1681735733,▪️ رئیس قوه قضاییه: در نیمه دوم ۱۴۰۰ وزیر صمت ...,,رئیس قوه قضاییه : در نیمه دوم 1400 وزیر صمت خو...,گروه هزار تحلیل,"[-0.005179875064641237, -0.021517939865589142,..."
31,31,31,channel1247075296,361152,2023-04-18T08:58:37,1681795717,واریز سودهای رسوبی به بیش از ۷.۲ همت رسید\nشرک...,,واریز سودهای رسوبی به بیش از 7.2 همت رسید\nشرک...,گروه هزار تحلیل,"[0.006867371499538422, -0.017345596104860306, ..."
32,32,32,channel1247075296,361155,2023-04-18T11:18:35,1681804115,شرکت بازار پایه ای پیشنهاد افزایش سرمایه از مح...,,شرکت بازار پایه‌ای پیشنهاد افزایش سرمایه از مح...,گروه هزار تحلیل,"[-0.024819498881697655, -0.010722077451646328,..."
33,33,33,user164684213,361156,2023-04-18T10:19:41,1681800581,برکت قابل بررسی مثبت ۱\n,,<BRKT1> قابل بررسی مثبت 1,گروه هزار تحلیل,"[-0.013731795363128185, -0.011448858305811882,..."
34,34,34,channel1247075296,361157,2023-04-18T11:18:38,1681804118,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 76...,گروه هزار تحلیل,"[-0.023190779611468315, -0.008333120495080948,..."
35,35,35,channel1247075296,361162,2023-04-18T11:19:05,1681804145,طرح استیضاح وزیر اقتصاد در مجلس به دلیل کاهش ا...,,طرح استیضاح وزیر اقتصاد در مجلس به دلیل کاهش ا...,گروه هزار تحلیل,"[-0.02361893653869629, -0.013208662159740925, ..."
36,36,36,user173580999,361166,2023-04-18T11:08:46,1681803526,تکنو\nبرا خرید زیر نظر داشته باشید\n,,<TKNO1>\nبرا خرید زیر نظر داشته باشید,گروه هزار تحلیل,"[-0.005202749278396368, -0.010651979595422745,..."
37,37,37,channel1247075296,361171,2023-04-18T12:49:22,1681809562,سخنگوی دولت تغییر «وزیر صمت» را تکذیب کرد\nبها...,,سخنگوی دولت تغییر « وزیر صمت » را تکذیب کرد\nب...,گروه هزار تحلیل,"[-0.010925063863396645, -0.0028354742098599672..."
38,38,38,channel1247075296,361177,2023-04-18T21:31:37,1681840897,ارزش معاملات خرد بورس تهران\n,,ارزش معاملات خرد <BORS1> تهران,گروه هزار تحلیل,"[-0.028870387002825737, -0.016243016347289085,..."
39,39,39,channel1247075296,361179,2023-04-18T21:31:48,1681840908,کلیات بازار، میزان تغییرات ارزش معاملات و شاخص...,,کلیات بازار ، میزان تغییرات ارزش معاملات و شاخ...,گروه هزار تحلیل,"[-0.020335884764790535, -0.014576698653399944,..."
40,40,40,channel1247075296,361180,2023-04-18T15:13:22,1681818202,تسنیم مدعی شد: کاهش ۴۰ تا ۹۰ میلیونی قیمت خودر...,,تسنیم مدعی شد : کاهش 40 تا 90 میلیونی قیمت <IK...,گروه هزار تحلیل,"[-0.004634585231542587, -0.011370977386832237,..."
41,41,41,channel1247075296,361181,2023-04-18T16:12:46,1681821766,🔴\nنامه فوری وزیر اقتصاد به رئیس‌جمهور\n🔹وزیر ...,,نامه فوری وزیر اقتصاد به رئیس‌جمهور\nوزیر اقتص...,گروه هزار تحلیل,"[-0.006698148790746927, -0.016520066186785698,..."
42,42,42,channel1247075296,361183,2023-04-18T17:34:53,1681826693,جزئیات واردات خودرو کارکرده اعلام شد\nامید قال...,,جزئیات واردات <IKCO1> کارکرده اعلام شد\n<OMID1...,گروه هزار تحلیل,"[-0.01281424518674612, -0.009902848862111568, ..."
43,43,43,channel1247075296,361184,2023-04-18T16:04:23,1681821263,بازار خودرو از سمت عرضه امسال به نقطه اشباع می...,,بازار <IKCO1> از سمت عرضه امسال به نقطه اشباع ...,گروه هزار تحلیل,"[-0.008684953674674034, -0.024459663778543472,..."
44,44,44,user973888342,361191,2023-04-18T23:02:35,1681846355,خدا لعنتشون کنه تاریخ تحویل خودرو(سورن دوگانه)...,,خدا لعنتشون کنه تاریخ تحویل <IKCO1> ( سورن دوگ...,گروه هزار تحلیل,"[-0.009455729275941849, -0.03202660754323006, ..."
45,45,45,user69564333,361198,2023-04-19T07:13:05,1681875785,سیل فروش حواله های خودرو هست که از امروز توی ج...,,سیل فروش حواله‌های <IKCO1> هست که از امروز توی...,گروه هزار تحلیل,"[-0.011131891049444675, -0.011297151446342468,..."
46,46,46,channel1247075296,361206,2023-04-19T18:11:37,1681915297,زمان پرداخت سود سهام عدالت هم مانند شرکت ها به...,,زمان <PRKT1> سود سهام عدالت هم مانند شرکت‌ها ب...,گروه هزار تحلیل,"[-0.009995631873607635, -0.02094900980591774, ..."
47,47,47,user173580999,361210,2023-04-19T10:35:01,1681887901,بورس هم چند روز قبل گفتم بخرین\nدو روزه صف خری...,,<BORS1> هم چند روز قبل گفتم بخرین\nدو روزه صف ...,گروه هزار تحلیل,"[-0.01913473941385746, 0.00040884778718464077,..."
48,48,48,channel1247075296,361211,2023-04-19T10:45:55,1681888555,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 72...,گروه هزار تحلیل,"[-0.02071465738117695, -0.0024163706693798304,..."
49,49,49,channel1247075296,361221,2023-04-19T12:45:02,1681895702,برنامه دولت برای اخذ مالیات از معاملات مکرر مس...,,برنامه دولت برای اخذ مالیات از معاملات مکرر مس...,گروه هزار تحلیل,"[-0.007500726729631424, -0.006628000643104315,..."
50,50,50,channel1247075296,361223,2023-04-19T12:50:29,1681896029,لایحه دوفوریتی واردات خودروهای کارکرده تصویب و...,,لایحه دوفوریتی واردات خودروهای کارکرده تصویب و...,گروه هزار تحلیل,"[-0.012289070524275303, -0.008199586533010006,..."
51,51,51,user453967023,361234,2023-04-20T20:02:11,1682008331,سلام\nساعت بورس از ۲/۱۶ میخاد تغییر کنه؟\n,,سلام\nساعت <BORS1> از 2 / 16 میخاد تغییر کنه ؟,گروه هزار تحلیل,"[-0.01254215370863676, -0.013465826399624348, ..."
52,52,52,user6195229393,361235,2023-04-20T21:13:26,1682012606,سلام. وقت بخیر. نظرتون در مورد چکارن؟ در منفی ...,,سلام . وقت بخیر . نظرتون در مورد <KRTI1> ؟ در ...,گروه هزار تحلیل,"[0.003243245417252183, -0.012074056081473827, ..."
53,53,53,user164684213,361236,2023-04-20T21:21:00,1682013060,بجاش چکاپا بگیر بررسی کن\n,,بجاش <KAPA1> بگیر بررسی کن,گروه هزار تحلیل,"[-0.0007934776367619634, -0.004565797280520201..."
54,54,54,user367978778,361239,2023-04-20T22:04:01,1682015641,تحلیلی از شبندر بزارید\n,,تحلیلی از <PNBA1> بزارید,گروه هزار تحلیل,"[-0.02228635735809803, -0.017445126548409462, ..."
55,55,55,user299743843,361240,2023-04-20T22:05:39,1682015739,شپدیس نظرتون چیه؟\n,,<PRDZ1> نظرتون چیه ؟,گروه هزار تحلیل,"[0.008631128817796707, -0.02028447389602661, 0..."
56,56,56,user164684213,361241,2023-04-20T22:30:36,1682017236,دوشنبه اول وقت سهم نگیر بازار رو نگاه اگه صعود...,,دوشنبه اول وقت سهم نگیر بازار رو نگاه اگه صعود...,گروه هزار تحلیل,"[-0.0006194617017172277, -0.013105801306664944..."
57,57,57,user161839085,361242,2023-04-21T08:22:33,1682052753,کساپا یا گدنا\n,,<SISH1> یا گدنا,گروه هزار تحلیل,"[-0.012202493846416473, -0.007332440000027418,..."
58,58,58,user107620713,361243,2023-04-21T09:55:51,1682058351,فرآور\n\n,,<FRVR1>,گروه هزار تحلیل,"[-0.013149932958185673, -0.012004321441054344,..."
59,59,59,user122377350,361246,2023-04-21T17:42:26,1682086346,شبندر کسی تحلیل داره\n,,<PNBA1> کسی تحلیل داره,گروه هزار تحلیل,"[-0.00998157262802124, -0.02140861749649048, 0..."
60,60,60,channel1247075296,361249,2023-04-21T21:58:36,1682101716,کت تن کیه ؟!\nتوییت افشاگرایانه رییس اتاق بازر...,,کت تن کیه ؟!\n توییت افشاگرایانه رییس اتاق باز...,گروه هزار تحلیل,"[-0.011301090940833092, -0.014305348508059978,..."
61,61,61,user799325239,361254,2023-04-23T09:38:19,1682230099,سلام وقت بخیر\nیه سوال داشتم اگه امکانش بود ج...,,سلام وقت بخیر\nیه سوال داشتم اگه امکانش‌بود جو...,گروه هزار تحلیل,"[-0.005214995238929987, 0.005817617289721966, ..."
62,62,62,user216841847,361256,2023-04-23T12:30:20,1682240420,پس از ریزش های سال 99 بازار بورس ایران و سیل ا...,,پس از ریزش‌های سال 99 بازار <BORS1> ایران و سی...,گروه هزار تحلیل,"[-0.02115100435912609, -0.017931794747710228, ..."
63,63,63,user216841847,361257,2023-04-23T12:31:07,1682240467,نسبت P/S از دو واژه Price به معنای قیمت و Sale...,,نسبت P / S از دو واژه Price به معنای قیمت و Sa...,گروه هزار تحلیل,"[-0.009756434708833694, -0.006443175952881575,..."
64,64,64,user6195229393,361261,2023-04-23T21:30:17,1682272817,سلام. وقت بخیر. میدکو را برای خرید فردا چطور م...,,سلام . وقت بخیر . <MDKO1> را برای خرید فردا چط...,گروه هزار تحلیل,"[0.003633804153650999, 0.01113294716924429, -0..."
65,65,65,user956857432,361263,2023-04-24T00:16:17,1682282777,درود به همه هموطن اتحاد شما در برابر خودرو ساز...,,درود به همه هموطن اتحاد شما در برابر <IKCO1> س...,گروه هزار تحلیل,"[-0.009424790740013123, -0.01618131436407566, ..."
66,66,66,channel1247075296,361278,2023-04-24T11:47:01,1682324221,وضعیت بازار در این لحظه\n🔳\nارزش معاملات :\n▫️...,,وضعیت بازار در این لحظه\n\nارزش معاملات :\n 94...,گروه هزار تحلیل,"[-0.02020762301981449, -0.00943837221711874, -..."
67,67,67,channel1247075296,361279,2023-04-24T11:47:06,1682324226,رشد ۴۱ درصدی محصولات سایپا در فروردین با تولید...,,رشد 41 درصدی محصولات سایپا در فروردین با تولید...,گروه هزار تحلیل,"[-0.009068685583770275, -0.010694204829633236,..."
68,68,68,channel1247075296,361280,2023-04-24T11:47:15,1682324235,حجم مبنا ۲۷ نماد فرابورسی از سه شنبه حذف می شو...,,حجم مبنا 27 نماد فرابورسی از سه شنبه حذف می‌شو...,گروه هزار تحلیل,"[-0.01943681389093399, -0.001369088189676404, ..."
69,69,69,user54013653,361284,2023-04-24T12:08:58,1682325538,تا بازار بورس دوطرفه نشود ریسک بالایی خواهد دا...,,تا بازار <BORS1> دوطرفه نشود ریسک بالایی خواهد...,گروه هزار تحلیل,"[-0.0188043974339962, -0.024930475279688835, -..."
70,70,70,user84698370,361285,2023-04-24T12:16:01,1682325961,🔻مخالفت نمایندگان مجلس با استیضاح فاطمی امین\n...,,مخالفت نمایندگان مجلس با استیضاح فاطمی <TSAN1>...,گروه هزار تحلیل,"[0.0005962142022326589, -0.0150330550968647, -..."
71,71,71,user367978778,361288,2023-04-24T12:49:57,1682327997,شبندر رو تحلیل کنید\n,,<PNBA1> رو تحلیل کنید,گروه هزار تحلیل,"[0.004434048663824797, -0.011579276993870735, ..."
72,72,72,user956857432,361289,2023-04-24T13:11:15,1682329275,درود بهتر نبود وزارت و مجلس اول عملکرد مثبت را...,,درود بهتر نبود وزارت و مجلس اول عمل‌کرد مثبت ر...,گروه هزار تحلیل,"[0.008305607363581657, -0.011833084747195244, ..."
73,73,73,user69564333,361295,2023-04-24T20:15:28,1682354728,شاخص_کل_بورس\nبعد از اصلاح شدیدی که شاخص کل بو...,,شاخص _ کل _ <BORS1>\nبعد از اصلاح شدیدی که شاخ...,گروه هزار تحلیل,"[-0.01935340091586113, -0.013764213770627975, ..."
74,74,74,channel1247075296,361299,2023-04-25T08:51:45,1682400105,قیمت شکر تنظیم بازار و قند شکسته بسته بندی: ۲۱...,,قیمت شکر تنظیم بازار و قند شکسته بسته‌بندی : 2...,گروه هزار تحلیل,"[-0.013384942896664143, -0.00734466128051281, ..."
75,75,75,channel1247075296,361306,2023-04-25T10:16:37,1682405197,شرکت بورسی چهار قرارداد برای تولید و فروش بطری...,,شرکت بورسی چهار قرارداد برای تولید و فروش بطری...,گروه هزار تحلیل,"[-0.014569593593478203, -0.018917517736554146,..."
76,76,76,channel1247075296,361311,2023-04-25T10:50:00,1682407200,نقشه بازار گروه خودرو و قطعات\n\n\n,,نقشه بازار گروه <IKCO1> و قطعات,گروه هزار تحلیل,"[-0.024104328826069832, -0.0037443945184350014..."
77,77,0,user1012889741,751441,2023-05-13T00:35:18,1683925518,✨\nاتاق های ۳گانه مارکت انس\n(یک طرفه)\nتوتال ...,,اتاق‌های 3گانه مارکت انس \n( یک‌طرفه )\n توتال...,گروه بازار,"[-0.03224995359778404, 0.005043300334364176, 0..."
78,78,1,user170865604,751447,2023-05-13T10:00:13,1683959413,نیمه دوم بازار یرمیگرده مفت فروشی نگنید سهام ب...,,نیمه دوم بازار یرمیگرده مفت فروشی نگنید سهام ب...,گروه بازار,"[-0.03249457851052284, 0.004674057941883802, -..."
79,79,2,user170865604,751458,2023-05-13T11:55:50,1683966350,کترام صف فروشش جمع شد\n,,<TKSM1> صف فروشش جمع شد,گروه بازار,"[-0.015325411222875118, -0.011085336096584797,..."
80,80,3,user296014733,751462,2023-05-13T13:18:58,1683971338,فقط شیشه ای ها میرن سمت بورس ایران\n,,فقط شیشه‌ای ها میرن سمت <BORS1> ایران,گروه بازار,"[-0.01840779185295105, -0.02053125761449337, -..."
81,81,4,user296014733,751467,2023-05-13T14:38:43,1683976123,خدا شفا بده\n,,خدا <SHFA1> بده,گروه بازار,"[-0.01510512176901102, -0.01280129048973322, -..."
82,82,5,user170865604,751476,2023-05-13T20:47:21,1683998241,فوری؛\n🔺دو مصوبه مهم سازمان بورس برای حمایت از...,,فوری ؛\n دو مصوبه مهم سازمان <BORS1> برای حمای...,گروه بازار,"[-0.027391018345952034, -0.015341119840741158,..."
83,83,6,user170865604,751480,2023-05-14T00:22:50,1684011170,دستور حمایت وزیر اقتصاد از بازار سرمایه از جده...,,دستور حمایت وزیر اقتصاد از بازار سرمایه از جده...,گروه بازار,"[-0.01905154436826706, -0.00909802969545126, -..."
84,84,7,user170865604,751493,2023-05-14T10:40:05,1684048205,فلامی سهم انحصاری در تولید ژیلت و تیغ با سود د...,,<LAMI1> سهم انحصاری در تولید ژیلت و تیغ با سود...,گروه بازار,"[-0.014380701817572117, 0.007197146769613028, ..."
85,85,8,user395390942,751505,2023-05-14T14:49:05,1684063145,🔴 وزارت صمت: اطلاعات همۀ خریداران خودرو از سام...,,وزارت صمت : اطلاعات همه خریداران <IKCO1> از سا...,گروه بازار,"[-0.011748508550226688, -0.0011331302812322974..."
86,86,0,user117414063,71138,2023-05-14T08:59:38,1684042178,منم تازه چند روز وارد شستا شدم منتظرم پایینتر ...,,منم تازه چند روز وارد <TAMN1> شدم منتظرم پایین...,بورسگرام | Boursegram,"[-0.01531848032027483, -0.017790475860238075, ..."
87,87,1,user732850104,71151,2023-05-14T09:23:01,1684043581,یه نوسان‌گیری عالی از سهمهایی که گفته بودم\nخگ...,,یه نوسان‌گیری عالی از سهمهایی که گفته بودم\n<G...,بورسگرام | Boursegram,"[-0.022676806896924973, -0.00568633945658803, ..."
88,88,2,user106533999,71156,2023-05-14T09:20:46,1684043446,خبری شد دوباره دارن خساپا رو صف فروش میکنن؟\n,,خبری شد دوباره دارن <SIPA1> رو صف فروش میکنن ؟,بورسگرام | Boursegram,"[0.004924655891954899, -0.009460699744522572, ..."
89,89,3,user5632416119,71157,2023-05-14T09:21:19,1684043479,چرا من اسمتو نمیفهمم\nولی خیلی با حالی 🤚🏻🤚🏻🤚🏻☺️\n,71151,چرا من اسمتو نمیفهمم\nولی خیلی با حالی,بورسگرام | Boursegram,"[-0.02513243816792965, 0.0002731010608840734, ..."
90,90,5,user732850104,71160,2023-05-14T09:23:05,1684043585,بازیشونه\n,71156,بازیشونه,بورسگرام | Boursegram,"[-0.033924125134944916, -0.011035558767616749,..."

In [10]:
# type(embed["data"][0])
# embed["data"][0]["embedding"]
# # chats[]
# chats.iloc[0, text_index]=embed["data"][0]

@retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(7))
def embedding_with_backoff(input_data: list):
    # input_data.
    return openai.Embedding.create(model="text-embedding-ada-002", input=input_data)

In [ ]:
i = 0
token_count = 0
prev_index = 0
chats_limit_bound = []
chats.reset_index(inplace=True,drop=True)
data_len = len(chats)
text_index = chats.columns.get_loc("text")
while i < data_len:
    chat = chats.iloc[i]
    chat_tokens_count = len(token_count(chat["text"]))
    # print(i,chat_tokens_count,token_count,token_count + chat_tokens_count > 4096,i + 1 == len(chanell),)
    if token_count + chat_tokens_count > 8192:
        # slice_embed=chats.iloc[(prev_index) : i , text_index]
        # chats.iloc[(0 if i == 0 else i + 1) : i, embed_index] = embedding_with_backoff(
        #     slice_embed
        # )
        prev_index = 0 if prev_index == 0 else prev_index + 1

        print("s1")
        print(f"i: {i}, prev_index: {prev_index}")
        slice_embed = list(chats.iloc[prev_index:i, text_index])
        embeddings = embedding_with_backoff(slice_embed)
        embed_str_list = [str(embed["embedding"]) for embed in embeddings["data"]]
        chats.iloc[prev_index:i, embed_index] = embed_str_list
        print("s2")
        # chats_limit_bound.append(i - 1)
        prev_index = i - 1
        token_count = 0
    elif i + 1 == data_len:
        prev_index = 0 if prev_index == 0 else prev_index + 1
        print("f1")
        print(f"i: {i}, prev_index: {prev_index}")
        slice_embed = list(chats.iloc[prev_index : i + 1, text_index])
        embeddings = embedding_with_backoff(slice_embed)
        embed_str_list = [str(embed["embedding"]) for embed in embeddings["data"]]
        chats.iloc[prev_index : i + 1, embed_index] = embed_str_list
        print("f2")
        # chats.iloc[prev_index : i + 1, embed_index] = embedding_with_backoff(slice_embed)
        # chats_limit_bound.append(i)
        prev_index = i
        token_count = 0
        i += 1
    else:
        token_count += chat_tokens_count
        i += 1
print(chats_limit_bound)

s1
i: 49, prev_index: 0

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

s2
s1
i: 120, prev_index: 49
s2
f1
i: 149, prev_index: 120
f2
[]

### Model

In [121]:
# chats.drop(columns=["level_0"	,"index"],inplace=True)
chats.reset_index(inplace=True,drop=True)

rnd = round(len(chats) * 0.6)
print(rnd,len(chats))
labeled_chats = chats
# rnd
labeled_chats.loc[0:rnd, "pred"] = 1
labeled_chats.loc[rnd + 1 : len(chats) - 1, "pred"] = 0
# labeled_chats.head(3)
# chats

90 150

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

### Make infreneces

In [145]:
labeled_chats.iloc[17]["text"]

'سلام لطفا سهم <دکوثر> را تحلیل می\u200cفرمائید .'

In [172]:
reg=norm('\؟\|\?|بررسی|تحلیل').replace(' ','')

# chats["text"].str.contains(reg, regex=True)
# labeled_chats["chat_id"](["71334"])
# labeled_chats[labeled_chats["reply_to_message_id"]==71331]
# labeled_chats[labeled_chats["reply_to_message_id"].isin([71331])]
# ["chat_id"](["71334"])
x=[1,2,3]
x.extend([2,1])
x
# if["2"]:
#     print(1)
# tx="<IKCO1> و سحاد به احتمال زیاد صف خرید بشند ...	"
# rep=re.sub(rf"\bسحاد\b", f"<سحاد>", tx)
# rep
# re.findall(r"<[آا-ی\s]*>",rep )
# chats["text"].str.replace(r"<[آا-ی\s]*>", '<hi>', regex=True)
# re.findall(, tx)
# labeled_chats.drop(columns=["embedding"]).to_clipboard(sep=',')
# token_count("""",,"<BORS1> <KALA1> پیشنهاد افزایش سرمایه از دو محل سود انباشته و اندوخته داد
# <BORS1> <KALA1> از پیشنهاد هیات مدیره مبنی بر افزایش سرمایه 64 درصدی از دو محل سود انباشته و اندوخته خبر داد .
#  به گزارش پایگاه خبری <BORS1> پرس ، <BORS1> <KALA1> از برنامه افزایش سرمایه 64 درصدی از دو محل سود انباشته و اندوخته خبر داد .
#  بر اساس این گزارش ، "" <KALA1> "" در نظر دارد سرمایه فعلی را از 830 میلیارد به 1.36 هزار میلیارد تومان برساند . تامین مالی این شرکت در صورت موافقت از دو محل سود انباشته و سایر اندوخته‌ها به منظور الزام اجرای مصوبه هیات مدیره سازمان <BORS1> اعمال خواهد شد",گروه هزار تحلیل,1.0""")

[1, 2, 3, 2, 1]

In [173]:
votes = {}
communities = labeled_chats["channel_name"].unique()  ##Telegram groups and channels
for com in communities:
    com_chats = labeled_chats[labeled_chats["channel_name"] == com]
    votes[com] = {}
    print("****", com)
    for index, row in com_chats.iterrows():
        stock_interface = {"buy": set(), "sell": set(), "attention": set()}
        included_stocks = re.findall(r"<([ا-ی]*)>", row["text"])
        print("*_ORG_>", list(set(included_stocks)))
        # if row["text"].str.contains('بررسی|تحلیل|?|؟', regex=True)
        if row["reply_to_message_id"]:
            # com_chats[]
            replied_from = com_chats["reply_to_message_id"].isin(
                [row["reply_to_message_id"]]
            )
            replied_from_stocks = re.findall(r"<([ا-ی]*)>", row["text"])
            included_stocks.extend(replied_from_stocks)
            print("*_EXTEND_ORG_>", included_stocks)
            # print("reply_to_message_id", row["reply_to_message_id"])
        for stock in list(set(included_stocks)):
            votes[com][stock] = (
                votes[com][stock] if (stock in votes[com]) else stock_interface
            )

            print("\t", stock)
            if row["pred"] == 1:
                votes[com][stock]["buy"].add(row["chat_id"])
                # print("\t", "[buy]])", votes[com][stock]["buy"])
            elif row["pred"] == 0:
                votes[com][stock]["sell"].add(row["chat_id"])
                # print("\t", "[sell]])", votes[com][stock]["sell"])
            print("\t", votes[com][stock])

    # print(com_chats["channel_name"].unique())

**** گروه هزار تحلیل
*_ORG_> ['ملت', 'خودرو']
	 ملت
	 {'buy': {361027}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361027}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'کالا']
	 بورس
	 {'buy': {361043}, 'sell': set(), 'attention': set()}
	 کالا
	 {'buy': {361043}, 'sell': set(), 'attention': set()}
*_ORG_> ['خساپا', 'خودرو']
	 خساپا
	 {'buy': {361050}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361050, 361027}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361051, 361043}, 'sell': set(), 'attention': set()}
*_ORG_> ['وخارزم']
	 وخارزم
	 {'buy': {361052}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361051, 361043, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['وخارزم']
	 وخارزم
	 {'buy': {361052, 361054}, 'sell': set(), 'attention': set()}
*_ORG_> ['وتجارت', 'وخارزم']
	 وتجارت
	 {'buy': {361055}, 'sell': set(), 'attention': set()}
	 وخارزم
	 {'buy': {361052, 361054, 361055}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361051, 361043, 361053, 361058}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361061, 361043, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'کالا', 'خودرو']
	 بورس
	 {'buy': {361058, 361061, 361062, 361043, 361051, 361053}, 'sell': set(), 'attention': set()}
	 کالا
	 {'buy': {361058, 361061, 361062, 361043, 361051, 361053}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361050, 361027, 361062}, 'sell': set(), 'attention': set()}
*_ORG_> ['ملت', 'خودرو']
	 ملت
	 {'buy': {361050, 361027, 361062, 361071}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361050, 361027, 361062, 361071}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'حپترو']
	 بورس
	 {'buy': {361058, 361061, 361062, 361043, 361080, 361051, 361053}, 'sell': set(), 'attention': set()}
	 حپترو
	 {'buy': {361080}, 'sell': set(), 'attention': set()}
*_ORG_> ['خاور', 'خساپا', 'شستا', 'خودرو']
	 خاور
	 {'buy': {361083}, 'sell': set(), 'attention': set()}
	 خساپا
	 {'buy': {361050, 361083}, 'sell': set(), 'attention': set()}
	 شستا
	 {'buy': {361083}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361027, 361062, 361071, 361050, 361083}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361027, 361062, 361071, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361027, 361062, 361071, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361027, 361092, 361062, 361071, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['دکوثر']
	 دکوثر
	 {'buy': {361097}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361061, 361062, 361102, 361043, 361080, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['ثشاهد']
	 ثشاهد
	 {'buy': {361106}, 'sell': set(), 'attention': set()}
*_ORG_> ['ددام']
	 ددام
	 {'buy': {361107}, 'sell': set(), 'attention': set()}
*_ORG_> ['کالا']
	 کالا
	 {'buy': {361058, 361061, 361062, 361102, 361043, 361108, 361080, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'کالا', 'خودرو']
	 بورس
	 {'buy': {361058, 361061, 361062, 361102, 361043, 361108, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
	 کالا
	 {'buy': {361058, 361061, 361062, 361102, 361043, 361108, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361027, 361092, 361062, 361071, 361113, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['تپکو']
	 تپکو
	 {'buy': {361116}, 'sell': set(), 'attention': set()}
*_ORG_> ['پارسیان']
	 پارسیان
	 {'buy': {361117}, 'sell': set(), 'attention': set()}
*_ORG_> ['قشکر']
	 قشکر
	 {'buy': {361125}, 'sell': set(), 'attention': set()}
*_ORG_> ['برکت']
	 برکت
	 {'buy': {361127}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361061, 361062, 361130, 361102, 361043, 361108, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['وپارس', 'خساپا', 'شستا']
	 وپارس
	 {'buy': {361131}, 'sell': set(), 'attention': set()}
	 خساپا
	 {'buy': {361050, 361083, 361131}, 'sell': set(), 'attention': set()}
	 شستا
	 {'buy': {361083, 361131}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'کساپا']
	 بورس
	 {'buy': {361058, 361061, 361062, 361130, 361132, 361102, 361043, 361108, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
	 کساپا
	 {'buy': {361132}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'خودرو']
	 بورس
	 {'buy': {361058, 361061, 361062, 361130, 361132, 361102, 361043, 361108, 361143, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361027, 361092, 361062, 361071, 361143, 361113, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['پرداخت']
	 پرداخت
	 {'buy': {361152}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361155, 361061, 361062, 361130, 361132, 361102, 361043, 361108, 361143, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['برکت']
	 برکت
	 {'buy': {361156, 361127}, 'sell': set(), 'attention': set()}
*_ORG_> ['وبملت', 'شستا', 'خودرو', 'خساپا', 'وبصادر']
	 وبملت
	 {'buy': {361157}, 'sell': set(), 'attention': set()}
	 شستا
	 {'buy': {361157, 361083, 361131}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361027, 361092, 361157, 361062, 361071, 361143, 361113, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
	 خساپا
	 {'buy': {361157, 361050, 361083, 361131}, 'sell': set(), 'attention': set()}
	 وبصادر
	 {'buy': {361157}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361155, 361061, 361062, 361130, 361162, 361132, 361102, 361043, 361108, 361143, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['تکنو']
	 تکنو
	 {'buy': {361166}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361027, 361092, 361157, 361062, 361071, 361171, 361143, 361113, 361050, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361155, 361061, 361062, 361130, 361162, 361132, 361102, 361043, 361108, 361177, 361143, 361080, 361113, 361051, 361053}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361058, 361155, 361061, 361062, 361130, 361162, 361132, 361102, 361043, 361108, 361177, 361143, 361080, 361113, 361051, 361053, 361179}, 'sell': set(), 'attention': set()}
*_ORG_> ['پارس', 'خودرو']
	 پارس
	 {'buy': {361180}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361027, 361092, 361157, 361062, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['دارو']
	 دارو
	 {'buy': {361181}, 'sell': set(), 'attention': set()}
*_ORG_> ['امید', 'خودرو']
	 امید
	 {'buy': {361183}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361027, 361092, 361157, 361062, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361184, 361027, 361092, 361157, 361062, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361184, 361027, 361092, 361157, 361062, 361191, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361184, 361027, 361092, 361157, 361062, 361191, 361198, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'پرداخت']
	 بورس
	 {'buy': {361058, 361155, 361061, 361062, 361130, 361162, 361132, 361102, 361043, 361108, 361177, 361206, 361143, 361080, 361113, 361051, 361053, 361179}, 'sell': set(), 'attention': set()}
	 پرداخت
	 {'buy': {361152, 361206}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361102, 361108, 361113, 361130, 361132, 361143, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['خساپا', 'وکار', 'شستا']
	 خساپا
	 {'buy': {361157, 361131, 361050, 361083, 361211}, 'sell': set(), 'attention': set()}
	 وکار
	 {'buy': {361211}, 'sell': set(), 'attention': set()}
	 شستا
	 {'buy': {361157, 361083, 361131, 361211}, 'sell': set(), 'attention': set()}
*_ORG_> ['امید']
	 امید
	 {'buy': {361221, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'امین', 'امید', 'خودرو']
	 بورس
	 {'buy': {361223, 361102, 361108, 361113, 361130, 361132, 361143, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
	 امین
	 {'buy': {361223}, 'sell': set(), 'attention': set()}
	 امید
	 {'buy': {361223, 361221, 361183}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361184, 361027, 361092, 361157, 361062, 361191, 361223, 361198, 361071, 361171, 361143, 361113, 361050, 361083, 361180, 361086, 361183}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361130, 361132, 361143, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['چکارن']
	 چکارن
	 {'buy': {361235}, 'sell': set(), 'attention': set()}
*_ORG_> ['چکاپا']
	 چکاپا
	 {'buy': {361236}, 'sell': set(), 'attention': set()}
*_ORG_> ['شبندر']
	 شبندر
	 {'buy': {361239}, 'sell': set(), 'attention': set()}
*_ORG_> ['شپدیس']
	 شپدیس
	 {'buy': {361240}, 'sell': set(), 'attention': set()}
*_ORG_> ['خگستر']
	 خگستر
	 {'buy': {361241}, 'sell': set(), 'attention': set()}
*_ORG_> ['کساپا']
	 کساپا
	 {'buy': {361242, 361132}, 'sell': set(), 'attention': set()}
*_ORG_> []
*_ORG_> ['شبندر']
	 شبندر
	 {'buy': {361246, 361239}, 'sell': set(), 'attention': set()}
*_ORG_> ['دارو']
	 دارو
	 {'buy': {361249, 361181}, 'sell': set(), 'attention': set()}
*_ORG_> ['خپارس', 'خساپا', 'خزامیا']
	 خپارس
	 {'buy': {361254}, 'sell': set(), 'attention': set()}
	 خساپا
	 {'buy': {361157, 361254, 361131, 361050, 361083, 361211}, 'sell': set(), 'attention': set()}
	 خزامیا
	 {'buy': {361254}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361130, 361132, 361143, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['میدکو']
	 میدکو
	 {'buy': {361261}, 'sell': set(), 'attention': set()}
*_ORG_> ['ملت', 'خودرو']
	 ملت
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361027, 361157, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361027, 361157, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['خساپا', 'شستا', 'خودرو']
	 خساپا
	 {'buy': {361157, 361254, 361131, 361050, 361083, 361278, 361211}, 'sell': set(), 'attention': set()}
	 شستا
	 {'buy': {361157, 361131, 361083, 361278, 361211}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361027, 361157, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'خودرو']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361279, 361027, 361157, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361280, 361155, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361280, 361155, 361284, 361162, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['امین', 'خودرو']
	 امین
	 {'buy': {361285, 361223}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361279, 361027, 361157, 361285, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['شبندر']
	 شبندر
	 {'buy': {361288, 361246, 361239}, 'sell': set(), 'attention': set()}
*_ORG_> ['ملت']
	 ملت
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361279, 361027, 361157, 361285, 361289, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'خودرو']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361280, 361155, 361284, 361162, 361295, 361043, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361279, 361027, 361157, 361285, 361289, 361295, 361171, 361050, 361180, 361183, 361184, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361280, 361155, 361284, 361162, 361295, 361043, 361299, 361177, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'کگاز']
	 بورس
	 {'buy': {361223, 361102, 361234, 361108, 361113, 361256, 361257, 361130, 361132, 361143, 361279, 361280, 361155, 361284, 361162, 361295, 361043, 361299, 361177, 361306, 361051, 361179, 361053, 361058, 361061, 361062, 361206, 361080, 361210}, 'sell': set(), 'attention': set()}
	 کگاز
	 {'buy': {361306}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {361088, 361092, 361223, 361113, 361263, 361143, 361278, 361279, 361027, 361157, 361285, 361289, 361295, 361171, 361050, 361180, 361183, 361184, 361311, 361062, 361191, 361198, 361071, 361083, 361086}, 'sell': set(), 'attention': set()}
**** گروه بازار
*_ORG_> ['همراه']
	 همراه
	 {'buy': {751441}, 'sell': set(), 'attention': set()}
*_ORG_> ['فلامی', 'حتاید']
	 فلامی
	 {'buy': {751447}, 'sell': set(), 'attention': set()}
	 حتاید
	 {'buy': {751447}, 'sell': set(), 'attention': set()}
*_ORG_> ['کترام']
	 کترام
	 {'buy': {751458}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {751462}, 'sell': set(), 'attention': set()}
*_ORG_> ['شفا']
	 شفا
	 {'buy': {751467}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {751476, 751462}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس']
	 بورس
	 {'buy': {751480, 751476, 751462}, 'sell': set(), 'attention': set()}
*_ORG_> ['فلامی']
	 فلامی
	 {'buy': {751493, 751447}, 'sell': set(), 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': {751505}, 'sell': set(), 'attention': set()}
**** بورسگرام | Boursegram
*_ORG_> ['شستا']
	 شستا
	 {'buy': {71138}, 'sell': set(), 'attention': set()}
*_ORG_> ['بورس', 'ختور', 'خگستر', 'خمحرکه']
	 بورس
	 {'buy': {71151}, 'sell': set(), 'attention': set()}
	 ختور
	 {'buy': {71151}, 'sell': set(), 'attention': set()}
	 خگستر
	 {'buy': {71151}, 'sell': set(), 'attention': set()}
	 خمحرکه
	 {'buy': {71151}, 'sell': set(), 'attention': set()}
*_ORG_> ['خساپا']
	 خساپا
	 {'buy': {71156}, 'sell': set(), 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['کماسه', 'دامین', 'سپید']
	 کماسه
	 {'buy': set(), 'sell': {71165}, 'attention': set()}
	 دامین
	 {'buy': set(), 'sell': {71165}, 'attention': set()}
	 سپید
	 {'buy': set(), 'sell': {71165}, 'attention': set()}
*_ORG_> ['کماسه', 'دامین', 'سپید']
	 کماسه
	 {'buy': set(), 'sell': {71165, 71166}, 'attention': set()}
	 دامین
	 {'buy': set(), 'sell': {71165, 71166}, 'attention': set()}
	 سپید
	 {'buy': set(), 'sell': {71165, 71166}, 'attention': set()}
*_ORG_> ['کماسه', 'دامین', 'سپید']
	 کماسه
	 {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()}
	 دامین
	 {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()}
	 سپید
	 {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()}
*_ORG_> ['حکشتی', 'خزامیا']
	 حکشتی
	 {'buy': set(), 'sell': {71170}, 'attention': set()}
	 خزامیا
	 {'buy': set(), 'sell': {71170}, 'attention': set()}
*_ORG_> ['حکشتی']
	 حکشتی
	 {'buy': set(), 'sell': {71170, 71171}, 'attention': set()}
*_ORG_> ['خودرو']
	 خودرو
	 {'buy': set(), 'sell': {71173}, 'attention': set()}
*_ORG_> ['خزامیا']
	 خزامیا
	 {'buy': set(), 'sell': {71170, 71171, 71174}, 'attention': set()}
*_ORG_> ['خزامیا']
*_EXTEND_ORG_> ['خزامیا', 'خزامیا']
	 خزامیا
	 {'buy': set(), 'sell': {71170, 71171, 71174, 71175}, 'attention': set()}
*_ORG_> ['خودرو', 'خزامیا']
*_EXTEND_ORG_> ['خزامیا', 'خودرو', 'خزامیا', 'خودرو']
	 خودرو
	 {'buy': set(), 'sell': {71176, 71173}, 'attention': set()}
	 خزامیا
	 {'buy': set(), 'sell': {71170, 71171, 71174, 71175, 71176}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['دزهراوی']
	 دزهراوی
	 {'buy': set(), 'sell': {71186}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['غبهنوش']
	 غبهنوش
	 {'buy': set(), 'sell': {71188}, 'attention': set()}
*_ORG_> ['غبهنوش']
	 غبهنوش
	 {'buy': set(), 'sell': {71188, 71191}, 'attention': set()}
*_ORG_> ['غزر']
	 غزر
	 {'buy': set(), 'sell': {71196}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['غبهنوش']
	 غبهنوش
	 {'buy': set(), 'sell': {71188, 71204, 71191}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['ختور']
	 ختور
	 {'buy': {71151}, 'sell': {71219}, 'attention': set()}
*_ORG_> ['غبهنوش']
*_EXTEND_ORG_> ['غبهنوش', 'غبهنوش']
	 غبهنوش
	 {'buy': set(), 'sell': {71188, 71220, 71204, 71191}, 'attention': set()}
*_ORG_> ['خمحرکه']
	 خمحرکه
	 {'buy': {71151}, 'sell': {71219, 71221}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['امید']
	 امید
	 {'buy': set(), 'sell': {71227}, 'attention': set()}
*_ORG_> ['خساپا']
	 خساپا
	 {'buy': {71156}, 'sell': {71232}, 'attention': set()}
*_ORG_> ['خساپا']
	 خساپا
	 {'buy': {71156}, 'sell': {71232, 71233}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []
*_ORG_> ['خودرو']
*_EXTEND_ORG_> ['خودرو', 'خودرو']
	 خودرو
	 {'buy': set(), 'sell': {71176, 71242, 71173}, 'attention': set()}
*_ORG_> ['خساپا', 'خودرو']
*_EXTEND_ORG_> ['خودرو', 'خساپا', 'خودرو', 'خساپا']
	 خساپا
	 {'buy': {71156}, 'sell': {71232, 71233, 71245}, 'attention': set()}
	 خودرو
	 {'buy': set(), 'sell': {71176, 71242, 71245, 71173}, 'attention': set()}
*_ORG_> ['خگستر']
	 خگستر
	 {'buy': {71151}, 'sell': {71219, 71221, 71246}, 'attention': set()}
*_ORG_> ['بورس']
*_EXTEND_ORG_> ['بورس', 'بورس']
	 بورس
	 {'buy': {71151}, 'sell': {71219, 71221, 71246, 71247}, 'attention': set()}
*_ORG_> []
*_EXTEND_ORG_> []

In [127]:
votes

{'گروه هزار تحلیل': {'ملت': {'buy': {361027,
    361050,
    361062,
    361071,
    361083,
    361086,
    361088,
    361092,
    361113,
    361143,
    361157,
    361171,
    361180,
    361183,
    361184,
    361191,
    361198,
    361223,
    361263,
    361278,
    361279,
    361285,
    361289,
    361295,
    361311},
   'sell': set(),
   'attention': set()},
  'خودرو': {'buy': {361027,
    361050,
    361062,
    361071,
    361083,
    361086,
    361088,
    361092,
    361113,
    361143,
    361157,
    361171,
    361180,
    361183,
    361184,
    361191,
    361198,
    361223,
    361263,
    361278,
    361279,
    361285,
    361289,
    361295,
    361311},
   'sell': set(),
   'attention': set()},
  'بورس': {'buy': {361043,
    361051,
    361053,
    361058,
    361061,
    361062,
    361080,
    361102,
    361108,
    361113,
    361130,
    361132,
    361143,
    361155,
    361162,
    361177,
    361179,
    361206,
    361210,
    361223,
    361234,
    361256,
    361257,
    361279,
    361280,
    361284,
    361295,
    361299,
    361306},
   'sell': set(),
   'attention': set()},
  'کالا': {'buy': {361043,
    361051,
    361053,
    361058,
    361061,
    361062,
    361080,
    361102,
    361108,
    361113,
    361130,
    361132,
    361143,
    361155,
    361162,
    361177,
    361179,
    361206,
    361210,
    361223,
    361234,
    361256,
    361257,
    361279,
    361280,
    361284,
    361295,
    361299,
    361306},
   'sell': set(),
   'attention': set()},
  'خساپا': {'buy': {361050, 361083, 361131, 361157, 361211, 361254, 361278},
   'sell': set(),
   'attention': set()},
  'وخارزم': {'buy': {361052, 361054, 361055},
   'sell': set(),
   'attention': set()},
  'وتجارت': {'buy': {361055}, 'sell': set(), 'attention': set()},
  'حپترو': {'buy': {361080}, 'sell': set(), 'attention': set()},
  'خاور': {'buy': {361083, 361131, 361157, 361211, 361278},
   'sell': set(),
   'attention': set()},
  'شستا': {'buy': {361083, 361131, 361157, 361211, 361278},
   'sell': set(),
   'attention': set()},
  'دکوثر': {'buy': {361097}, 'sell': set(), 'attention': set()},
  'ثشاهد': {'buy': {361106}, 'sell': set(), 'attention': set()},
  'ددام': {'buy': {361107}, 'sell': set(), 'attention': set()},
  'تپکو': {'buy': {361116}, 'sell': set(), 'attention': set()},
  'پارسیان': {'buy': {361117}, 'sell': set(), 'attention': set()},
  'قشکر': {'buy': {361125}, 'sell': set(), 'attention': set()},
  'برکت': {'buy': {361127, 361156}, 'sell': set(), 'attention': set()},
  'وپارس': {'buy': {361131}, 'sell': set(), 'attention': set()},
  'کساپا': {'buy': {361132, 361242}, 'sell': set(), 'attention': set()},
  'پرداخت': {'buy': {361152, 361206}, 'sell': set(), 'attention': set()},
  'وبملت': {'buy': {361157}, 'sell': set(), 'attention': set()},
  'وبصادر': {'buy': {361157}, 'sell': set(), 'attention': set()},
  'تکنو': {'buy': {361166}, 'sell': set(), 'attention': set()},
  'پارس': {'buy': {361180}, 'sell': set(), 'attention': set()},
  'دارو': {'buy': {361181, 361249}, 'sell': set(), 'attention': set()},
  'امید': {'buy': {361183, 361221, 361223}, 'sell': set(), 'attention': set()},
  'وکار': {'buy': {361211}, 'sell': set(), 'attention': set()},
  'امین': {'buy': {361223, 361285}, 'sell': set(), 'attention': set()},
  'چکارن': {'buy': {361235}, 'sell': set(), 'attention': set()},
  'چکاپا': {'buy': {361236}, 'sell': set(), 'attention': set()},
  'شبندر': {'buy': {361239, 361246, 361288},
   'sell': set(),
   'attention': set()},
  'شپدیس': {'buy': {361240}, 'sell': set(), 'attention': set()},
  'خگستر': {'buy': {361241}, 'sell': set(), 'attention': set()},
  'خپارس': {'buy': {361254}, 'sell': set(), 'attention': set()},
  'خزامیا': {'buy': {361254}, 'sell': set(), 'attention': set()},
  'میدکو': {'buy': {361261}, 'sell': set(), 'attention': set()},
  'کگاز': {'buy': {361306}, 'sell': set(), 'attention': set()}},
 'گروه بازار': {'همراه': {'buy': {751441}, 'sell': set(), 'attention': set()},
  'فلامی': {'buy': {751447, 751493}, 'sell': set(), 'attention': set()},
  'حتاید': {'buy': {751447, 751493}, 'sell': set(), 'attention': set()},
  'کترام': {'buy': {751458}, 'sell': set(), 'attention': set()},
  'بورس': {'buy': {751462, 751476, 751480}, 'sell': set(), 'attention': set()},
  'شفا': {'buy': {751467}, 'sell': set(), 'attention': set()},
  'خودرو': {'buy': {751505}, 'sell': set(), 'attention': set()}},
 'بورسگرام | Boursegram': {'شستا': {'buy': {71138},
   'sell': set(),
   'attention': set()},
  'بورس': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'ختور': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خگستر': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خمحرکه': {'buy': {71151},
   'sell': {71219, 71221, 71246, 71247, 71275, 71326, 71327},
   'attention': set()},
  'خساپا': {'buy': {71156}, 'sell': {71232, 71233, 71245}, 'attention': set()},
  'کماسه': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'دامین': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'سپید': {'buy': set(), 'sell': {71165, 71166, 71167}, 'attention': set()},
  'حکشتی': {'buy': set(),
   'sell': {71170, 71171, 71174, 71175, 71176},
   'attention': set()},
  'خزامیا': {'buy': set(),
   'sell': {71170, 71171, 71174, 71175, 71176},
   'attention': set()},
  'خودرو': {'buy': set(),
   'sell': {71173, 71176, 71242, 71245, 71276},
   'attention': set()},
  'دزهراوی': {'buy': set(), 'sell': {71186}, 'attention': set()},
  'غبهنوش': {'buy': set(),
   'sell': {71188, 71191, 71204, 71220},
   'attention': set()},
  'غزر': {'buy': set(), 'sell': {71196}, 'attention': set()},
  'امید': {'buy': set(), 'sell': {71227}, 'attention': set()},
  'فاراک': {'buy': set(), 'sell': {71306}, 'attention': set()},
  'کرازیح': {'buy': set(), 'sell': {71308}, 'attention': set()},
  'خپارس': {'buy': set(), 'sell': {71317}, 'attention': set()},
  'خنصیر': {'buy': set(), 'sell': {71323}, 'attention': set()},
  'کالا': {'buy': set(), 'sell': {71326}, 'attention': set()}}}

In [202]:
# # @ BOUNDS : []
# # chat_list
# telegram_chanells = [chat_list_2, chat_list_2]

# channels_limit_bound = []
# for chanell in telegram_chanells:
#     chanell_bound = []
#     token_count = 0
#     i = 0
#     while i < len(chanell):
#         chat = chanell[i]
#         chat_tokens_count = len(enc.encode(chat["text"]))
#         # print(i)
#         if token_count + chat_tokens_count > 8192 :
#             # print(i,len(chanell),chat_tokens_count,token_count,token_count + chat_tokens_count > 4096,i + 1 == len(chanell),)
            
#             chanell_bound.append(i - 1)
#             token_count = 0
#         elif i + 1 == len(chanell):
#             chanell_bound.append(i)
#             token_count = 0
#             i += 1
#         else:
#             token_count += chat_tokens_count
#             i += 1
#     channels_limit_bound.append(chanell_bound)
# channels_limit_bound

In [74]:

# for _ in range(100):
#     completion_with_backoff()
#     print(_)

In [155]:
enc = tiktoken.get_encoding("cl100k_base")
x = """۷ ملک دیگر بانک فرابورسی کارشناسی شدند/ افزایش ارزش دارایی‌ها
به گزارش پایگاه خبری بورس پرس، به‌دنبال ارائه پیشین گزارش‌های کارشناسی املاک بانک آینده در سامانه کدال، ارزیابی‌های جدیدی از املاک این بانک حاضر در بازار پایه و غایب 19 ماهه از تابلو معاملات افشا شد.
🔹بر اساس این گزارش، املاک و دارایی‌های ارزیابی شده از شرکت‌های زیرمجموعه بانک آینده که توسط هیأت کارشناسان رسمی دادگستری مرکز وکلا و کارشناسان رسمی قوه قضائیه انجام شده، بیانگر افزایش ارزش چشمگیر دارایی‌های مزبور، نسبت به گذشته است.
🔹جدیدترین موارد افشا شامل ملک سعادت آباد متعلق به شرکت تجارت الکترونیک فردا، ملک شیخ بهایی متعلق به شرکت توسعه تجارت نگین بینالود، ملک جردن متعلق به شرکت دقایق‌گستر پویا، املاک زرتشت و حکیم متعلق به شرکت آشیان‌سازان کیهان،"""
len(enc.encode(x))

510

In [140]:
# %%time
# def add(x, y):
#     return  x+y['text']
#     # return  x+"**"+y

# # list = [2, 4, 7, 3]
# reduce(add, telegram_chanells[0][:7+1],"")

# def concatenate_chanell_chat(chanell):
#     chats=""
#     for chat in chanell:
#         # chats+=("\n".join(chat['text'])+"**")
#         chats+=chat['text']
#     return chats

# x==concatenate_chanell_chat(telegram_chanells[0][:7+1])
# telegram_chanells[0][:7+1]

In [67]:
import os


# openai.Model.retrieve("gpt-3.5-turbo")
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )
# embeddings = response['data'][0]['embedding']
def request_openai(prompt):
    return openai.Completion.create(
        model="gpt-3.5-turbo", prompt="generate some ", temperature=1, max_tokens=5
    )

In [71]:
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )

# import os
# import openai

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello!"}]
)

completion
completion
# print(completion.choices[0].message)
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")

<OpenAIObject chat.completion id=chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN at 0x7fcde1e1c770> JSON: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello there! How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "created": 1683976467,
  "id": "chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 10,
    "prompt_tokens": 10,
    "total_tokens": 20
  }
}

In [105]:
# print(completion)
# print(completion)
# print(completion)
# print(completion)
# for i in range(20):
#     openai.ChatCompletion.create(
#   model="gpt-3.5-turbo",
#   messages=[
#     {"role": "user", "content": "Hello!"}
#   ]
# )

In [108]:
len(enc.encode("Hello!" * 1000))

2000

In [83]:
%! pip install tenacity

Collecting tenacity
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
WARNING: Error parsing requirements for matplotlib: [Errno 2] No such file or directory: '/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/matplotlib-3.7.1.dist-info/METADATA'
Installing collected packages: tenacity
Successfully installed tenacity-8.2.2