In [98]:
import tiktoken
import os
from parsivar import Normalizer
import pandas as pd
import json
import shortuuid
import regex as re
import time
from functools import reduce
import openai  # for OpenAI API calls
from tenacity import (
    retry,
    stop_after_attempt,
    wait_random_exponential,
)  # for exponential backoff


# from openai.embeddings_utils import get_embedding, cosine_similarity;
# import matplotlib

### Openai api notes for embedding

1. Embedding :
*  Each input must not exceed 8192 tokens in length.
* Model Name =>  text-embedding-ada-002

In [14]:
uuid = shortuuid.ShortUUID(alphabet="0123456789abcdefghijklmnopqrstuvwxyz")
enc = tiktoken.get_encoding("cl100k_base")
pd.set_option('display.max_rows', None)

In [15]:
with open('../../dataset/majid/result.json', encoding='utf-8') as file:
    maj = json.loads(file.read())
maj

{'name': 'مجید سلطانی',
 'type': 'public_channel',
 'id': 1082829946,
 'messages': [{'id': 65685,
   'type': 'message',
   'date': '2023-04-30T08:48:19',
   'date_unixtime': '1682831899',
   'edited': '2023-04-30T08:48:25',
   'edited_unixtime': '1682831905',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': 'صبح یکشنبه همگی به خیر و خوشی 🌷🙏',
   'text_entities': [{'type': 'plain',
     'text': 'صبح یکشنبه همگی به خیر و خوشی 🌷🙏'}]},
  {'id': 65686,
   'type': 'message',
   'date': '2023-04-30T09:08:01',
   'date_unixtime': '1682833081',
   'edited': '2023-04-30T09:09:24',
   'edited_unixtime': '1682833164',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': [{'type': 'hashtag', 'text': '#فسپا'},
    ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'],
   'text_entities': [{'type': 'hashtag', 'text': 'فسپا'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'},
    {'type': 'plain',
     'text': ' در آستانه صف خرید به دلیل رشد ۵۰ درصدی متوقف شد'}]},
  {'id': 65687,
   'type': 'message',
   'date': '2023-04-30T09:10:52',
   'date_unixtime': '1682833252',
   'edited': '2023-04-30T09:11:24',
   'edited_unixtime': '1682833284',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'reply_to_message_id': 65676,
   'text': [{'type': 'hashtag', 'text': '#شنفت'},
    ' اولین نفوذ به بالای سقف تاریخی بعد از ۳ سال'],
   'text_entities': [{'type': 'hashtag', 'text': '#شنفت'},
    {'type': 'plain',
     'text': ' اولین نفوذ به بالای سقف تاریخی بعد از ۳ سال'}]},
  {'id': 65688,
   'type': 'message',
   'date': '2023-04-30T09:23:02',
   'date_unixtime': '1682833982',
   'edited': '2023-04-30T09:23:13',
   'edited_unixtime': '1682833993',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'reply_to_message_id': 65678,
   'text': [{'type': 'hashtag', 'text': '#کهمدا'},
    ' یک قدم تا شکست سقف تاریخی مانده که امروز این یک قدم هم برداشته میشه'],
   'text_entities': [{'type': 'hashtag', 'text': '#کهمدا'},
    {'type': 'plain',
     'text': ' یک قدم تا شکست سقف تاریخی مانده که امروز این یک قدم هم برداشته میشه'}]},
  {'id': 65689,
   'type': 'message',
   'date': '2023-04-30T09:48:33',
   'date_unixtime': '1682835513',
   'edited': '2023-04-30T09:48:46',
   'edited_unixtime': '1682835526',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': ['پیشنهاد خرید مجدد\n\n',
    {'type': 'hashtag', 'text': '#کروی'},
    ' قیمت تابلو امروز'],
   'text_entities': [{'type': 'plain', 'text': 'پیشنهاد خرید مجدد\n\n'},
    {'type': 'hashtag', 'text': '#کروی'},
    {'type': 'plain', 'text': ' قیمت تابلو امروز'}]},
  {'id': 65690,
   'type': 'message',
   'date': '2023-04-30T09:50:17',
   'date_unixtime': '1682835617',
   'edited': '2023-04-30T09:50:45',
   'edited_unixtime': '1682835645',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': [{'type': 'hashtag', 'text': '#کروی'},
    ' در این قیمتها ارزش خرید مجدد داره\nچه برای کسانی که قبلا داشتند و چه کسانی که تازه می خوان بخرن'],
   'text_entities': [{'type': 'hashtag', 'text': '#کروی'},
    {'type': 'plain',
     'text': ' در این قیمتها ارزش خرید مجدد داره\nچه برای کسانی که قبلا داشتند و چه کسانی که تازه می خوان بخرن'}]},
  {'id': 65691,
   'type': 'message',
   'date': '2023-04-30T09:51:36',
   'date_unixtime': '1682835696',
   'edited': '2023-04-30T09:52:48',
   'edited_unixtime': '1682835768',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': 'تابلو سهم نشون میده که با قرار دادن اردر ترس در ۴۶۰۰ تومان، در حال جمع کردن زیر این قیمت هستند.',
   'text_entities': [{'type': 'plain',
     'text': 'تابلو سهم نشون میده که با قرار دادن اردر ترس در ۴۶۰۰ تومان، در حال جمع کردن زیر این قیمت هستند.'}]},
  {'id': 65692,
   'type': 'message',
   'date': '2023-04-30T10:09:05',
   'date_unixtime': '1682836745',
   'edited': '2023-04-30T10:09:26',
   'edited_unixtime': '1682836766',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': [{'type': 'hashtag', 'text': '#دکیمی'}, ' بازگشایی'],
   'text_entities': [{'type': 'hashtag', 'text': '#دکیمی'},
    {'type': 'plain', 'text': ' بازگشایی'}]},
  {'id': 65693,
   'type': 'message',
   'date': '2023-04-30T10:13:01',
   'date_unixtime': '1682836981',
   'edited': '2023-04-30T10:13:43',
   'edited_unixtime': '1682837023',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': ['نگاهی به سهمی مثل ',
    {'type': 'hashtag', 'text': '#ددام'},
    ' با پی بر ای ۲۲ بندازید که هر روز صف خریده! متوجه ارزش ',
    {'type': 'hashtag', 'text': '#دکیمی'},
    ' با پی بر ای ۹ می شید!\nنوبت این سهم هم خواهد رسید'],
   'text_entities': [{'type': 'plain', 'text': 'نگاهی به سهمی مثل '},
    {'type': 'hashtag', 'text': '#ددام'},
    {'type': 'plain',
     'text': ' با پی بر ای ۲۲ بندازید که هر روز صف خریده! متوجه ارزش '},
    {'type': 'hashtag', 'text': '#دکیمی'},
    {'type': 'plain',
     'text': ' با پی بر ای ۹ می شید!\nنوبت این سهم هم خواهد رسید'}]},
  {'id': 65694,
   'type': 'message',
   'date': '2023-04-30T10:22:31',
   'date_unixtime': '1682837551',
   'edited': '2023-04-30T10:29:51',
   'edited_unixtime': '1682837991',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'file': '(File not included. Change data exporting settings to download.)',
   'thumbnail': '(File not included. Change data exporting settings to download.)',
   'media_type': 'sticker',
   'sticker_emoji': '⬇️',
   'width': 512,
   'height': 512,
   'text': '',
   'text_entities': []},
  {'id': 65695,
   'type': 'message',
   'date': '2023-04-30T10:22:31',
   'date_unixtime': '1682837551',
   'edited': '2023-04-30T10:24:30',
   'edited_unixtime': '1682837670',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'forwarded_from': 'کارگزاری فارابی',
   'photo': 'photos/photo_3664@30-04-2023_10-22-31.jpg',
   'width': 1080,
   'height': 1080,
   'text': ['✅',
    {'type': 'bold',
     'text': 'با انتخاب صندوق سهامی سلام فارابی(ETF)، برترین سهم\u200cهای بازار را به پرتفوی خود اضافه کنید.\n\n'},
    '🔹سرمایه\u200cگذارانی که',
    {'type': 'bold', 'text': ' آبان ماه'},
    ' گذشته ',
    {'type': 'bold', 'text': 'نماد سلام'},
    ' را به پرتفوی خود اضافه کرده\u200cاند، امروز ارزش دارایی\u200cشان',
    {'type': 'bold', 'text': ' بیش از ۱۲۶ درصد '},
    'رشد کرده است.\n\n▪️برای خرید کافیست نماد ',
    {'type': 'bold', 'text': '«سلام»'},
    ' را در سامانه کارگزاری خود جستجو کنید.\n\n🔻',
    {'type': 'bold', 'text': 'اطلاعات بیشتر'},
    ' در لینک زیر :\n\n',
    {'type': 'link', 'text': 'https://fxo.is/slmfds'},
    {'type': 'bold', 'text': '\n\n'},
    '____     \n🆔 ',
    {'type': 'mention', 'text': '@farabinvest'},
    ''],
   'text_entities': [{'type': 'plain', 'text': '✅'},
    {'type': 'bold',
     'text': 'با انتخاب صندوق سهامی سلام فارابی(ETF)، برترین سهم\u200cهای بازار را به پرتفوی خود اضافه کنید.\n\n'},
    {'type': 'plain', 'text': '🔹سرمایه\u200cگذارانی که'},
    {'type': 'bold', 'text': ' آبان ماه'},
    {'type': 'plain', 'text': ' گذشته '},
    {'type': 'bold', 'text': 'نماد سلام'},
    {'type': 'plain',
     'text': ' را به پرتفوی خود اضافه کرده\u200cاند، امروز ارزش دارایی\u200cشان'},
    {'type': 'bold', 'text': ' بیش از ۱۲۶ درصد '},
    {'type': 'plain', 'text': 'رشد کرده است.\n\n▪️برای خرید کافیست نماد '},
    {'type': 'bold', 'text': '«سلام»'},
    {'type': 'plain', 'text': ' را در سامانه کارگزاری خود جستجو کنید.\n\n🔻'},
    {'type': 'bold', 'text': 'اطلاعات بیشتر'},
    {'type': 'plain', 'text': ' در لینک زیر :\n\n'},
    {'type': 'link', 'text': 'https://fxo.is/slmfds'},
    {'type': 'bold', 'text': '\n\n'},
    {'type': 'plain', 'text': '____     \n🆔 '},
    {'type': 'mention', 'text': '@farabinvest'},
    {'type': 'plain', 'text': ''}]},
  {'id': 65696,
   'type': 'message',
   'date': '2023-04-30T10:23:58',
   'date_unixtime': '1682837638',
   'edited': '2023-04-30T10:24:05',
   'edited_unixtime': '1682837645',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': ['این سبدی که چیدیم انصافا سبدی کمریسک و  پربازده بوده و خواهد بود. ایده آل برای یک سهامداری بی دغدغه\n\n',
    {'type': 'hashtag', 'text': '#شنفت'},
    ' ',
    {'type': 'hashtag', 'text': '#فسپا'},
    ' ',
    {'type': 'hashtag', 'text': '#کهمدا'},
    ' ',
    {'type': 'hashtag', 'text': '#کروی'},
    ' ',
    {'type': 'hashtag', 'text': '#دکیمی'},
    ' \n\nبزودی با چند سهم مناسب دیگه سبدمون را تکمیل می کنیم.'],
   'text_entities': [{'type': 'plain',
     'text': 'این سبدی که چیدیم انصافا سبدی کمریسک و  پربازده بوده و خواهد بود. ایده آل برای یک سهامداری بی دغدغه\n\n'},
    {'type': 'hashtag', 'text': '#شنفت'},
    {'type': 'plain', 'text': ' '},
    {'type': 'hashtag', 'text': '#فسپا'},
    {'type': 'plain', 'text': ' '},
    {'type': 'hashtag', 'text': '#کهمدا'},
    {'type': 'plain', 'text': ' '},
    {'type': 'hashtag', 'text': '#کروی'},
    {'type': 'plain', 'text': ' '},
    {'type': 'hashtag', 'text': '#دکیمی'},
    {'type': 'plain',
     'text': ' \n\nبزودی با چند سهم مناسب دیگه سبدمون را تکمیل می کنیم.'}]},
  {'id': 65697,
   'type': 'message',
   'date': '2023-04-30T10:32:42',
   'date_unixtime': '1682838162',
   'edited': '2023-04-30T10:32:54',
   'edited_unixtime': '1682838174',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'file': '(File not included. Change data exporting settings to download.)',
   'thumbnail': '(File not included. Change data exporting settings to download.)',
   'media_type': 'video_file',
   'mime_type': 'video/mp4',
   'duration_seconds': 84,
   'width': 426,
   'height': 240,
   'text': [{'type': 'bold',
     'text': 'وزیر صمت در مجلس: رئیس مجلس شما پیگیری کنید کدام شرکت است که وقتی به منافعش نمی\u200cرسد، معاون بنده را ضرب\u200cوشتم می\u200cکند'},
    '!'],
   'text_entities': [{'type': 'bold',
     'text': 'وزیر صمت در مجلس: رئیس مجلس شما پیگیری کنید کدام شرکت است که وقتی به منافعش نمی\u200cرسد، معاون بنده را ضرب\u200cوشتم می\u200cکند'},
    {'type': 'plain', 'text': '!'}]},
  {'id': 65698,
   'type': 'message',
   'date': '2023-04-30T10:41:01',
   'date_unixtime': '1682838661',
   'edited': '2023-04-30T10:41:15',
   'edited_unixtime': '1682838675',
   'from': 'مجید سلطانی',
   'from_id': 'channel1082829946',
   'text': [{'type': 'hashtag', 'text': '#دکیمی'}, ' صف خرید شد'],
   'text_entities': [{'type': 'hashtag', 'text': '#دکیمی'},

In [16]:
with open('../../dataset/BOURSGRAM/boursgram.json', encoding='utf-8') as file:
    boursgram_data = json.loads(file.read())
boursgram_data

{'name': 'بورسگرام | Boursegram',
 'type': 'public_supergroup',
 'id': 1727038436,
 'messages': [{'id': 71117,
   'type': 'message',
   'date': '2023-05-14T00:08:53',
   'date_unixtime': '1684010333',
   'from': 'ᴍᴀɴɪ_ᴀʀꜱɪɴ',
   'from_id': 'user5242220299',
   'reply_to_message_id': 70323,
   'text': 'سلام با توجه به اصلاح اخیر بازار تقریبا میشه گفت اکثریت بازار اصلاح کرده، در منفی ها و بصورت پله ای خرید کنید',
   'text_entities': [{'type': 'plain',
     'text': 'سلام با توجه به اصلاح اخیر بازار تقریبا میشه گفت اکثریت بازار اصلاح کرده، در منفی ها و بصورت پله ای خرید کنید'}]},
  {'id': 71118,
   'type': 'message',
   'date': '2023-05-14T00:09:27',
   'date_unixtime': '1684010367',
   'edited': '2023-05-14T01:48:39',
   'edited_unixtime': '1684016319',
   'from': 'ᴍᴀɴɪ_ᴀʀꜱɪɴ',
   'from_id': 'user5242220299',
   'reply_to_message_id': 71114,
   'text': 'سلام هر دو سهم های بنیادی و ارزنده ای هستن به دید بلند مدت',
   'text_entities': [{'type': 'plain',
     'text': 'سلام هر دو سهم های بنیادی و ارزنده ای هستن به دید بلند مدت'}]},
  {'id': 71119,
   'type': 'message',
   'date': '2023-05-14T00:14:30',
   'date_unixtime': '1684010670',
   'from': 'Hossein Moradzadeh',
   'from_id': 'user1275940942',
   'reply_to_message_id': 71113,
   'text': '👍',
   'text_entities': [{'type': 'plain', 'text': '👍'}]},
  {'id': 71120,
   'type': 'message',
   'date': '2023-05-14T00:25:18',
   'date_unixtime': '1684011318',
   'edited': '2023-05-14T00:25:36',
   'edited_unixtime': '1684011336',
   'from': '.',
   'from_id': 'user478003895',
   'reply_to_message_id': 71109,
   'text': 'ممنون',
   'text_entities': [{'type': 'plain', 'text': 'ممنون'}]},
  {'id': 71121,
   'type': 'message',
   'date': '2023-05-14T00:50:47',
   'date_unixtime': '1684012847',
   'from': 'adel',
   'from_id': 'user349763836',
   'reply_to_message_id': 40211,
   'text': 'فردا حواستون به بانکیا باشه😁😁',
   'text_entities': [{'type': 'plain',
     'text': 'فردا حواستون به بانکیا باشه😁😁'}]},
  {'id': 71122,
   'type': 'message',
   'date': '2023-05-14T00:54:44',
   'date_unixtime': '1684013084',
   'edited': '2023-05-14T00:57:22',
   'edited_unixtime': '1684013242',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 71008,
   'text': 'آخه برید معاملات رو یکم\u200cنگاه کنید بررسی بکنید\nمعاملات \nهیچی سر درنمیارین یکیم\u200cمیخواد اینجا فقط توضیح بده\nپیام هارو هم درست بخونید خو اهشن\nیکیتون\u200cمیگید سه شنبه کی پیام گذاشتی \nسه شنبه نبود چهارشنبه پیام گذاشتی ریپلای میکنم\u200cپیام رو\nدوباره یه نفر بگه پیدا میشه یه چیز دیگه میگه\nبابا برید یکبار پیام هارو از اول درست بخونید دیگه سوال پیش نمیاد واستون\nهرکدوم یه گوشه  و میگیرید \nهزارتا داستان درست میکنید \nآخرشم محکوم\nخب میگی نوسان\u200cگیری باید حرفه ای باشی خب برو حرفه ای بشو بدون چه جوری میگیرن دیگه\nهمه چی رو مگه میشه با تایپ کردن توضیح داد\nیکم\u200cمنطقی باشین خب',
   'text_entities': [{'type': 'plain',
     'text': 'آخه برید معاملات رو یکم\u200cنگاه کنید بررسی بکنید\nمعاملات \nهیچی سر درنمیارین یکیم\u200cمیخواد اینجا فقط توضیح بده\nپیام هارو هم درست بخونید خو اهشن\nیکیتون\u200cمیگید سه شنبه کی پیام گذاشتی \nسه شنبه نبود چهارشنبه پیام گذاشتی ریپلای میکنم\u200cپیام رو\nدوباره یه نفر بگه پیدا میشه یه چیز دیگه میگه\nبابا برید یکبار پیام هارو از اول درست بخونید دیگه سوال پیش نمیاد واستون\nهرکدوم یه گوشه  و میگیرید \nهزارتا داستان درست میکنید \nآخرشم محکوم\nخب میگی نوسان\u200cگیری باید حرفه ای باشی خب برو حرفه ای بشو بدون چه جوری میگیرن دیگه\nهمه چی رو مگه میشه با تایپ کردن توضیح داد\nیکم\u200cمنطقی باشین خب'}]},
  {'id': 71123,
   'type': 'message',
   'date': '2023-05-14T00:57:12',
   'date_unixtime': '1684013232',
   'from': 'farshad Safaei',
   'from_id': 'user1404572273',
   'reply_to_message_id': 68904,
   'text': 'داداش از زراعتی ها کدوم رو شما مناسب میدونید',
   'text_entities': [{'type': 'plain',
     'text': 'داداش از زراعتی ها کدوم رو شما مناسب میدونید'}]},
  {'id': 71124,
   'type': 'message',
   'date': '2023-05-14T01:00:04',
   'date_unixtime': '1684013404',
   'from': 'J r',
   'from_id': 'user513876700',
   'reply_to_message_id': 40211,
   'text': 'اسهال خونی میشن',
   'text_entities': [{'type': 'plain', 'text': 'اسهال خونی میشن'}]},
  {'id': 71125,
   'type': 'message',
   'date': '2023-05-14T01:01:53',
   'date_unixtime': '1684013513',
   'from': 'kiân 🐈\u200d⬛',
   'from_id': 'user898630388',
   'reply_to_message_id': 71123,
   'text': 'سلام تکنیکالی همین زکشت\nبنیادی زفکا خوبه،توی این قیمتا کم ریسکه',
   'text_entities': [{'type': 'plain',
     'text': 'سلام تکنیکالی همین زکشت\nبنیادی زفکا خوبه،توی این قیمتا کم ریسکه'}]},
  {'id': 71126,
   'type': 'message',
   'date': '2023-05-14T01:19:13',
   'date_unixtime': '1684014553',
   'from': 'X',
   'from_id': 'user630762799',
   'reply_to_message_id': 71113,
   'photo': '(File not included. Change data exporting settings to download.)',
   'width': 748,
   'height': 848,
   'text': '',
   'text_entities': []},
  {'id': 71127,
   'type': 'message',
   'date': '2023-05-14T01:59:32',
   'date_unixtime': '1684016972',
   'edited': '2023-05-14T07:32:45',
   'edited_unixtime': '1684036965',
   'from': '-Amin-',
   'from_id': 'user101702051',
   'reply_to_message_id': 71122,
   'text': 'از این بازار سازی که دست قدیمیا و گنده های بورسم میذاره تو پوست گردو و مدام رکب میزنه با بازیاش میخوای نوسان بگیری؟؟؟؟موفق باشی',
   'text_entities': [{'type': 'plain',
     'text': 'از این بازار سازی که دست قدیمیا و گنده های بورسم میذاره تو پوست گردو و مدام رکب میزنه با بازیاش میخوای نوسان بگیری؟؟؟؟موفق باشی'}]},
  {'id': 71128,
   'type': 'message',
   'date': '2023-05-14T02:00:15',
   'date_unixtime': '1684017015',
   'edited': '2023-05-14T06:23:20',
   'edited_unixtime': '1684032800',
   'from': '↻ DIGI ANTI ⇦',
   'from_id': 'user708729562',
   'text': ['⏰ زمان فعال شدن قفل خودکار رسیده است !\n\n» ارسال پیام در گروه تا ساعت [ ',
    {'type': 'bold', 'text': '06:00'},
    ' ] ممنوع می\u200cباشد .'],
   'text_entities': [{'type': 'plain',
     'text': '⏰ زمان فعال شدن قفل خودکار رسیده است !\n\n» ارسال پیام در گروه تا ساعت [ '},
    {'type': 'bold', 'text': '06:00'},
    {'type': 'plain', 'text': ' ] ممنوع می\u200cباشد .'}]},
  {'id': 71135,
   'type': 'message',
   'date': '2023-05-14T06:01:27',
   'date_unixtime': '1684031487',
   'from': '↻ DIGI ANTI ⇦',
   'from_id': 'user708729562',
   'text': '✅ زمان قفل خودکار به پایان رسید !\n\n» کاربران میتوانند مطالب خود را ارسال کنند .',
   'text_entities': [{'type': 'plain',
     'text': '✅ زمان قفل خودکار به پایان رسید !\n\n» کاربران میتوانند مطالب خود را ارسال کنند .'}]},
  {'id': 71136,
   'type': 'message',
   'date': '2023-05-14T07:11:23',
   'date_unixtime': '1684035683',
   'from': 'Mohsen Saadat',
   'from_id': 'user75667610',
   'file': '(File not included. Change data exporting settings to download.)',
   'thumbnail': '(File not included. Change data exporting settings to download.)',
   'media_type': 'video_file',
   'mime_type': 'video/mp4',
   'duration_seconds': 1,
   'width': 320,
   'height': 282,
   'text': 'سلام صبح زیباتون بخیر ☕️🌸\nانشاءالله\nدرپناه پروردگار💖\nامروزتون بخیرونیکی\nحال دلتون خوب\nوجودتون سرشار از سلامتی 😇\nزندگیتون غرق درخوشبختی🌷\nشیرین وعاشقانه با خدا\xa0 باشه 💖🌷\nعرض ادب و احترام ، سعادت🌹',
   'text_entities': [{'type': 'plain',
     'text': 'سلام صبح زیباتون بخیر ☕️🌸\nانشاءالله\nدرپناه پروردگار💖\nامروزتون بخیرونیکی\nحال دلتون خوب\nوجودتون سرشار از سلامتی 😇\nزندگیتون غرق درخوشبختی🌷\nشیرین وعاشقانه با خدا\xa0 باشه 💖🌷\nعرض ادب و احترام ، سعادت🌹'}]},
  {'id': 71137,
   'type': 'message',
   'date': '2023-05-14T07:34:51',
   'date_unixtime': '1684037091',
   'from': 'Z.hn',
   'from_id': 'user41786458',
   'reply_to_message_id': 71122,
   'text': 'باشه استاد کارت درسته، اگه میبینی کسی متوجه منظورتون نمیشه لازم نیس خودتو اذیت کنی و اینقد توضیح بدی، دقیقا چیو میخوای ثابت کنی؟؟\nهمین که خودت سود کردی کافیه\nموفق و پرسود باشی',
   'text_entities': [{'type': 'plain',
     'text': 'باشه استاد کارت درسته، اگه میبینی کسی متوجه منظورتون نمیشه لازم نیس خودتو اذیت کنی و اینقد توضیح بدی، دقیقا چیو میخوای ثابت کنی؟؟\nهمین که خودت سود کردی کافیه\nموفق و پرسود باشی'}]},
  {'id': 71138,
   'type': 'message',
   'date': '2023-05-14T07:36:08',
   'date_unixtime': '1684037168',
   'edited': '2023-05-14T08:59:38',
   'edited_unixtime': '1684042178',
   'from': 'B Razli',
   'from_id': 'user117414063',
   'reply_to_message_id': 70368,
   'text': 'منم تازه چند روز وارد شستا شدم منتظرم پایینتر بیاد پله دوم رو هم بخرم. الان منفی کم هستم.',
   'text_entities': [{'type': 'plain',
     'text': 'منم تازه چند روز وارد شستا شدم منتظرم پایینتر بیاد پله دوم رو هم بخرم. الان منفی کم هستم.'}]},
  {'id': 71139,
   'type': 'message',
   'date': '2023-05-14T07:45:59',
   'date_unixtime': '1684037759',
   'from': 'Mohsen Monadi',
   'from_id': 'user82475781',
   'reply_to_message_id': 70629,
   'text': 'تحلیلت رو اینجا بذار ما هم استفاده کنیم',
   'text_entities': [{'type': 'plain',
     'text': 'تحلیلت رو اینجا بذار ما هم استفاده کنیم'}]},
  {'id': 71140,
   'type': 'message',
   'date': '2023-05-14T07:47:18',
   'date_unixtime': '1684037838',
   'edited': '2023-05-14T08:17:37',
   'edited_unixtime': '1684039657',
   'from': 'Mohsen Monadi',
   'from_id': 'user82475781',
   'reply_to_message_id': 40778,
   'text': 'زمانی که تعداد عرضه اولیه ها زیاد شد از بازار بترسید',
   'text_entities': [{'type': 'plain',
     'text': 'زمانی که تعداد عرضه اولیه ها زیاد شد از بازار بترسید'}]},
  {'id': 71141,
   'type': 'message',
   'date': '2023-05-14T08:12:12',
   'date_unixtime': '1684039332',
   'from': 'asadi',
   'from_id': 'user389665592',
   'reply_to_message_id': 71139,
   'text': 'میگه بازی نمیگه تحلیل',
   'text_entities': [{'type': 'plain', 'text': 'میگه بازی نمیگه تحلیل'}]},
  {'id': 71142,
   'type': 'message',
   'date': '2023-05-14T08:42:25',
   'date_unixtime': '1684041145',
   'from': 'Mohsen Monadi',
   'from_id': 'user82475781',
   'reply_to_message_id': 71141,
   'text': 'مگه بازی بدون تحلیلم داریم؟؟ 🤔🤔',
   'text_entities': [{'type': 'plain',
     'text': 'مگه بازی بدون تحلیلم داریم؟؟ 🤔🤔'}]},
  {'id': 71143,
   'type': 'message',
   'date': '2023-05-14T08:43:35',
   'date_unixtime': '1684041215',
   'from': 'Alireza Momenynejad',
   'from_id': 'user106533999',
   'reply_to_message_id': 71140,
   'text': 'دیگه کار از ترس گذشته مشتی تو 5 روز 500 هزار واحد اومدیم پایین عملا اب از سرمون گذشته',
   'text_entities': [{'type': 'plain',
     'text': 'دیگه کار از ترس گذشته مشتی تو 5 روز 500 هزار واحد اومدیم پایین عملا اب از سرمون گذشته'}]},
  {'id': 71144,
   'type': 'message',
   'date': '2023-05-14T08:44:17',
   'date_unixtime': '1684041257',
   'from': 'Hamid Khoshdel',
   'from_id': 'user68282650',
   'reply_to_message_id': 71143,
   'text': '۵۰۰ هرار واحد رو از کجات اوردی اخوی؟',
   'text_entities': [{'type': 'plain',
     'text': '۵۰۰ هرار واحد رو از کجات اوردی اخوی؟'}]},
  {'id': 71145,
   'type': 'message',
   'date': '2023-05-14T08:44:46',
   'date_unixtime': '1684041286',
   'from': 'asadi',
   'from_id': 'user389665592',
   'reply_to_message_id': 71142,
   'text': 'بازی بازیگر',
   'text_entities': [{'type': 'plain', 'text': 'بازی بازیگر'}]},
  {'id': 71146,
   'type': 'message',
   'date': '2023-05-14T08:46:08',
   'date_unixtime': '1684041368',
   'from': '...',
   'from_id': 'user5841141460',
   'reply_to_message_id': 71121,
   'text': 'چکارشون کنیم بخریم یا بفروشیم ؟',
   'text_entities': [{'type': 'plain',
     'text': 'چکارشون کنیم بخریم یا بفروشیم ؟'}]},
  {'id': 71147,
   'type': 'message',
   'date': '2023-05-14T08:47:51',
   'date_unixtime': '1684041471',
   'from': 'Ahmad',
   'from_id': 'user5621880841',
   'reply_to_message_id': 71126,
   'text': 'بازار مگه تکنیکالی اومد پایین\u200c ک\u200cتکنیکالی بره بالا؟',
   'text_entities': [{'type': 'plain',
     'text': 'بازار مگه تکنیکالی اومد پایین\u200c ک\u200cتکنیکالی بره بالا؟'}]},
  {'id': 71148,
   'type': 'message',
   'date': '2023-05-14T08:59:50',
   'date_unixtime': '1684042190',
   'from': 'asadi',
   'from_id': 'user389665592',
   'reply_to_message_id': 71147,
   'text': 'موج اصلاحی رو منظورشه هرچند اصلاح دستوری بود ولی کلا حرکات اصلاحی رو میگه',
   'text_entities': [{'type': 'plain',
     'text': 'موج اصلاحی رو منظورشه هرچند اصلاح دستوری بود ولی کلا حرکات اصلاحی رو میگه'}]},
  {'id': 71149,
   'type': 'message',
   'date': '2023-05-14T09:00:50',
   'date_unixtime': '1684042250',
   'from': 'افشین احمدی',
   'from_id': 'user891725662',
   'reply_to_message_id': 71122,
   'text': 'دوست عزیز سلام\nچرا خودتو اذیت میکنی\nمن هفته پیش فرمایشات شما خدمت دوستان عرض کردم\nحالا هر\u200c کسی مسئول سود و ضرر خودشه\nمختاره تو کارش\nاصرار بیجایه شما باعث میشه \nدوستان تازه وارد با بحث و لجبازی گاها پیش اومده نتونن درست تصمیم بگیرن\nمیدونم نیتت خیره \nولی اجازه فکر کردن بده ب دوستان\nممنونم',
   'text_entities': [{'type': 'plain',
     'text': 'دوست عزیز سلام\nچرا خودتو اذیت میکنی\nمن هفته پیش فرمایشات شما خدمت دوستان عرض کردم\nحالا هر\u200c کسی مسئول سود و ضرر خودشه\nمختاره تو کارش\nاصرار بیجایه شما باعث میشه \nدوستان تازه وارد با بحث و لجبازی گاها پیش اومده نتونن درست تصمیم بگیرن\nمیدونم نیتت خیره \nولی اجازه فکر کردن بده ب دوستان\nممنونم'}]},
  {'id': 71150,
   'type': 'message',
   'date': '2023-05-14T09:01:06',
   'date_unixtime': '1684042266',
   'from': 'E S',
   'from_id': 'user762592197',
   'reply_to_message_id': 40783,
   'photo': '(File not included. Change data exporting settings to download.)',
   'width': 1280,
   'height': 1280,
   'text': '',
   'text_entities': []},
  {'id': 71151,
   'type': 'message',
   'date': '2023-05-14T09:14:33',
   'date_unixtime': '1684043073',
   'edited': '2023-05-14T09:23:01',
   'edited_unixtime': '1684043581',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 40302,
   'text': 'یه نوسان\u200cگیری عالی از سهمهایی که گفته بودم\nخگستر، خمحرکه، ختور\nهیچ جایی مثله بورس ایران سود نمیده.فقط بدونی کجا وارد بشی کجا خارج بشی💪💪💪💪',
   'text_entities': [{'type': 'plain',
     'text': 'یه نوسان\u200cگیری عالی از سهمهایی که گفته بودم\nخگستر، خمحرکه، ختور\nهیچ جایی مثله بورس ایران سود نمیده.فقط بدونی کجا وارد بشی کجا خارج بشی💪💪💪💪'}]},
  {'id': 71152,
   'type': 'message',
   'date': '2023-05-14T09:15:10',
   'date_unixtime': '1684043110',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 71149,
   'text': 'چشم',
   'text_entities': [{'type': 'plain', 'text': 'چشم'}]},
  {'id': 71153,
   'type': 'message',
   'date': '2023-05-14T09:16:45',
   'date_unixtime': '1684043205',
   'from': 'asadi',
   'from_id': 'user389665592',
   'reply_to_message_id': 40302,
   'file': '(File not included. Change data exporting settings to download.)',
   'thumbnail': '(File not included. Change data exporting settings to download.)',
   'media_type': 'animation',
   'mime_type': 'video/mp4',
   'duration_seconds': 4,
   'width': 536,
   'height': 300,
   'text': '',
   'text_entities': []},
  {'id': 71154,
   'type': 'message',
   'date': '2023-05-14T09:17:02',
   'date_unixtime': '1684043222',
   'edited': '2023-05-14T09:24:53',
   'edited_unixtime': '1684043693',
   'from': 'asadi',
   'from_id': 'user389665592',
   'reply_to_message_id': 40302,
   'text': 'خوشم میاد کمم نمیاری🥰😂',
   'text_entities': [{'type': 'plain', 'text': 'خوشم میاد کمم نمیاری🥰😂'}]},
  {'id': 71155,
   'type': 'message',
   'date': '2023-05-14T09:18:34',
   'date_unixtime': '1684043314',
   'from': 'خیرالهی',
   'from_id': 'user454310006',
   'reply_to_message_id': 71153,
   'text': '😂👍',
   'text_entities': [{'type': 'plain', 'text': '😂👍'}]},
  {'id': 71156,
   'type': 'message',
   'date': '2023-05-14T09:20:46',
   'date_unixtime': '1684043446',
   'from': 'Alireza Momenynejad',
   'from_id': 'user106533999',
   'reply_to_message_id': 40302,
   'text': 'خبری شد دوباره دارن خساپا رو صف فروش میکنن؟',
   'text_entities': [{'type': 'plain',
     'text': 'خبری شد دوباره دارن خساپا رو صف فروش میکنن؟'}]},
  {'id': 71157,
   'type': 'message',
   'date': '2023-05-14T09:21:19',
   'date_unixtime': '1684043479',
   'from': 'Shima Ghaffari 💁🏼\u200d♀️',
   'from_id': 'user5632416119',
   'reply_to_message_id': 71151,
   'text': 'چرا من اسمتو نمیفهمم\n\n\n\nولی خیلی با حالی 🤚🏻🤚🏻🤚🏻☺️',
   'text_entities': [{'type': 'plain',
     'text': 'چرا من اسمتو نمیفهمم\n\n\n\nولی خیلی با حالی 🤚🏻🤚🏻🤚🏻☺️'}]},
  {'id': 71158,
   'type': 'message',
   'date': '2023-05-14T09:21:44',
   'date_unixtime': '1684043504',
   'from': 'خیرالهی',
   'from_id': 'user454310006',
   'reply_to_message_id': 71153,
   'text': 'من که بدبخت نبودم اینا منو بدبخت کردن…',
   'text_entities': [{'type': 'plain',
     'text': 'من که بدبخت نبودم اینا منو بدبخت کردن…'}]},
  {'id': 71159,
   'type': 'message',
   'date': '2023-05-14T09:22:41',
   'date_unixtime': '1684043561',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 71157,
   'text': '🙏🙏🙏',
   'text_entities': [{'type': 'plain', 'text': '🙏🙏🙏'}]},
  {'id': 71160,
   'type': 'message',
   'date': '2023-05-14T09:23:05',
   'date_unixtime': '1684043585',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 71156,
   'text': 'بازیشونه',
   'text_entities': [{'type': 'plain', 'text': 'بازیشونه'}]},
  {'id': 71161,
   'type': 'message',
   'date': '2023-05-14T09:25:16',
   'date_unixtime': '1684043716',
   'from': 'Arash Kargar',
   'from_id': 'user188200496',
   'reply_to_message_id': 71156,
   'text': 'پنل من مثبت نشون میده.کارگزاریتون چیه؟',
   'text_entities': [{'type': 'plain',
     'text': 'پنل من مثبت نشون میده.کارگزاریتون چیه؟'}]},
  {'id': 71162,
   'type': 'message',
   'date': '2023-05-14T09:25:44',
   'date_unixtime': '1684043744',
   'edited': '2023-05-14T09:26:12',
   'edited_unixtime': '1684043772',
   'from': '£@¥&',
   'from_id': 'user732850104',
   'reply_to_message_id': 40302,
   'text': 'بچها گل نخورید ها شاخص داره پولبک میزنه واسه برگشت\nسهم هاتون رو از چنگتون درنیارن',
   'text_entities': [{'type': 'plain',
     'text': 'بچها گل نخورید ها شاخص داره پولبک میزنه واسه برگشت\nسهم هاتون رو از چنگتون درنیارن'}]},
  {'id': 71163,
   'type': 'message',
   'date': '2023-05-14T09:25:44',
   'date_unixtime': '1684043744',
   'from': 'Sohrabi',
   'from_id': 'user99901769',
   'reply_to_message_id': 71156,
   'text': 'کو تا صف فروش',
   'text_entities': [{'type': 'plain', 'text': 'کو تا صف فروش'}]},
  {'id': 71164,
   'type': 'message',
   'date': '2023-05-14T09:26:40',
   'date_unixtime': '1684043800',
   'edited': '2023-05-14T09:26:52',
   'edited_unixtime': '1684043812',
   'from': 'Sohrabi',
   'from_id': 'user99901769',
   'reply_to_message_id': 71161,
   'text': 'یعنی حتی فرق صف فروشم نمیدونن .\nیعنی حتی چیزی غیر صف خرید و صف فروش ندیدن',
   'text_entities': [{'type': 'plain',
     'text': 'یعنی حتی فرق صف فروشم نمیدونن .\nیعنی حتی چیزی غیر صف خرید و صف فروش ندیدن'}]},
  {'id': 71165,
   'type': 'message',
   'date': '2023-05-14T09:28:04',
   'date_unixtime': '1684043884',
   'from': 'Amir Shadmn',
   'from_id': 'user1840617096',
   'reply_to_message_id': 40211,
   'text': 'یک مقدار تردید و وحشت هنوز در بین سهامداران وجود دارد اما سهم های ذیل مساعد برای رشد هستند حتما کمی در سبد داشته باشید.\nدامین\nکماسه\nبخاور\nسپید\nسلام\nانشاالله تا آخر هفته از همین ۵ سهم سود خوبی دریافت میکنید',
   'text_entities': [{'type': 'plain',
     'text': 'یک مقدار تردید و وحشت هنوز در بین سهامداران وجود دارد اما سهم های ذیل مساعد برای رشد هستند حتما کمی در سبد داشته باشید.\nدامین\nکماسه\nبخاور\nسپید\nسلام\nانشاالله تا آخر هفته از همین ۵ سهم سود خوبی دریافت میکنید'}]},
  {'id': 71166,
   'type': 'message',
   'date': '2023-05-14T09:28:14',
   'date_unixtime': '1684043894',
   'from': 'Amir Shadmn',
   'from_id': 'user1840617096',
   'reply_to_message_id': 40302,
   'text': 'یک مقدار تردید و وحشت هنوز در بین سهامداران وجود دارد اما سهم های ذیل مساعد برای رشد هستند حتما کمی در سبد داشته باشید.\nدامین\nکماسه\nبخاور\nسپید\nسلام\nانشاالله تا آخر هفته از همین ۵ سهم سود خوبی دریافت میکنید',
   'text_entities': [{'type': 'plain',

In [6]:
# with open('result.json', encoding='utf-8') as file:
#     result = json.loads(file.read())
# len(result)

In [34]:
stocks=pd.read_csv('../stocks/stocks_tsetmcs.csv')
stocks=stocks[["sym_name","name","sym","gp_name"]]
exlude_list=['ما', 'تمدن']
stocks=stocks[~stocks["sym_name"].isin(exlude_list)]
stocks.head()

,sym_name,name,sym,gp_name
0,18719101,اوراق مشاركت ايران‌ خودرو,IKCQ1,خودرو و ساخت قطعات
1,آباد,توريستي ورفاهي آبادگران ايران,ABAD1,هتل و رستوران
2,آبادا,توليد نيروي برق آبادان,NBAB1,عرضه برق، گاز، بخاروآب گرم
3,آبادح,ح . ‌توريستي‌ورفاهي‌آبادگران‌,ABAX1,هتل و رستوران
4,آپ,آسان پرداخت پرشين,APPE1,رايانه و فعاليت‌هاي وابسته به آن

In [18]:
# txt="""# فولاژ
# در آستانه صف خرید به دلیل رشد 50 درصدی متوقف شد
#     """

# with open('./stocks/stk_id.json', encoding='utf-8') as file:
#     stocks = json.loads(file.read())
# len(stocks)
# stocks


def norm(txt):
    return Normalizer().normalize(txt)


def token_count(txt):
    return len(enc.encode(txt))


def if_chatlist_id_included(chatlist, ID):
    #     print("CHATLIS__",chat_list)
    for chat in chatlist:
        if ID in chat["id_list"]:
            return True
    return False


def is_id_in_chatlist(chatlist, ID):
    #     print("CHATLIS__",chat_list)
    for chat in chatlist:
        if ID == chat["chat_id"]:
            return True
    return False


def if_stock_included(txt):
    for index, row in stocks.iterrows():
        if norm(row["sym_name"]) in norm(txt):
            #             print("if_stock_included__")
            #             print(f"_*_{norm(txt)}_*_",row["sym_name"])
            return True
    return False


# if stock name is included in the text it will be replaced by stocks ID RETURNS: (if_is_included,text)
def if_stock_included_replace(txt):
    txt = norm(txt)
    #     txt_list=txt.split()

    for index, row in stocks.iterrows():
        norm_sym = norm(row["sym_name"]).replace("\u200c", " ")
        txt = re.sub(rf"\b{norm_sym}\b", f"<{row['sym']}>", txt)
    #     print("replace_stock_with_idـ",norm_sym)
    if re.findall(r"<[0-9A-Za-z]>*", txt):
        return True, txt
    return False, txt


def clean_text(txt):
    replacement_patterns = {
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+": "",  # website
        r"[\w\.-]+@[\w\.-]+": "",  # email
        r"@[A-Za-z0-9]*": "",  # @ID
        r"#": "",
        r"\n{2,}": "\n",
    }
    for pattern, replacement in replacement_patterns.items():
        txt = re.sub(pattern, replacement, txt)
    return txt

In [75]:
# with open('./majid/result.json', encoding='utf-8') as file:
#     maj = json.loads(file.read())
# maj

### Preprocessing public_supergroup
* GROUPS List :        
    1. BOURSGRAM بورسگرام

In [143]:
SUBGROUPS = {
    "1727038436": {
        "name": "بورسگرام | Boursegram",
        "40231": {"name": "غذایی"},
        "40209": {"name": "حمل و نقل"},
        "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
        "40211": {"name": "بانکها"},
        "40302": {"name": "خودرو و ساخت قطعات"},
        "48994": {"name": "آپشن (اختیار معامله)"},
        "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
        "40230": {"name": "دارویی"},
        "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
        "40203": {"name": "انبوه سازي_ساختمانی"},
        "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
        "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
        "40253": {"name": "زراعت"},
        "40236": {"name": "قند و شكر"},
        "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
        "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
        "40206": {
            "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
        },
        "40207": {"name": "بیمه"},
        "40227": {"name": "محصولات شيميايي"},
        "40219": {"name": "سیمان"},
        "40210": {"name": "لیزینگ"},
        "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
        "40247": {"name": "لاستيك و پلاستيك"},
        "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
        "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
        "40217": {"name": "هتل و رستوران"},
        "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
        "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
        "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
    }
}

BOURSGRAM_SUBGROUPS = {
    "40231": {"name": "غذایی"},
    "40209": {"name": "حمل و نقل"},
    "40783": {"name": "روند و‌ پیش بینی بازار_شاخص کل و شاخص هموزن"},
    "40211": {"name": "بانکها"},
    "40302": {"name": "خودرو و ساخت قطعات"},
    "48994": {"name": "آپشن (اختیار معامله)"},
    "40212": {"name": "سرمایه گذاریها_چند رشته اي صنعتي"},
    "40230": {"name": "دارویی"},
    "40246": {"name": "فلزات_ استخراج کانه های فلزی_زغال سنگ_سایرمعادن"},
    "40203": {"name": "انبوه سازي_ساختمانی"},
    "40232": {"name": "نیروگاهها (عرضه برق، گاز، بخاروآب گرم)"},
    "40248": {"name": "پالایشی (فراورده هاي نفتي)_استخراج نفت گاز"},
    "40253": {"name": "زراعت"},
    "40236": {"name": "قند و شكر"},
    "40778": {"name": "بورس کالا_دلار، سکه، طلا_عرضه اولیه"},
    "40208": {"name": "برقی-مخابرات_ساخت دستگاه‌ها و وسايل ارتباطي"},
    "40206": {
        "name": "فراکاب(کالا، فرابورس، انرژی3،..)_فعاليتهاي كمكي به نهادهاي مالي واسط"
    },
    "40207": {"name": "بیمه"},
    "40227": {"name": "محصولات شيميايي"},
    "40219": {"name": "سیمان"},
    "40210": {"name": "لیزینگ"},
    "40200": {"name": "خدمات فني و مهندسي_پیمانکاری صنعتی_فعاليت مهندسي"},
    "40247": {"name": "لاستيك و پلاستيك"},
    "40221": {"name": "خرده فروشی_تجارت عمده فروشی"},
    "40218": {"name": "ساير محصولات كاني غيرفلزي_کاشی و سرامیک"},
    "40217": {"name": "هتل و رستوران"},
    "40242": {"name": "ماشين آلات و تجهيزات_ساخت محصولات فلزي"},
    "40249": {"name": "محصولات كاغذي_چاپ_محصولات چوبي_چرم_منسوجات_ فعالیتهای هنری"},
    "40202": {"name": "رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري"},
}

In [21]:
"40202"in BOURSGRAM_SUBGROUPS
# BOURSGRAM_SUBGROUPS["40202"]

{'name': 'رایانه_اطلاعات و ارتباطات_توليد محصولات كامپيوتري'}

In [68]:
# %%time
# def preprocess_subgroup():
messages = boursgram_data["messages"]
chat_list_2 = []
for mess in messages:
    txt = ""
    if "actor_id" in mess:
        continue

    date = mess["edited"] if ("edited" in mess) else mess["date"]
    date_unixtime = ( mess["edited_unixtime"] if ("edited_unixtime" in mess) else mess["date_unixtime"])

    chat_info = {
        "person_id": mess["from_id"],
        "chat_id": mess["id"],
        "date": date,
        "date_unixtime": date_unixtime,
        "org_txt":mess["text"],
        "reply_to_message_id":""

    }

    for tx in mess["text_entities"]:
        txt += clean_text(tx["text"]).strip() + "\n"

    #     chat_info["text"]= txt
    is_stock_included, txt = if_stock_included_replace(txt.strip())

    # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
    if ( ("reply_to_message_id" in mess) and mess["reply_to_message_id"] not in SUBGROUPS[""] ) and (is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        
        chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
        #         txt_rep = replace_stock_with_id(txt.strip())
        chat_info["text"] = txt
        chat_list_2.append(chat_info)
        #                 print(cht["id_list"])
        # print("looooool")
    #     is_included,txt = replace_stock_with_id(txt.strip())
    elif is_stock_included:
        chat_info["text"] = txt
        chat_list_2.append(chat_info)
# print(chat_list_1)
#

looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool
looooool

In [ ]:
# %%time
def preprocess_subgroup(data):
    print("__> preprocess_subgroup", data["name"])
    # messages = boursgram_data["messages"]
    chat_list = []
    for mess in data["messages"]:
        txt = ""
        if "actor_id" in mess:
            continue

        date = mess["edited"] if ("edited" in mess) else mess["date"]
        date_unixtime = (
            mess["edited_unixtime"]
            if ("edited_unixtime" in mess)
            else mess["date_unixtime"]
        )

        for tx in mess["text_entities"]:
            txt += clean_text(tx["text"]).strip() + "\n"
        is_stock_included, rep_txt = if_stock_included_replace(txt.strip())

        chat_info = {
            "person_id": mess["from_id"],
            "chat_id": mess["id"],
            "date": date,
            "date_unixtime": date_unixtime,
            "org_txt": txt,
            "reply_to_message_id": "",
            "text":rep_txt
        }

        #     chat_info["text"]= txt

        # if (data["type"]== "public_supergroup" and mess["reply_to_message_id"] not in SUBGROUPS["id"] ) or (data["type"] != "public_supergroup" ):

        # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        if (
            ("reply_to_message_id" in mess)
            and (mess["reply_to_message_id"] not in SUBGROUPS["id"])
            and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
        ):
            chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
            #         txt_rep = replace_stock_with_id(txt.strip())
            # chat_info["text"] = txt
            chat_list.append(chat_info)
            #                 print(cht["id_list"])
            # print("looooool")
        #     is_included,txt = replace_stock_with_id(txt.strip())
        elif is_stock_included:
            # chat_info["text"] = txt
            chat_list.append(chat_info)

    return {**data, "messages": chat_list}


# print(chat_list_1)
#

In [156]:
# %%time
def preprocess_subgroup(data):
    data_id=str(data["id"])
    print("__> preprocess_subgroup", data["name"])
    # messages = boursgram_data["messages"]
    chat_list = []
    for mess in data["messages"]:
        txt = ""
        if "actor_id" in mess:
            continue

        date = mess["edited"] if ("edited" in mess) else mess["date"]
        date_unixtime = (
            mess["edited_unixtime"]
            if ("edited_unixtime" in mess)
            else mess["date_unixtime"]
        )

        for tx in mess["text_entities"]:
            txt += clean_text(tx["text"]).strip() + "\n"
            
        if len(enc.encode(txt)) >500:
            continue
        is_stock_included, rep_txt = if_stock_included_replace(txt.strip())

        chat_info = {
            "person_id": mess["from_id"],
            "chat_id": mess["id"],
            "date": date,
            "date_unixtime": date_unixtime,
            "org_txt": txt,
            "reply_to_message_id": "",
            "text": rep_txt,
        }

        #     chat_info["text"]= txt

        # if (data["type"]== "public_supergroup" and mess["reply_to_message_id"] not in SUBGROUPS["id"] ) or (data["type"] != "public_supergroup" ):

        # if ("reply_to_message_id" in mess) and (mess["reply_to_message_id"] not in BOURSGRAM_SUBGROUPS) and(is_id_in_chatlist(chat_list_2, mess["reply_to_message_id"])):
        if (
            ("reply_to_message_id" in mess)
            and (
                ( ## checks in public_supergroup that have subgroups,wheter the replied messaged is not replied to the subgroup ID
                    data["type"] == "public_supergroup"
                    and (data_id in SUBGROUPS)
                    and (mess["reply_to_message_id"] not in SUBGROUPS[data_id])
                )
                or (data["type"] != "public_supergroup")
            )
            and (is_id_in_chatlist(chat_list, mess["reply_to_message_id"]))
        ):
            chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
            #         txt_rep = replace_stock_with_id(txt.strip())
            # chat_info["text"] = txt
            chat_list.append(chat_info)
            #                 print(cht["id_list"])
            # print("looooool")
        #     is_included,txt = replace_stock_with_id(txt.strip())
        elif is_stock_included:
            # chat_info["text"] = txt
            chat_list.append(chat_info)

    return {**data, "messages": chat_list}


# print(chat_list_1)
#

In [147]:
# chat_list_2
# bours_df=pd.DataFrame(chat_list_2)
# bours_df.head()
# x="  'text': '\u200c\nواقعیت ماجرای شاسی
# بلندها و ارتباطشان با استیضاح وزیر صمت\nمنابع < PKLJ1 > تایید کردند در ابتدای تابستان 1400 یعنی تنها چند هفته بعد از انتخابات ریاس"
# clean_text(x)

### Preprocessing telegram public_channel and simplegroups

In [146]:
# # %%time

# messages = maj["messages"]
# maj_list = []
# for mess in messages:
#     txt = ""
#     date = mess["edited"] if ("edited" in mess) else mess["date"]
#     date_unixtime = (
#         mess["edited_unixtime"]
#         if ("edited_unixtime" in mess)
#         else mess["date_unixtime"]
#     )
#     for tx in mess["text_entities"]:
#         txt += clean_text(tx["text"]).strip() + "\n"
#     chat_info = {
#         "person_id": mess["from_id"],
#         "chat_id": mess["id"],
#         "date": date,
#         "date_unixtime": date_unixtime,
#         "org_txt":txt,
#         "reply_to_message_id":""
#     }

#     #     chat_info["text"]= txt
#     is_stock_included, txt = if_stock_included_replace(txt.strip())

#     if ("reply_to_message_id" in mess) and (
#         is_id_in_chatlist(maj_list, mess["reply_to_message_id"])
#     ):
#         chat_info["reply_to_message_id"] = mess["reply_to_message_id"]
#         #         txt_rep = replace_stock_with_id(txt.strip())
#         chat_info["text"] = txt
#         maj_list.append(chat_info)
#         #                 print(cht["id_list"])
#         print("looooool")
#     #     is_included,txt = replace_stock_with_id(txt.strip())
#     elif is_stock_included:
#         chat_info["text"] = txt
#         maj_list.append(chat_info)
# #     elif if_stock_included(txt):
# # #         print("if_included_ch",txt)
# #         txt_rep = replace_stock_with_id(txt.strip())
# #         chat_info["text"]=txt_rep
# #         chat_list_2.append(chat_info)
# # print(chat_list_1)

In [145]:
# chat_list_2
# pd.DataFrame(maj_list) ,pd.DataFrame(bours_df)
# pd.concat([maj_df ,bours_df]).head()
# pd.DataFrame(maj_list)
# maj_df=pd.DataFrame(maj_list)
# majcol=maj_df[['person_id', 'chat_id', 'date', 'date_unixtime', 'org_txt', 'text','reply_to_message_id']].columns
# print(majcol)
# print(list(bours_df.columns)==list(majcol))
# maj_df=maj_df[['person_id', 'chat_id']]
# print(maj_df)
# bours_df.columns==maj_df.columns
# chat_list_2[1].keys()
# len(chat_list_2)
# len(enc.encode(chat_list_2[0]["text"]))
# chat_list_2[0]
# for index, row in df.iterrows():
#     print(row['c1'], row['c2'])

In [158]:
# datafile_names =
concatenated_data = pd.DataFrame()
chats_path = "./data/chats/"
for json_file in os.listdir(chats_path):
    # file = pd.read_csv("./data/"+json_file)
    # df = pd.DataFrame()
    with open(chats_path + json_file, encoding="utf-8") as file:
        file = json.loads(file.read())
        df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        concatenated_data = pd.concat([concatenated_data, df])

        # if file["type"] == "public_supergroup":
        #     df = pd.DataFrame(preprocess_subgroup(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])
        # else:
        #     df = pd.DataFrame(preprocess_chanell_group(file)["messages"])
        #     concatenated_data = pd.concat([concatenated_data, df])

concatenated_data = concatenated_data.reindex()
concatenated_data.to_csv("./data/concatenated.csv", index=False)
concatenated_data.head()
# concatenated_data.con
# pd.to

__> preprocess_subgroup گروه هزار تحلیل
__> preprocess_subgroup بورسگرام | Boursegram

,person_id,chat_id,date,date_unixtime,org_txt,reply_to_message_id,text
0,user956857432,361027,2023-04-15T00:38:55,1681506535,درود هموطن با نخریدن خودرو و دوری از معاملات خ...,,درود هموطن با نخریدن <IKCO1> و دوری از معاملات...
1,channel1247075296,361043,2023-04-15T10:04:39,1681540479,بورس کالا پیشنهاد افزایش سرمایه از دو محل سود ...,,<BORS1> <KALA1> پیشنهاد افزایش سرمایه از دو مح...
2,user164684213,361050,2023-04-15T11:56:44,1681547204,خودرو و خساپا به احتمال زیاد صف خرید بشند قابل...,,<IKCO1> و <SIPA1> به احتمال زیاد صف خرید بشند ...
3,user164684213,361051,2023-04-15T11:57:46,1681547266,از فراکاب ها بورس هم وضعیت خوبی داره مدتی درجا...,,از فراکاب‌ها <BORS1> هم وضعیت خوبی داره مدتی د...
4,user164684213,361052,2023-04-16T07:36:10,1681617970,وخارزم در حال شکستن مقاومت ، هدف بالاست. بررسی\n,,<IKHR1> در حال شکستن مقاومت ، هدف بالاست . بررسی

In [8]:
# @ BOUNDS : []
# chat_list
telegram_chanells = [chat_list_2, chat_list_2]


channels_limit_bound = []
for chanell in telegram_chanells:
    chanell_bound = []
    token_count = 0
    i = 0
    while i < len(chanell):
        chat = chanell[i]
        chat_tokens_count = len(enc.encode(chat["text"]))
        # print(i)
        if token_count + chat_tokens_count > 4096:
            # print(i,len(chanell),chat_tokens_count,token_count,token_count + chat_tokens_count > 4096,i + 1 == len(chanell),)
            chanell_bound.append(i - 1)
            token_count = 0
        elif i + 1 == len(chanell):
            chanell_bound.append(i)
            token_count = 0
            i += 1
        else:
            token_count += chat_tokens_count
            i += 1
    channels_limit_bound.append(chanell_bound)
channels_limit_bound

[[5, 29], [5, 29]]

In [155]:
enc = tiktoken.get_encoding("cl100k_base")
x="""۷ ملک دیگر بانک فرابورسی کارشناسی شدند/ افزایش ارزش دارایی‌ها
به گزارش پایگاه خبری بورس پرس، به‌دنبال ارائه پیشین گزارش‌های کارشناسی املاک بانک آینده در سامانه کدال، ارزیابی‌های جدیدی از املاک این بانک حاضر در بازار پایه و غایب 19 ماهه از تابلو معاملات افشا شد.
🔹بر اساس این گزارش، املاک و دارایی‌های ارزیابی شده از شرکت‌های زیرمجموعه بانک آینده که توسط هیأت کارشناسان رسمی دادگستری مرکز وکلا و کارشناسان رسمی قوه قضائیه انجام شده، بیانگر افزایش ارزش چشمگیر دارایی‌های مزبور، نسبت به گذشته است.
🔹جدیدترین موارد افشا شامل ملک سعادت آباد متعلق به شرکت تجارت الکترونیک فردا، ملک شیخ بهایی متعلق به شرکت توسعه تجارت نگین بینالود، ملک جردن متعلق به شرکت دقایق‌گستر پویا، املاک زرتشت و حکیم متعلق به شرکت آشیان‌سازان کیهان،"""
len(enc.encode(x))

510

In [140]:
# %%time
# def add(x, y):
#     return  x+y['text']
#     # return  x+"**"+y

# # list = [2, 4, 7, 3]
# reduce(add, telegram_chanells[0][:7+1],"")

# def concatenate_chanell_chat(chanell):
#     chats=""
#     for chat in chanell:
#         # chats+=("\n".join(chat['text'])+"**")
#         chats+=chat['text']
#     return chats

# x==concatenate_chanell_chat(telegram_chanells[0][:7+1])
# telegram_chanells[0][:7+1]

In [67]:
import os

api_key = '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'
openai.api_key = api_key
# openai.Model.retrieve("gpt-3.5-turbo")
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )
# embeddings = response['data'][0]['embedding']
def request_openai(prompt):
    return openai.Completion.create(
  model="gpt-3.5-turbo",
  prompt="generate some ",
  temperature=1,
    max_tokens=5
)

In [71]:
# response = openai.Embedding.create(
#     input=["Your text string goes here","hi","hello"],
#     model="text-embedding-ada-002"
# )

# import os
# import openai
# openai.api_key = os.getenv("OPENAI_API_KEY")

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

completion
completion
# print(completion.choices[0].message)
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")
# request_openai("prompt")

<OpenAIObject chat.completion id=chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN at 0x7fcde1e1c770> JSON: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello there! How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "created": 1683976467,
  "id": "chatcmpl-7FhUhSccRFLvvdgk9uyxopYbn6lcN",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 10,
    "prompt_tokens": 10,
    "total_tokens": 20
  }
}

In [105]:
# print(completion)
# print(completion)
# print(completion)
# print(completion)
# for i in range(20):
#     openai.ChatCompletion.create(
#   model="gpt-3.5-turbo",
#   messages=[
#     {"role": "user", "content": "Hello!"}
#   ]
# )

In [108]:
len(enc.encode("Hello!"*1000))

2000

In [114]:
@retry(wait=wait_random_exponential(min=1, max=60), stop=stop_after_attempt(10))
def completion_with_backoff(**kwargs):
    return openai.Embedding.create(
        model="text-embedding-ada-002", input="Helloiiiiiii!"
    )


for _ in range(100):
    completion_with_backoff()
    print(_)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [83]:
%! pip install tenacity

Collecting tenacity
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
WARNING: Error parsing requirements for matplotlib: [Errno 2] No such file or directory: '/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/matplotlib-3.7.1.dist-info/METADATA'
Installing collected packages: tenacity
Successfully installed tenacity-8.2.2