In [92]:
!pip uninstall sklearn -y

WARNING: Skipping sklearn as it is not installed.

In [1]:
import pandas as pd
import openai, numpy as np
from sklearn.cluster import KMeans
# from openai.embeddings_utils import get_embedding, cosine_similarity

In [2]:
api_key = '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'
openai.api_key = api_key

In [4]:

resp = openai.Embedding.create(
    input=["eating food", "I am hungry", "I am traveling" , "exploring new places"],
    engine="text-similarity-davinci-001")
# response = openai.Embedding.create(
#     input="Your text string goes here",
#     model="text-embedding-ada-002"
# )
embeddings = resp['data'][0]['embedding']

In [26]:
# embeddings
# resp["data"][0]

In [6]:
datafile_path = "./data.csv"  # for your convenience, we precomputed the embeddings
df = pd.read_csv(datafile_path)
df.head()

                                                Text  Score  Suggestion
0  این اولین تجربه من برای خرید ایفون هست   امروز...    100           1
1                     خرید این محصول رو توصیه میکنم      84           1
2  1 ساله این گوشی رو دارم   هیچ نقطه ضعفی ازش ند...     60           1
3  سلام خدمت دوستان این گوشی از همه نظر عالی  کیف...     96           1
4  سلام دوستانی که نگران شکستن صفحه نمایش هستند ا...     92           1

In [7]:
df=df.sample(60)
df.describe()

            Score  Suggestion
count   60.000000   60.000000
mean    73.333333    1.333333
std     26.262473    0.705106
min      0.000000    1.000000
25%     60.000000    1.000000
50%     82.000000    1.000000
75%     92.000000    1.000000
max    100.000000    3.000000

In [9]:
def get_embedding(text, model="text-embedding-ada-002"):
   text = text.replace("\n", " ")
   return openai.Embedding.create(input = [text], model=model)['data'][0]['embedding']

df['embedding'] = df.Text.apply(lambda x: get_embedding(x, model='text-embedding-ada-002'))
# df.to_csv('output/embedded_1k_reviews.csv', index=False)
# df['ada_embedding']
# df['ada_embedding']=openai.Embedding.create(input = list("hi"), model="text-embedding-ada-002")['data'][0]['embedding']

In [11]:
# df['embedding']

In [12]:
# type(df['ada_embedding'][0])
df.reset_index(drop="index",inplace=True)

In [13]:
# df["embedding"] = df.ada_embedding.apply(eval).apply(np.array)
# type(df[0])
type(df.iloc[0,:]["embedding"])

list

In [15]:
df.to_csv("./digi60.csv",index=False)

In [87]:
# a=[[[2,3,4]]]; b=[[[1,2,1]]]
# np.vstack((a,b))
# np.vstack((a,b))

array([[[2, 3, 4]],

       [[1, 2, 1]]])

In [17]:
# df["ada_embedding"].values.shape
matrix = np.vstack(df["embedding"].values)
matrix.shape
# matrix

(60, 1536)

In [18]:
from sklearn.cluster import KMeans

n_clusters = 4

kmeans = KMeans(n_clusters=n_clusters, init="k-means++", random_state=42)
kmeans.fit(matrix)
labels = kmeans.labels_
df["Suggestion"] = labels

df.groupby("Suggestion").Score.mean().sort_values()

/home/arman/anaconda3/envs/openai_nlp/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Suggestion
0    55.272727
3    74.434783
1    78.857143
2    84.800000
Name: Score, dtype: float64

In [100]:
from sklearn.manifold import TSNE
import matplotlib
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, perplexity=15, random_state=42, init="random", learning_rate=200)
vis_dims2 = tsne.fit_transform(matrix)

x = [x for x, y in vis_dims2]
y = [y for x, y in vis_dims2]

for category, color in enumerate(["purple", "green", "red", "blue"]):
    xs = np.array(x)[df.Cluster == category]
    ys = np.array(y)[df.Cluster == category]
    plt.scatter(xs, ys, color=color, alpha=0.3)

    avg_x = xs.mean()
    avg_y = ys.mean()

    plt.scatter(avg_x, avg_y, marker="x", color=color, s=100)
plt.title("Clusters identified visualized in language 2d using t-SNE")

EOFError: marshal data too short